Lock Set Stop-loss button disabled if SL is set on collateral ratio, …
OasisDEX/oasis-borrow pull request #1035
Opened 2022-05-17 13:55 UTC by johnnieskywalker

…display message to close vault

# [Lock Set Stop-loss button disabled if SL is set on collateral ratio, display message to close vault](https://app.shortcut.com/oazo-apps/story/4400/lock-set-stop-loss-button-disabled-if-sl-is-set-on-collateral-ratio-display-message-to-close-vault)

  
## Changes 👷‍♀️
 
- Disabled adding stop loss on liquidation ratio
  
## How to test 🧪
  Try to set stop loss on liquidationRatio
See if you will see message and add stop-loss button will be disabled
![image](https://user-images.githubusercontent.com/6871923/168826327-bfac6dd5-97b8-458d-b566-fd7e1099debf.png)

2022-05-17 15:59 UTC, adamskrodzki commented
Also, original message says about 3% margin

https://discord.com/channels/837076147694207067/973226516978745396/973298564413415425

lets make it part of configuration

2022-05-18 10:31 UTC, piekczyk requested changes

2022-05-18 10:31 UTC, piekczyk commented on components/vault/ProtectionControl.tsx
> +  return !vault.debt.isZero() && vault.debt.isGreaterThan(dustLimit) ? (
not obligatory but you can use `gt` instead of `isGreaterThan`

2022-05-18 10:31 UTC, piekczyk commented on features/automation/protection/controls/AdjustSlFormLayout.tsx
> +export function slCollRatioIsAtLiquidationRatio(selectedSLValue: BigNumber, ilkData: IlkData) {
name should be adjusted since we added margin here, for example `slCollRatioNearLiquidationRatio`

2022-05-18 10:31 UTC, piekczyk commented on public/locales/en/common.json
> +    "coll-ratio-close-to-current": "Your Stop-Loss Trigger Col. Ratio is very close to your current Col. Ratio. Only continue if this is intended and understand your Vault could be closed with a smal
`Col. Ratio.` or should be `Coll. Ratio.`? Just wondering.

2022-05-18 10:31 UTC, piekczyk commented on features/automation/protection/controls/AdjustSlFormLayout.tsx
> +  return selectedSLValue.isLessThanOrEqualTo(ilkData.liquidationRatio.multipliedBy(100).plus(margin))
`isLessThanOrEqualTo` is `lte` but not obligatory ;)

2022-05-18 13:22 UTC, piekczyk approved these changes

2022-05-18 13:23 UTC, merged

2022-05-19 09:07 UTC, johnnieskywalker commented on public/locales/en/common.json
> +    "coll-ratio-close-to-current": "Your Stop-Loss Trigger Col. Ratio is very close to your current Col. Ratio. Only continue if this is intended and understand your Vault could be closed with a smal
it should I've missed this one also copy needs to be reviewed