Top assets and positions
OasisDEX/oasis-borrow pull request #1048
Opened 2022-05-19 12:10 UTC by sennett

# [Top assets and positions](https://app.shortcut.com/oazo-apps/story/3793/create-top-5-positions)
  
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/3783198/169262671-39a105ac-88c7-496b-ac8b-635994df7152.png">

## Changes 👷‍♀️
- adds a new box for top assets and positions.  This includes stuff in the users wallet, as well their maker vaults (encoded as `Position`s)
- hides this box if there are no positions.
- assets open a menu that contains things people can do with an asset - clicking through takes them to the landing page for that asset
  
## Tech changes
- creates a new concept - position.  Not much in it right now, but the idea is Maker vaults can be exposed as positions.  Other concepts from other protocols can also be surfaced as positions in the future.
- new tokenPriceUsd(tokens: Array<string>) pipe, using a new ticker from coingecko in addition to coinpaprika and coinbase.

## How to test 🧪
1. hardhat
2. enable `Earn` feature (UI is expected to be janky with the rest of the page - it will not get released like this)
3. grab some erc-20 assets using https://github.com/OasisDEX/multiply-proxy-actions/blob/develop/tasks/transfer-erc20.ts
4. play around with creating some positions from the positions overview panel
5. play around adjusting some positions.
6. check the piechart percentages
7. do this on mobile.

2022-05-19 12:24 UTC, sennett commented on features/automation/protection/common/UITypes/SwapWidgetChange.ts
> +}
Not sure if this is right location for this file.

2022-05-19 15:48 UTC, jakubswierczek commented on theme/index.tsx
> +      background: '#FFFFFF',
use color from `oasisBaseTheme`

2022-05-19 15:48 UTC, jakubswierczek commented on helpers/productCards.ts
> +} = _(genericFilters)
do we need to use lodash?

2022-05-19 15:48 UTC, jakubswierczek commented on features/vaultsOverview/pipes/positionsOverviewSummary.ts
> +const tokensWeCareAbout: Array<string> = uniq(tokenList.tokens.map((t) => t.symbol.toUpperCase()))
good name ;)

2022-05-19 15:48 UTC, jakubswierczek commented on features/vaultsOverview/pipes/assetActions.ts
> +type ProductCategory = 'multiply' | 'borrow' | 'earn'
this type should be placed in a global place

2022-05-19 15:48 UTC, jakubswierczek commented on features/vaultsOverview/pipes/assetActions.ts
> +        path: `/multiply`,
maybe we can put the paths in some config object?

2022-05-19 15:48 UTC, jakubswierczek commented on features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
> +        background: '#FFFFFF',
use values from theme

2022-05-19 15:48 UTC, jakubswierczek commented on features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
> +        pt: '11px',
11? wired value

2022-05-20 01:45 UTC, ferni commented on features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
> +        Top {topAssetsAndPositions.length} Assets and Positions
Can you add this to the lang file?

2022-05-20 03:08 UTC, ferni commented on features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
> +        {(positionsOverviewSummary) => {
I don't understand the usage of this callback. Is this a common pattern?

2022-05-20 09:05 UTC, sennett commented on helpers/productCards.ts
> +} = _(genericFilters)
`genericFilters` is an object so I went for that rather than transform into an array and back.

2022-05-20 09:13 UTC, sennett commented on features/vaultsOverview/pipes/assetActions.ts
> +type ProductCategory = 'multiply' | 'borrow' | 'earn'
Yup completely agree.  Discussion needed as to where, because right now we have no centralised place I don't think.  For me we are missing a folder `/domain` for these concepts, and I also think that a bunch of pipes inside `/features` and things inside `/blockchain` could also belong there.  For this reason I think this is not something to solve in this PR.

2022-05-20 09:19 UTC, sennett commented on features/vaultsOverview/pipes/assetActions.ts
> +        path: `/multiply`,
I'm not sure.  What's the benefit of doing this?  I guess we get some typesafety with the path always existing?  Where would this config live?

2022-05-20 09:23 UTC, sennett commented on features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
> +        background: '#FFFFFF',
That's a good point - we'd get compile-time safety from this rather than a magic string. I'll make a config file for product categories.

2022-05-20 09:30 UTC, sennett commented on features/vaultsOverview/pipes/assetActions.ts
> +type ProductCategory = 'multiply' | 'borrow' | 'earn'
Ah I moved this to a file in `config/product-categories` along with the type above.

2022-05-20 09:31 UTC, sennett commented on features/vaultsOverview/pipes/assetActions.ts
> +        path: `/multiply`,
That's a good point - we'd get compile-time safety from this rather than a magic string. I'll make a config file for product categories.

2022-05-20 10:39 UTC, sennett commented on features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
> +        pt: '11px',
This is the value I needed to use to make the designs look the same: https://www.figma.com/file/kAPyiF2JpYre2pgxiYunEr/Oasis-Master?node-id=6466%3A42432

2022-05-23 06:59 UTC, jakubswierczek approved these changes

2022-05-24 14:08 UTC, BackToTheCode submitted a review, later dismissed

2022-05-25 04:31 UTC, ferni commented
The position of the Swap widget seems to have changed:
![Screen Shot 2022-05-25 at 01 29 21](https://user-images.githubusercontent.com/653586/170180129-62911f54-6d6b-4363-a565-0667be5e76e0.png)

2022-05-25 04:34 UTC, ferni requested changes
The position of Swap widget seems to have changed.

![Screen Shot 2022-05-25 at 01 29 21](https://user-images.githubusercontent.com/653586/170180436-31a9a71f-619c-4207-a3e8-900a8e6e1249.png)

2022-05-27 08:59 UTC, jakubswierczek approved these changes

2022-05-27 09:00 UTC, merged

2022-05-27 09:00 UTC, sennett commented
> 

@ferni this was resolved and we merged in.  Good spot.