Lw/redirect to close vault
OasisDEX/oasis-borrow pull request #1051
Opened 2022-05-23 08:16 UTC by johnnieskywalker

[redirecting from sl at liquidation to dai payback](https://app.shortcut.com/oazo-apps/story/4330/redirect-user-to-close-vault-when-they-attempt-to-set-a-stop-loss-that-would-result-in-vault-closure-at-next-price)
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-05-23 16:02 UTC, adamskrodzki requested changes
Why merge to dev not to sl-re-release?

2022-05-23 16:02 UTC, adamskrodzki commented on features/automation/protection/controls/AdjustSlFormLayout.tsx
> +  const margin = 5
Make this 5 configurable value imported from common place, like default_slippage for example let's have all magic numbers in one place

2022-05-24 08:24 UTC, johnnieskywalker commented on features/automation/protection/controls/AdjustSlFormControl.tsx
> +      ? new BigNumber(5)
`sliderBoundry` would be proper name I guess

2022-05-24 10:26 UTC, adamskrodzki commented on features/borrow/manage/containers/ManageVaultEditing.tsx
> +  useEffect(() => {
what this code is responsible for?

2022-05-26 12:11 UTC, johnnieskywalker commented on components/MessageCard.tsx
> +export function MessageCard({ messages, type, withBullet = true, handleClick }: NoticeCardProps) {
Keep clickable MessageCard as it was implemented :+1:  but not used or remove it because YAGNI :-1: ?

2022-05-26 13:49 UTC, piekczyk requested changes

2022-05-26 13:49 UTC, piekczyk commented on components/MessageCard.tsx
> +export function MessageCard({ messages, type, withBullet = true, handleClick }: NoticeCardProps) {
I think currently there is no need to keep functionality like that, but it can stay as well. It is up to you.

2022-05-26 13:49 UTC, piekczyk commented on features/automation/protection/controls/AdjustSlFormLayout.tsx
> +      ``
:)

2022-05-26 13:49 UTC, piekczyk commented on features/borrow/manage/containers/ManageVaultEditing.tsx
> +  // const [uiState] = useUIChanges<BorrowPillChange>(BORROW_VAULT_PILL_CHANGE_SUBJECT)
do we need this commented block?

2022-05-26 13:49 UTC, piekczyk commented on features/userSettings/userSettings.ts
> +export const DEFAULT_SLIDER_BOUNDRY = 5
BOUNDARY, I guess if its used only in the scope of automation it should be moved to path related to automation. Also name should be self explanatory i.e `DEFAULT_SL_SLIDER_BOUNDARY` or something similar.

2022-05-26 14:50 UTC, johnnieskywalker commented on features/automation/protection/controls/AdjustSlFormLayout.tsx
> +      ``
interesting that linter didn't complained about it :D

2022-05-26 14:51 UTC, johnnieskywalker commented on features/borrow/manage/containers/ManageVaultEditing.tsx
> +  // const [uiState] = useUIChanges<BorrowPillChange>(BORROW_VAULT_PILL_CHANGE_SUBJECT)
nope

2022-05-26 15:11 UTC, johnnieskywalker commented on features/userSettings/userSettings.ts
> +export const DEFAULT_SLIDER_BOUNDRY = 5
You'e right, also we don't allow user to configure it or change default

2022-05-27 07:08 UTC, piekczyk submitted a review, later dismissed

2022-05-27 10:14 UTC, adamskrodzki approved these changes

2022-05-27 10:14 UTC, johnnieskywalker commented on components/AppContext.ts
> -  const uiChanges = initializeUIChanges()
It's still there it was just duplicated during resolving conflicts https://github.com/OasisDEX/oasis-borrow/blob/02e3bca5ad402050abba832fbad382bd1b042bb8/components/AppContext.ts#L787

2022-05-27 10:24 UTC, adamskrodzki approved these changes

2022-05-27 10:29 UTC, merged