New sidebars for manage borrow vault
OasisDEX/oasis-borrow pull request #1063
Opened 2022-05-25 15:39 UTC by piotrkonowrocki

# [New sidebars for manage borrow vault](https://app.shortcut.com/oazo-apps/story/4226/implement-managing-borrow-vault-according-to-new-design)

New sidebars design implemented using current pipelines.
Also small updates to previous flows: open borrow vault and open multiply vault.
  
## Changes 👷‍♀️

TBD
  
## How to test 🧪

TBD

2022-05-26 08:09 UTC, johnnieskywalker commented
Component looks and behaves as expected, also reset works

![image](https://user-images.githubusercontent.com/6871923/170445816-c3c05d73-044b-4d9d-81dc-f930acfbaa58.png)
![image](https://user-images.githubusercontent.com/6871923/170445887-fbe5e219-b316-4145-9a58-782e79244578.png)

User is able to withdraw collateral, payback DAI

![image](https://user-images.githubusercontent.com/6871923/170446067-d978ad82-d417-4fb7-b5ed-d333ace70aee.png)


![image](https://user-images.githubusercontent.com/6871923/170446112-0d8ca4e6-12b0-4cc5-a524-8614fabe4823.png)
![image](https://user-images.githubusercontent.com/6871923/170446161-6fdde7bd-4f36-446f-b24c-55b3edf4d311.png)

![image](https://user-images.githubusercontent.com/6871923/170446209-013290b4-ec05-4bc9-96d7-df28f7dd061a.png)
![image](https://user-images.githubusercontent.com/6871923/170446260-45ff0e51-8617-49cb-9332-ba8e29462fd4.png)

Generating DAI and adding more collateral

![image](https://user-images.githubusercontent.com/6871923/170446405-403ba07d-c24d-465b-b038-cd8e483e22f4.png)

![image](https://user-images.githubusercontent.com/6871923/170446463-2277079b-71ca-4b57-86e2-c97fc2f10595.png)

2022-05-26 08:22 UTC, johnnieskywalker requested changes
Just one small minor comment

2022-05-26 08:22 UTC, johnnieskywalker commented on features/sidebar/isDropdownDisabled.ts
> +    case 'manageWaitingForApproval':
Couldn't this whole switch be just an if statement that returns true for `manageWaitingForApproval` and false for every other value ?

2022-05-26 08:25 UTC, piotrkonowrocki commented on features/sidebar/isDropdownDisabled.ts
> +    case 'manageWaitingForApproval':
But there are 13 stages that returns `true`, not just `manageWaitingForApproval`. I can change it from `switch` to `if` if you think that would be better, but I thought that `switch` would make it easier to read. In `if` I would have to put 12 `ORs`. What do you think?

2022-05-26 08:28 UTC, johnnieskywalker commented on features/sidebar/isDropdownDisabled.ts
> +    case 'manageWaitingForApproval':
ok it could return false for that just one case and true for every else but indeed it's maybe more readable, so nevermind approving changes

2022-05-26 08:28 UTC, johnnieskywalker approved these changes

2022-05-26 10:49 UTC, johnnieskywalker approved these changes

2022-05-26 12:34 UTC, piekczyk commented on components/ActionPills.tsx
> +            key={k}
key should be on Box element

2022-05-26 13:03 UTC, piekczyk commented on features/multiply/open/containers/sidebar/SidebarOpenMultiplyVaultEditingState.tsx
> +            <Text variant="paragraph1" sx={{ fontWeight: 'semiBold' }}>
semantics

2022-05-26 13:04 UTC, piekczyk commented on features/multiply/open/containers/sidebar/SidebarOpenMultiplyVaultEditingState.tsx
> +            <Text variant="paragraph1" sx={{ fontWeight: 'semiBold' }}>
...and below as well

2022-05-26 13:39 UTC, piotrkonowrocki commented on components/vault/sidebar/SidebarManageBorrowVaultManageStage.tsx
> +    if (props.stage !== 'manageSuccess') setVaultChanges(props)
Yes, but that's not my idea, this is something taken straight from old version of sidebar. Without that use effect, on the success page changes table keeps updating and it stops displaying changes that you just made and starts displays changes that would happen if you do similar transaction one again.

2022-05-26 14:00 UTC, piotrkonowrocki commented on components/sidebar/SidebarSectionHeaderSelect.tsx
> +    setActiveItem(items.filter((item) => item.panel === forcePanel)[0])
Fixed.

2022-05-26 14:01 UTC, piotrkonowrocki commented on components/sidebar/SidebarSectionHeaderSelect.tsx
> +        opacity: !disabled ? 1 : 0.5,
`!disabled` is default stage, that's why I started with it. Setting `disabled` on `true` is deviation, so it should follow default case.

2022-05-26 14:02 UTC, piotrkonowrocki commented on components/vault/sidebar/SidebarManageBorrowVaultEditingStage.tsx
> +      maxAmountLabel={'Balance'}
Fixed.

2022-05-26 14:02 UTC, piotrkonowrocki commented on components/vault/sidebar/SidebarManageBorrowVaultEditingStage.tsx
> +      maxAmountLabel={'Max'}
Fixed.

2022-05-26 14:02 UTC, piotrkonowrocki commented on components/vault/sidebar/SidebarManageBorrowVaultEditingStage.tsx
> +      token={'DAI'}
Fixed.

2022-05-26 14:02 UTC, piotrkonowrocki commented on features/multiply/open/containers/sidebar/SidebarOpenMultiplyVaultEditingState.tsx
> +            <Text variant="paragraph1" sx={{ fontWeight: 'semiBold' }}>
Fixed.

2022-05-27 07:38 UTC, piekczyk approved these changes

2022-05-27 07:43 UTC, merged