Added stop loss step to open borrow flow
OasisDEX/oasis-borrow pull request #1078
Opened 2022-06-02 10:46 UTC by piekczyk

# [Added stop loss step to open borrow flow](https://app.shortcut.com/oazo-apps/story/4039/add-sl-step-transitions-and-handling-to-borrow-form-opening-flow)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- Added stop loss step to open borrow flow
  
## How to test 🧪
  <Please explain how to test your changes>
- use borrow open flow and feature toggle flag StopLossOpenFlow

2022-06-02 13:38 UTC, johnnieskywalker requested changes
Probably OpenVaultButton misses `stopLossEditing` case

2022-06-02 14:13 UTC, johnnieskywalker commented
Tried on goerli with sl
![image](https://user-images.githubusercontent.com/6871923/171649204-bc127839-e823-4c2b-ae89-bd79fa47883e.png)

2022-06-02 14:15 UTC, johnnieskywalker commented on components/vault/sidebar/SidebarOpenBorrowVault.tsx
> +  const flow: SidebarFlow = !isStopLossEditingStage ? 'openBorrow' : 'addSl'
addStopLoss would be better name and more consistent with others

2022-06-02 14:17 UTC, johnnieskywalker approved these changes
Flow is implemented as in design, just added one minor comment

2022-06-03 07:10 UTC, piekczyk commented on components/vault/sidebar/SidebarOpenBorrowVault.tsx
> +  const flow: SidebarFlow = !isStopLossEditingStage ? 'openBorrow' : 'addSl'
for now I will leave it as it is because this change will generate conflicts on Piotr's sidebar refinement branch

2022-06-03 07:12 UTC, merged