Gf/basic buy form info
OasisDEX/oasis-borrow pull request #1102
Opened 2022-06-09 15:13 UTC by George-field

# [Add info section for basic buy & basic sell](https://app.shortcut.com/oazo-apps/story/3872/basic-sell-changes-information)

Covers both buy and sell info tickets.
- 3872
- 3871
  
## Changes 👷‍♀️
- Added a new reusable info section component
- added a new item component to render contents of a list of items
  
## How to test 🧪
Go to OpenVaultView.tsx and update the current sidebar there to the following. Modify the items array below to change the content that appears in the info section.

```
<SellInfoSection
            colRatioAfterSell={'200'}
            multipleAfterSell={'2'}
            ratiotoPeformSell={'250'}
            nextSellPrice={{
              value: '1,295.00',
              dropDownValues: [
                {
                  label: 'price',
                  value: '$1,250.00',
                },
                {
                  label: 'price',
                  value: '$1,350.00',
                }
              ]
            }}
            setupTransactionCost={'150.00'}
            slippageLimit={'0.6'}
            collatAfterNextSell={{
              value: '11.2345',
              secondaryValue: '345,234'
            }}
            outstandingDebtAfterSell={{
              value: '657,890',
              secondaryValue: '567,909'
            }}
            ethToBeSoldAtNextSell={'12.32'}
            estimatedTransactionCost={{
              value: '$250',
              dropDownValues: [
                {
                  label: 'price',
                  value: '$123.00'
                }
              ]
            }}
          />

```

2022-06-10 08:30 UTC, piotrkonowrocki requested changes
1. It's done in old designs, I believe it should be done in new one?
![image](https://user-images.githubusercontent.com/16230404/173024103-c2d1885a-d358-49de-9334-2c5991c2c05e.png)
2. We already have components to cover that, please take a look at for example `SidebarOpenBorrowVaultEditingStage`, inside of it is a `OpenVaultChangesInformation` component that is a wrapper for set of two components: `VaultChangesInformationContainer` and `VaultChangesInformationItem`. With that you should be able to create that changes table and it will be consistent with existing ones.
3. I don't know if that components that I mentioned have the ability to put something with expandable arrow inside of them or do you need to extend that component, but I strongly suggest to use `ExpandableArrow` component instead of simple svg, because it has nice animation. If that component already has option to put something in accordion, maybe it's a good moment to redesign it so it also uses `ExpandableArrow`?

2022-06-14 12:18 UTC, George-field commented
Added some more changes, you can now test by using the following code example

```
<SellInfoSection
            colRatioAfterSell={'200'}
            multipleAfterSell={'2'}
            ratiotoPeformSell={'250'}
            nextSellPrice={{
              value: '1,295.00',
              dropDownValues: [
                {
                  label: 'price',
                  value: '$1,250.00',
                },
                {
                  label: 'price',
                  value: '$1,350.00',
                }
              ]
            }}
            setupTransactionCost={'150.00'}
            slippageLimit={'0.6'}
            collatAfterNextSell={{
              value: '11.2345',
              secondaryValue: '345,234'
            }}
            outstandingDebtAfterSell={{
              value: '657,890',
              secondaryValue: '567,909'
            }}
            ethToBeSoldAtNextSell={'12.32'}
            estimatedTransactionCost={{
              value: '$250',
              dropDownValues: [
                {
                  label: 'price',
                  value: '$123.00'
                }
              ]
            }}
          />
```

2022-06-15 11:05 UTC, piotrkonowrocki requested changes
One additional note, but I don't feel competent enough about codebase to suggest solution. @piekczyk, could you tell what do you think about files structure? I know that some time ago you split automation into optimization and protection separately. Should new components created here be placed accordingly in those directories or in new aggregate one like George did it?

2022-06-20 13:25 UTC, piotrkonowrocki approved these changes

2022-06-20 13:27 UTC, merged