Gf/max gas fee section
OasisDEX/oasis-borrow pull request #1147
Opened 2022-06-20 15:38 UTC by George-field

# [Max Gas Fee Component][(https://shortcutLink](https://app.shortcut.com/oazo-apps/story/4652/max-gas-fee-section))

  
## Changes 👷‍♀️
Added a new max gas fee component
modified the existing Item component to account for different props
  
## How to test 🧪
  Add the following code to a view with a sidebar

```
 <MaxGasFeeSection />
```

2022-06-20 19:10 UTC, johnnieskywalker commented on components/infoSection/Item.tsx
> +                {value && <>{typeof value === 'object' ? value : `${value}`}</>}
[minor] How about `value instanceof Object` ? 
`typeof value === 'object'` would return `true` also if value is `null`. 
However I'm not sure which is better as result of both would be very similar.

2022-06-21 07:41 UTC, piekczyk requested changes

2022-06-21 07:41 UTC, piekczyk commented on components/infoSection/Item.tsx
> +            <Text
add semantics `as="..."`

2022-06-21 08:48 UTC, George-field commented on components/infoSection/Item.tsx
> +                {value && <>{typeof value === 'object' ? value : `${value}`}</>}
Ah, I was trying to find if there was something like ```React.isValidElement``` I will use that, thanks :)

2022-06-21 09:13 UTC, piekczyk approved these changes

2022-06-21 10:01 UTC, merged

2022-06-21 10:19 UTC, johnnieskywalker commented on components/infoSection/Item.tsx
> +                {value && <>{typeof value === 'object' ? value : `${value}`}</>}
gj