Add Cookie Policy [DO NOT MERGE]
OasisDEX/oasis-borrow pull request #1200
Opened 2022-07-05 10:10 UTC by halaprix

# [Add cookie policy](https://app.shortcut.com/oazo-apps/story/5030/add-cookie-policy)

**DO NOT MERGE until we are ready with updated TOS**

  
## Changes 👷‍♀️
Added cookie policy that can be reached by either going to /cookie or clicking the link in the footer
  
## How to test 🧪
- click the `Cookie Policy` link in the footer

2022-07-05 17:06 UTC, johnnieskywalker requested changes

2022-07-05 17:06 UTC, johnnieskywalker commented on features/content/index.tsx
> +  return <ContentComp sx={{ table: { background: '1px solid black !important' } }} />
Redundant style, properties from theme do their job

2022-07-06 06:34 UTC, piekczyk requested changes

2022-07-06 06:41 UTC, halaprix commented on pages/cookie.tsx
> +      <Box sx={{ width: '100%', table: { background: '1px solid black !important' } }}>
totally forgotten about it. removed

2022-07-06 06:45 UTC, halaprix commented on theme/index.tsx
> +        border: '1px solid black',
ok

2022-07-06 10:11 UTC, johnnieskywalker approved these changes

2022-07-19 13:59 UTC, closed without merging