Referrals dashboard for disconnected wallet
OasisDEX/oasis-borrow pull request #1262
Opened 2022-07-14 06:34 UTC by halaprix

# [Title](https://app.shortcut.com/oazo-apps/story/5259/fix-referral-flow-after-testing)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
added conditions that will show the referral marketing page to a user that :
- is not connected and tries to see others user referral dashboard
- is connected and tries to see others user referral dashboard
- disconnects wallet when viewing their dashboard
  
## How to test 🧪
go to http://localhost:3000/referrals/0xbebe3A65A762021b873a1e7212a7254dA5453b82

when:
- not connected
- conencted with wour wallet

2022-07-14 11:37 UTC, johnnieskywalker commented
viewing other dashboard when connected 
![image](https://user-images.githubusercontent.com/6871923/178973856-68e26236-1149-48f7-9ce9-1277e46e9e69.png)

2022-07-14 11:39 UTC, johnnieskywalker requested changes
Can't see nothing when connected and not connected viewing other user dashboard or mine 
![image](https://user-images.githubusercontent.com/6871923/178974163-de672881-2316-42d5-8211-44d4d30a5966.png)

2022-07-14 14:17 UTC, piekczyk approved these changes

2022-07-18 09:47 UTC, johnnieskywalker approved these changes

2022-07-18 10:05 UTC, merged