New privacy policy 07.07.2022
OasisDEX/oasis-borrow pull request #1267
Opened 2022-07-14 14:01 UTC by halaprix

# [Update the privacy policy](https://app.shortcut.com/oazo-apps/story/5242/update-the-privacy-policy)

  
## Changes 👷‍♀️
updated the privacy policy
  
## How to test 🧪
go to `/privacy` and read the entire text.
thank you

2022-07-14 17:18 UTC, johnnieskywalker requested changes

2022-07-14 17:18 UTC, johnnieskywalker commented on features/content/privacy/en.mdx
> +The Site is using cookies. Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as
line 25 (can't comment it as it wasn't edited). However not 100% sure about this one.
`Our service providers analyses this information and provides us with aggregate reports. `
shouldn't it be 
``Our service providers analyse this information and provide us with aggregate reports. ``

So one provider analyses but multiple providers analyse?

2022-07-14 17:18 UTC, johnnieskywalker commented on features/content/privacy/en.mdx
> +You may contact us by email to the following email address: **[legal@oasis.app.](mailto:legal@oasis.app.)** We use the data that you provide in an email to us, which you may give voluntarily, only in
line 67
shouldn't it be 
`we no longer need` ? instead of `we no longer needs` ?

2022-07-15 06:26 UTC, halaprix commented on features/content/privacy/en.mdx
> +This Privacy Policy provides our privacy policy regarding the nature, purpose, use, and sharing of personal data or other information collected from the users of the oasis.app website and other websi
copy paste from the docs ;| fixed

2022-07-15 06:26 UTC, halaprix commented on features/content/privacy/en.mdx
> +The Site is using cookies. Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as
you are right - fixed

2022-07-15 06:27 UTC, halaprix commented on features/content/privacy/en.mdx
> +You may contact us by email to the following email address: **[legal@oasis.app.](mailto:legal@oasis.app.)** We use the data that you provide in an email to us, which you may give voluntarily, only in
right - fixed. There were some other things grammarly caught.
But there are still things that make no sense to me, like `the processing is unlawful and you oppose the erasure of the personal data and requests instead the restriction of their use instead;`

2022-07-22 06:29 UTC, closed without merging