wip cm sidebar blank
OasisDEX/oasis-borrow pull request #1268
Opened 2022-07-14 14:58 UTC by johnnieskywalker

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-07-18 15:46 UTC, johnnieskywalker commented
![image](https://user-images.githubusercontent.com/6871923/179550397-b1951d7a-abd5-4179-aea8-9dcd686ef14e.png)

2022-07-22 12:57 UTC, johnnieskywalker commented
![image](https://user-images.githubusercontent.com/6871923/180443831-c5d1a769-0d9b-43e1-9adc-801136b75248.png)

2022-07-27 10:01 UTC, piekczyk requested changes

2022-07-27 11:33 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardTargetMultiple.tsx
> +    targetMultiple: `${targetMultiple?.toFixed(1)}x`,
Fixed.

2022-07-27 11:33 UTC, piotrkonowrocki commented on features/automation/optimization/controls/ConstantMultipleDetailsLayout.tsx
> +                afterTotalCost={undefined}
Fixed.

2022-07-27 14:36 UTC, johnnieskywalker commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +    SLIDER_MAX_FOR_BIG_VAULTS,
we discussed it with @adamskrodzki see comments in task https://app.shortcut.com/oazo-apps/story/5216/create-constant-multiple-form

2022-07-28 05:35 UTC, piekczyk submitted a review, later dismissed

2022-08-02 09:02 UTC, piotrkonowrocki approved these changes

2022-08-02 09:02 UTC, piekczyk approved these changes

2022-08-02 09:02 UTC, merged