Gf/notifications center modal
OasisDEX/oasis-borrow pull request #1269
Opened 2022-07-14 15:32 UTC by George-field

# [Create Notifications Centre Widget](https://app.shortcut.com/oazo-apps/story/4790/notification-center-ui-component-create-notification-centre-widget)
  
## Changes 👷‍♀️
- Added notification centre widget
- Added slide in and out animation
- Adjusted header spacing as per designs
  
## How to test 🧪
 To test, turn on the Notifications feature flag in local storage, refresh and  click the notifications icon at the top right.

2022-07-14 17:06 UTC, johnnieskywalker commented
Feature works as expected,  notifications have animation of sliding from right to left. Leaving just few minor comments.

on desktop
![image](https://user-images.githubusercontent.com/6871923/179040456-561e1949-bce8-4bff-bf1e-e9e41dfff250.png)

smaller screen
![image](https://user-images.githubusercontent.com/6871923/179040658-76e420c3-54e8-4d37-9a74-03d77a9fd3ac.png)

simulating Google Pixel 5 
![image](https://user-images.githubusercontent.com/6871923/179040920-68ac0f76-f3e8-4f54-b4a9-8c9cbbdc802e.png)

iPhone12
![image](https://user-images.githubusercontent.com/6871923/179041245-d24c3a9a-7d58-4f20-9860-3505c843cd40.png)

iPad Mini 
![image](https://user-images.githubusercontent.com/6871923/179041497-8045a2c0-bc5b-4e76-81e4-7608f0be15aa.png)

2022-07-14 17:06 UTC, johnnieskywalker requested changes
just address minor comments and we're good to go

2022-07-14 17:06 UTC, johnnieskywalker commented on components/notifications/NotificationsCenterHeader.tsx
> +          // height: '28px',
plz remove commented out properties

2022-07-15 13:03 UTC, piekczyk approved these changes

2022-07-15 13:07 UTC, johnnieskywalker approved these changes

2022-07-15 13:08 UTC, merged