Legal update [DO NOT MERGE]
OasisDEX/oasis-borrow pull request #1271
Opened 2022-07-15 08:08 UTC by halaprix

# [Update Cookie Banner](https://app.shortcut.com/oazo-apps/story/5243/update-cookie-banner)

  
## Changes 👷‍♀️
added `version` to the cookie policy settings

`Update the link from the Privacy Policy to the Cookie Policy in the copy`

`Update the copy from the marketing cookies to:
"Oasis.app uses anonymised cookies from adRoll to be able to apply retargeting campaigns on advertising platforms"`

`Standard untick the cookies, and only tick them when the user clicks accept`
- updated terms of service
- updatet privacy policy
- added cookie policy
- added GDPR copy (when newsletter input is onFocus)
  
## How to test 🧪
- go to the homepage - cookie banner should pop up automatically
- check if TOS modal popped up

2022-07-15 10:15 UTC, piekczyk requested changes

2022-07-15 10:15 UTC, piekczyk commented on components/CookieBanner.tsx
> +type Version = string
you used it just once so I guess you can just type version inline on line 42

2022-07-15 14:38 UTC, halaprix commented on components/CookieBanner.tsx
> +type Version = string
ok!

2022-07-15 14:53 UTC, piekczyk approved these changes

2022-07-19 10:47 UTC, piekczyk approved these changes

2022-07-19 15:03 UTC, merged