Gf/notification prefrences
OasisDEX/oasis-borrow pull request #1286
Opened 2022-07-19 14:13 UTC by George-field

# [Notifications Preferences](https://app.shortcut.com/oazo-apps/story/4887/manage-notifications-ui-component-notifications-on-off-switch)

  
## Changes 👷‍♀️
- Added notifications preferences cards & section
  
## How to test 🧪
- Enable notifications by turning on the feature toggle in local storage. Click the notification Icon in the top right, then select the settings icon in the top right of the notifications modal.

2022-07-25 15:30 UTC, johnnieskywalker requested changes

2022-07-25 15:30 UTC, johnnieskywalker commented on components/notifications/NotificationPrefrenceCard.tsx
> +interface NotificationPrefrenceCardPtops {
[minor][ a typo, `Props` is expected :D

2022-07-25 16:31 UTC, George-field commented on components/notifications/NotificationPrefrenceCard.tsx
> +interface NotificationPrefrenceCardPtops {
ah, dam it, thank you

2022-07-25 17:39 UTC, piekczyk requested changes

2022-07-25 17:39 UTC, piekczyk commented on ui/Toggle/Toggle.tsx
> +            // TODO: Possibly create a function to do this so that is more readable
I agree with TODO, if there is no other way to define these svgs we should definitely extract it to constant / function which returns it

2022-07-25 17:39 UTC, piekczyk commented on components/notifications/NotificationsCenter.tsx
> +            <Box>
maybe it is worth to extract it as for example `NotificationPreferencesWrapper` even though it is simple box for now

2022-07-26 09:44 UTC, piekczyk approved these changes

2022-07-26 14:18 UTC, johnnieskywalker approved these changes

2022-07-26 14:19 UTC, merged