Gf/notifications email prefrences
OasisDEX/oasis-borrow pull request #1308
Opened 2022-07-22 10:28 UTC by George-field

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-07-22 10:54 UTC, piotrkonowrocki requested changes
I have some issues with css/sx code, but there are recurring errors and I don't want to mark every one of them as separated comment.

Please update css to use more of our theme. There are a lot of colors or border radius values that are hardcoded, but should be taken from theme file. I also notices some of font sizes that are available in theme, like 8 or 16px, that are also hardcoded.

About some of the animations, what exactly is transitioning in them? Not specifying css selectors that suppose to transition can sometimes lead to unexpected behaviors, I suggest listing what exactly is animating instead of using `all` or providing just a duration.

Also, that's only suggestion, not request change, but I suggest using shorthands in `sx` objects, `marginLeft` -> `ml`, `paddingLeft` -> `pl` etc.

2022-07-22 10:54 UTC, piotrkonowrocki commented on components/notifications/NotificationsChangeEmailButton.tsx
> +          marginLeft: 'auto !important',
Is that necessary? `!important` should be last resorts, because from that point it could only go downhill. What is default value of that margin and is it possible to overwrite it without using importants?

2022-07-22 10:54 UTC, piotrkonowrocki commented on components/notifications/NotificationsEmailPrefrences.tsx
> +              Set up your email
Shouldn't that be in translations?

2022-07-22 10:54 UTC, piotrkonowrocki commented on components/notifications/NotificationsSetupSuccess.tsx
> +        <svg
Consider moving to global icons?

2022-07-22 10:54 UTC, piotrkonowrocki commented on helpers/formValidation.ts
> +    /^(([^<>()[\]\\.,;:\s@]+(\.[^<>()[\]\\.,;:\s@]+)*)|(.+))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
I'm wondering about that regex, have you used it somewhere before? I've been using different and it's much shorter: `^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$`. What do you think, is it missing something?

2022-07-22 12:08 UTC, George-field commented on components/notifications/NotificationsChangeEmailButton.tsx
> +          marginLeft: 'auto !important',
It is being overridden by an !important somewhere else in the code :(, I believe it is a default style that is being applied by the UI library.

2022-07-22 12:09 UTC, George-field commented on components/notifications/NotificationsEmailPrefrences.tsx
> +              Set up your email
yes, I missed that one

2022-07-22 12:09 UTC, George-field commented on helpers/formValidation.ts
> +    /^(([^<>()[\]\\.,;:\s@]+(\.[^<>()[\]\\.,;:\s@]+)*)|(.+))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
I'll go with your one, I just found that on stackoverflow if I am honest

2022-07-22 12:22 UTC, piotrkonowrocki commented on components/notifications/NotificationsChangeEmailButton.tsx
> +          marginLeft: 'auto !important',
That's exactly what I meant by saying that it can only go downhill from there. Someone already did that mistake earlier and it's forcing you to using `important` because of that. In that case I understand that it can't be done in any other way.

2022-07-26 09:57 UTC, piekczyk requested changes

2022-07-26 09:57 UTC, piekczyk commented on components/notifications/NotificationsSetupSuccess.tsx
> +        p: '16px',
3

2022-07-26 09:57 UTC, piekczyk commented on components/notifications/NotificationsSetupSuccess.tsx
> +export function NotificationsSetupSuccess() {
this component name is too general since it has hardcoded email-related copy

2022-07-26 09:57 UTC, piekczyk commented on components/notifications/NotificationsEmailPrefrences.tsx
> +              p: '16px',
3

2022-07-26 14:05 UTC, piotrkonowrocki approved these changes

2022-07-26 14:11 UTC, merged