Added notification handlers
OasisDEX/oasis-borrow pull request #1320
Opened 2022-07-27 12:09 UTC by piekczyk

# [Notification handler](https://app.shortcut.com/oazo-apps/story/4786/notifications-handler)
# [Notification Center Logic | Critical Notifications](https://app.shortcut.com/oazo-apps/story/4792/notification-center-logic-critical-notifications)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- added websockets handlers and mappers
  
## How to test 🧪
  <Please explain how to test your changes>

- api not prepared yet, download https://github.com/OasisDEX/notifications and initialize server using `yarn start websockets`, its required to get socket connection
- in `env.local` add following variable `NOTIFICATIONS_HOST=ws://localhost:3005`

2022-07-27 14:38 UTC, adamskrodzki commented on components/NotificationSocketProvider.tsx
> +    numberOfNotificationsHandler,
we still need this one ?

2022-07-27 14:41 UTC, adamskrodzki commented on components/NotificationSocketProvider.tsx
> +              firstRelevantDate: 1658296560,
I believe this one should be somehow relative to `now`

2022-07-27 14:42 UTC, adamskrodzki commented on components/NotificationSocketProvider.tsx
>    }, [jwtToken, socket])
why socket is here as well? doesnt it recreate socket oftenly?

2022-07-27 15:28 UTC, adamskrodzki commented on features/notifications/types.ts
> +  timestamp?: number
not needed parent message already have timestamp

2022-07-27 18:58 UTC, piotrkonowrocki requested changes

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/Header.tsx
> +            disabled={!notificationsState}
Are you sure this is the best way to do it? `notificationsState` represents interface, not simple `boolean`.

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/NotificationSocketProvider.tsx
> +          console.log(err.message)
Oopsie...

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/NotificationSocketProvider.tsx
> +          console.log(err.message)
...daisy

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/NotificationSocketProvider.tsx
> +              maxNumberOfNotifications: 50,
Maybe save it to the constant?

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/notifications/NotificationCard.tsx
> +function getNotificationCardSx({ isCritical, read }: { isCritical: boolean; read: boolean }) {
`isCritical` and `read` both are `boolean`, but only `isCritical` suggests that. I suggests using is/has/does naming convention for booleans.

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/notifications/NotificationCard.tsx
> +function getNotificationCardSx({ isCritical, read }: { isCritical: boolean; read: boolean }) {
I saw that `read` prop is passed and used in more places, so this is more of a general comment.

2022-07-27 18:58 UTC, piotrkonowrocki commented on components/notifications/NotificationCard.tsx
> +      <Text as="div" variant="paragraph3" sx={{ mb: 2, fontWeight: read ? 'body' : 'semiBold' }}>
Is there a reason why text should be a `div`?

2022-07-27 18:58 UTC, piotrkonowrocki commented on features/notifications/consts.ts
> +export const notificationPreferences = [
Missing translations.

2022-07-27 18:58 UTC, piotrkonowrocki commented on features/notifications/helpers.tsx
> +    : '[date unavailable]'
Missing translation for `'[date unavailable]'`.

2022-07-28 05:48 UTC, piekczyk commented on components/NotificationSocketProvider.tsx
>    }, [jwtToken, socket])
Socket is here because in order to create connection we need JWT token. Inside this useEffect hook you will see condition which checks whether socket is already initialized and prevent from multiple initializations. Additionally I added condition which verifies whether jwtToken changed (when someone switches connected accounts in for example metamask). If account has been changed socket is disconnected as is no longer valid and new socket connection is initialized.

2022-07-28 05:49 UTC, piekczyk commented on components/NotificationSocketProvider.tsx
> +              firstRelevantDate: 1658296560,
fixed

2022-07-28 05:55 UTC, piekczyk commented on features/notifications/types.ts
> +  timestamp?: number
fixed and marked `vaultId` as optional

2022-07-28 05:55 UTC, piekczyk commented on components/NotificationSocketProvider.tsx
> +              firstRelevantDate: 1658296560,
fixed

2022-07-28 05:59 UTC, piekczyk commented on components/Header.tsx
> +            disabled={!notificationsState}
I did it in that way because for short period of time `notificationsState` is `undefined` and we shouldn't allow user to click on it until data is there. If we introduce signature flow right after wallet connection I guess it won't be needed anymore but for now I think its simplest solution.

2022-07-28 06:00 UTC, piekczyk commented on components/NotificationSocketProvider.tsx
> +          console.log(err.message)
debugging hard :D fixed

2022-07-28 06:00 UTC, piekczyk commented on components/NotificationSocketProvider.tsx
> +          console.log(err.message)
fixed

2022-07-28 06:03 UTC, piekczyk commented on components/NotificationSocketProvider.tsx
> +              maxNumberOfNotifications: 50,
fixed

2022-07-28 06:05 UTC, piekczyk commented on components/notifications/NotificationCard.tsx
> +function getNotificationCardSx({ isCritical, read }: { isCritical: boolean; read: boolean }) {
good catch, I will ping Adam that we will need to update it on backend as well

2022-07-28 06:08 UTC, piekczyk commented on components/notifications/NotificationCard.tsx
> +      <Text as="div" variant="paragraph3" sx={{ mb: 2, fontWeight: read ? 'body' : 'semiBold' }}>
I couldn't manage to render `<Trans ... />` with arrow and link component as span or paragraphs. I changed it because `p` can't have `div` as child.

2022-07-28 06:15 UTC, piekczyk commented on features/notifications/consts.ts
> +export const notificationPreferences = [
added

2022-07-28 06:15 UTC, piekczyk commented on features/notifications/helpers.tsx
> +    : '[date unavailable]'
won't be needed anymore

2022-08-03 10:58 UTC, piotrkonowrocki commented on components/Header.tsx
> +            disabled={!notificationsState}
👌

2022-08-03 10:59 UTC, piotrkonowrocki commented on components/notifications/NotificationCard.tsx
> +      <Text as="div" variant="paragraph3" sx={{ mb: 2, fontWeight: read ? 'body' : 'semiBold' }}>
👌

2022-08-03 11:47 UTC, piotrkonowrocki approved these changes

2022-08-03 11:53 UTC, merged