Auto generated multipliers range
OasisDEX/oasis-borrow pull request #1337
Opened 2022-08-03 13:55 UTC by piotrkonowrocki

# [Auto generated multipliers range](https://app.shortcut.com/oazo-apps/story/5469/auto-generated-multipliers-range)

Updated list of possible multipliers available to choose from while setting up a Constant Multiple. Most of the ilks have static list of valid multipliers, as a fallback list generates automatically.

![image](https://user-images.githubusercontent.com/16230404/182621702-fa0fd258-df7b-40f2-ac53-be642e749649.png)
![image](https://user-images.githubusercontent.com/16230404/182625616-633bdef7-a811-481b-a480-71d4253ae1d1.png)
  
## Changes 👷‍♀️

- Added static lists for specifics ilks,
- created a method for auto generating as a fallback,
- refined, simplified and straighten some parts of the code related to CM UI changes and calculations,
- updated visuals to match figma designs,
  
## How to test 🧪

- Try to setup CM for vaults belonging to different ilks,
- please note that I DIDN'T test all the ilks if multiplier values are correct, I believe that should be a different story, I used values provided in here: https://www.notion.so/oazo/Ilk-multiples-1c616773bb9540b29e6124ff0955567c.

2022-08-03 14:29 UTC, johnnieskywalker commented on features/automation/basicBuySell/InfoSections/ConstantMultipleInfoSection.tsx
> +          value: formatPercent(slippage?.times(100) || zero, { precision: 2 }),
Correct me if it was discussed with someone. But I guess in such case we should get default slippage similarly as in userSettings

```ts
export const SLIPPAGE_DEFAULT = new BigNumber(0.005)

```

2022-08-03 14:29 UTC, johnnieskywalker commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +      multiplier: acceptableMultipliers[1],
I'm kinda confused why [1] ?

2022-08-03 14:33 UTC, piotrkonowrocki commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +      multiplier: acceptableMultipliers[1],
I had to choose something, it might be `[0]` or `[2]` as well, there's nothing behind it. If you don't have any multiplier selected or, for some reason, col ratio doesn't correspond to available ratios, the second item is selected.

2022-08-03 14:36 UTC, johnnieskywalker commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +      multiplier: acceptableMultipliers[1],
ok nevermind

2022-08-03 14:44 UTC, johnnieskywalker approved these changes

2022-08-04 03:58 UTC, piekczyk requested changes

2022-08-04 03:58 UTC, piekczyk commented on features/automation/basicBuySell/InfoSections/ConstantMultipleInfoSection.tsx
> +          value: formatPercent(slippage.times(100), { precision: 2 }),
So we will show hardcoded slippage in changes information? Do we know what is actual slippage on SC level?

2022-08-04 03:58 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +              items={acceptableMultipliers.map((multiplier) => {
since linter does not complain on using arrow function in callbacks maybe you could omit `return`

2022-08-04 03:58 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +              slippage={userSettings?.slippage}
hm, maybe user will choose slippage using user settings but do we pass this parameter to SC?

2022-08-04 08:45 UTC, piotrkonowrocki commented on features/automation/basicBuySell/InfoSections/ConstantMultipleInfoSection.tsx
> +          value: formatPercent(slippage?.times(100) || zero, { precision: 2 }),
In the end, slippage was removed at all from changes information, so irrelevant.

2022-08-04 08:45 UTC, piotrkonowrocki commented on features/automation/basicBuySell/InfoSections/ConstantMultipleInfoSection.tsx
> +          value: formatPercent(slippage.times(100), { precision: 2 }),
Slippage removed.

2022-08-04 08:45 UTC, piotrkonowrocki commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +              slippage={userSettings?.slippage}
Slippage removed.

2022-08-04 08:46 UTC, piotrkonowrocki commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +              items={acceptableMultipliers.map((multiplier) => {
It won't work, because I need multiplier parameter in the object that is created inside of that. I could move it to separated function, but I'm not sure if that has any added value.

2022-08-04 08:52 UTC, piotrkonowrocki commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +              items={acceptableMultipliers.map((multiplier) => {
`return` removed.

2022-08-04 09:49 UTC, piekczyk approved these changes

2022-08-04 09:49 UTC, merged