Gf/stop loss confirmation screen
OasisDEX/oasis-borrow pull request #1376
Opened 2022-08-18 07:15 UTC by George-field

# [Stop Loss Order Confirmation Screen](https://app.shortcut.com/oazo-apps/story/5353/stop-loss-add-order-summary-confirmation-screen)
  
## Changes 👷‍♀️
- Added a screen in the auto buy / auto sell flow for confirmation before confirming an order. 
  
## How to test 🧪
- Go through the add auto buy set up process
- You will see an additional screen in the flow

2022-08-18 10:31 UTC, piekczyk requested changes
I'm confused regarding this PR title and linked story since code changes are applied to AutoBuy and AutoSell flows. Stop Loss hasn't be touched here.

2022-08-18 10:31 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarAutoBuyConfirmationStage.tsx
> +      <MaxGasPriceSection
like I mentioned in one of the previous comments, I believe that we shouldn't show this section on confirmation screen

2022-08-18 10:31 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
> +              {isAddForm && !isConfirmation && (
shouldn't `isAddForm` and `isConfirmation` flags be totally unrelated? I guess `isConfirmation` check shouldn't be required here

2022-08-18 10:31 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
> +              {isConfirmation && (
do we plan to add confirmation step to removal flow as well?

2022-08-18 10:31 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
> +          if (!isConfirmation) {
if confirmation should be visible only in add trigger flow you should add here a condition which will verify that

2022-08-18 10:31 UTC, piekczyk commented on features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
> +          action: () => {
support for `Edit Order`  (which is basically a back button) is missing and also according to figma design we should show step number indicator. When fixing please verify it both for adding new trigger and when trigger is being updated

2022-08-18 10:31 UTC, piekczyk commented on features/automation/protection/common/UITypes/basicBSFormChange.ts
> +export const BASIC_BUY_SELL_FLOW_STATE_CHANGE = 'BASIC_BUY_SELL_FLOW_STATE_CHANGE'
is this constant used anywhere?

2022-08-18 10:31 UTC, piekczyk commented on features/automation/protection/common/UITypes/basicBSFormChange.ts
> +export type AUTOMATION_FORM_FLOW_STATE = 'confirmation' | 'editing'
is this constant used anywhere?

2022-08-18 10:31 UTC, piekczyk commented on features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
> +  isConfirmation,
all comments that I've added to `SidebarSetupAutoBuy` applies here as well

2022-08-18 10:31 UTC, piekczyk commented on helpers/functions.ts
> +  if (isConfirmation) return 'Edit Order'
missing translation

2022-08-18 10:31 UTC, piekczyk commented on tenderly.yaml
> +account_id: ""
please add this file to you local git ignore

2022-08-18 10:31 UTC, piekczyk commented on features/automation/protection/common/UITypes/basicBSFormChange.ts
> +  | { type: 'is-confirmation'; isConfirmation: boolean }
it seems that this flag is not reset properly on tx success

2022-08-22 07:10 UTC, George-field commented on features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
> +              {isAddForm && !isConfirmation && (
Its required because isAddForm would still be true?

2022-08-25 12:12 UTC, piekczyk requested changes

2022-08-25 12:12 UTC, piekczyk commented on helpers/functions.ts
> +  if (isConfirmation) return t('auto-buy.edit-order-btn')
edit order does not always display in confirmation step, please verify it

![image](https://user-images.githubusercontent.com/39706811/186658801-7dcf6cae-a750-4a5c-9441-f17fe6e3e08d.png)

2022-08-25 12:12 UTC, piekczyk commented on helpers/functions.ts
> +  if (isConfirmation) return t('auto-buy.edit-order-btn')
![image](https://user-images.githubusercontent.com/39706811/186659746-5ccc010a-e303-4797-a269-b97906cae3ea.png)

2022-08-25 12:12 UTC, piekczyk commented on features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
> +    ...(!firstStopLossSetup && createTextBtnConfig(stage, protectionState.isConfirmation)),
We should display either `Confirm` or `Retry`

![image](https://user-images.githubusercontent.com/39706811/186660150-be7d1c34-f281-47b1-a779-addc47559a74.png)

2022-08-25 12:12 UTC, piekczyk commented on features/automation/protection/controls/StopLossFormControl.tsx
> +  const [currentForm] = useUIChanges<ProtectionModeChange>(PROTECTION_STATE_UPDATE)
I think bug is introduced here. Due to this change you wont be able to go to cancel stop loss form.

2022-08-25 12:12 UTC, piekczyk commented on features/automation/protection/controls/StopLossFormControl.tsx
> +  console.log(currentForm, 'form in StopLossFormContrl')
to be removed

2022-08-26 08:25 UTC, George-field commented on features/automation/protection/controls/AutoSellFormControl.tsx
> +  const isProgressStage = (txStatus && progressStatuses.includes(txStatus)) || false
Otherwise it will be undefined and it throws an error. Typescript compiler moans also saying boolean | undefined . The alternative I guess is I could do ```as boolean```

2022-08-26 08:26 UTC, George-field commented on features/automation/protection/controls/StopLossFormControl.tsx
> +  const [currentForm] = useUIChanges<ProtectionModeChange>(PROTECTION_STATE_UPDATE)
Ah yeah, my bad, forgot to change that back

2022-10-24 13:28 UTC, marcinciarka commented
Closing old PR (cleaning up PR tab).

2022-10-24 13:28 UTC, closed without merging