introduced constant multiple read only safe switch flag
OasisDEX/oasis-borrow pull request #1379
Opened 2022-08-18 11:51 UTC by johnnieskywalker

# [Constant Multiple Readonly safety switch](https://app.shortcut.com/oazo-apps/story/5631/safety-switch)

  
## Changes 👷‍♀️
-introduced constantMultipleReadOnly flag
  
## How to test 🧪
  
- Both constant multiple and constant multiple read only off user shouldn't see any CM features|
![image](https://user-images.githubusercontent.com/6871923/185387540-65e02fe7-89ee-47e4-b20c-bc3b4a27111d.png)

- all CM and BS flags off user is informed that it's not possible to access optimization at the moment

![image](https://user-images.githubusercontent.com/6871923/185387947-22398b47-43cf-4003-b034-122f40052759.png)

- BasicBS on but Constant Multiple Read Only Enabled - ?

2022-08-19 11:07 UTC, piekczyk commented
Summary should be the same as when read only flag is not enabled
![image](https://user-images.githubusercontent.com/39706811/185605667-0658336e-3bc6-41c4-b954-c8d213c12f76.png)

2022-08-19 11:09 UTC, piekczyk commented
Combination of read only flags (BS and CM) should should show banner in optimization tab only if there are no active optimization. If there is active either Auto-Buy or Constant-Multiple we need to give chance to the user to remove existing trigger. 
![image](https://user-images.githubusercontent.com/39706811/185606106-89149e08-43c4-4f0d-b05d-d90ccbe5327a.png)

2022-08-19 12:11 UTC, johnnieskywalker commented on components/vault/OptimizationControl.tsx
> +            vaultHasNoActiveTrigger: !vaultHasActiveAutoBuyTrigger,
After updating condition with no triggers:

both BS and CM in RO
![image](https://user-images.githubusercontent.com/6871923/185615071-a4d791ac-8797-435a-ac13-389156698330.png)

CM enabled (I doubt there will be case when BS will be off but CM will remain enabled but anyway it works)
![image](https://user-images.githubusercontent.com/6871923/185615240-65933bac-e4aa-412b-9e7b-207588041a45.png)

mission CM in RO and BS on ...

2022-08-22 10:19 UTC, adamskrodzki commented
Why on all screens also Notifications are true and Exchange ? are those dependencies ? If no (and I guess no) they should be false

2022-08-22 10:46 UTC, johnnieskywalker commented
> Summary should be the same as when read only flag is not enabled ![image](https://user-images.githubusercontent.com/39706811/185605667-0658336e-3bc6-41c4-b954-c8d213c12f76.png)

Gotcha
![image](https://user-images.githubusercontent.com/6871923/185903574-a7796389-10ce-43af-94a1-d69e19cdef5a.png)

2022-08-22 12:24 UTC, piekczyk commented
Copy of following banner (when 0 debt in vault) needs to be updated to include CM as well
![image](https://user-images.githubusercontent.com/39706811/185920357-6bcdb83f-2e75-4e1c-97ef-8d670c9421bd.png)

2022-08-22 12:34 UTC, piekczyk commented
If I reduce my debt to zero when CM is enabled I'm not able to remove it. 
![image](https://user-images.githubusercontent.com/39706811/185922063-a1e1f813-e7e5-4f5a-9467-3ede6629ce34.png)

2022-08-22 12:38 UTC, piekczyk requested changes

2022-08-22 12:38 UTC, piekczyk commented on components/vault/OptimizationControl.tsx
> +  // constantMultipleReadOnlyEnabled,
remove if not necessary

2022-08-22 12:38 UTC, piekczyk commented on components/vault/OptimizationControl.tsx
> +  // constantMultipleReadOnlyEnabled: boolean
remove if not necessary

2022-08-22 12:38 UTC, piekczyk commented on features/automation/optimization/controls/OptimizationFormControl.tsx
> +  // const constantMultipleEnabled = useFeatureToggle('ConstantMultiple')
remove if not necessary

2022-08-22 13:36 UTC, johnnieskywalker commented on components/vault/OptimizationControl.tsx
> +  // constantMultipleReadOnlyEnabled,
it was there on purpose ;)

2022-08-22 13:38 UTC, johnnieskywalker commented on features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
> +      ...((constantMultipleEnabled || constantMultipleReadOnlyEnabled) && {
gotcha

2022-08-22 13:41 UTC, johnnieskywalker commented on features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
> +        title={t('auto-buy.closed-vault-existing-trigger-header')}
got it 
![image](https://user-images.githubusercontent.com/6871923/185935392-134ce529-5608-421d-b6de-905ac2c9ced7.png)

2022-08-22 14:38 UTC, johnnieskywalker commented on features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
> +                  constantMultipleTriggerData={constantMultipleTriggerData}
result of this change

![image](https://user-images.githubusercontent.com/6871923/185948267-a7435f24-bc5c-4a76-82fc-12520e1e8106.png)

2022-08-23 06:34 UTC, piekczyk commented on public/locales/en/common.json
> +    "zero-debt-description": "Oasis.app Optimization allows you to set up a dynamic Auto-Buy and Constant Multiple Strategies on your vault based on the collateralization ratio. This will increase yo
`Oasis.app Optimization allows you to set up a dynamic Auto-Buy and Constant Multiple Strategies on your vault based on the collateralization ratio. This will increase or decrease your exposure to the collateral asset as the price changed. Learn more about how it works`

2022-08-23 08:09 UTC, piekczyk approved these changes

2022-08-23 08:19 UTC, merged