Automate the weekly referral data creation step - Borrow database refinement and testing
OasisDEX/oasis-borrow pull request #1402
Opened 2022-08-25 11:58 UTC by halaprix

# [Automate the weekly referral data creation step - Borrow database refinement and testing](https://app.shortcut.com/oazo-apps/story/5820/automate-the-weekly-referral-data-creation-step-borrow-database-refinement-and-testing)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
modification of existing tables
```
ALTER TABLE public.merkle_tree
ADD COLUMN start_block decimal(78, 0);
ALTER TABLE public.merkle_tree
ADD COLUMN end_block decimal(78, 0);
ALTER TABLE public.user
    RENAME COLUMN "createdAt" TO timestamp;
ALTER TABLE public.user DROP COLUMN total_amount;
ALTER TABLE public.merkle_tree
ADD COLUMN timestamp TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.weekly_claim
ADD COLUMN timestamp TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.merkle_tree
ADD COLUMN snapshot text;
```
 - change in referral user creation - no need to provide the timestamp, it's added by default
 - the `total_amount` column has been depreciated
 - 
## How to test 🧪
test if it doesn't break anything

2022-08-25 15:11 UTC, johnnieskywalker requested changes
Just a minor comment

2022-08-25 15:11 UTC, johnnieskywalker commented on server/database/migrations/009-referral-changes.sql
> +ADD COLUMN end_block decimal(78, 0);
[minor]
```sql
ALTER TABLE public.merkle_tree
ADD COLUMN start_block decimal(78, 0);
ADD COLUMN end_block decimal(78, 0);
```
would have the same result

2022-08-26 06:46 UTC, halaprix commented on server/database/migrations/009-referral-changes.sql
> +ADD COLUMN end_block decimal(78, 0);
makes sense :)

2022-08-26 09:01 UTC, johnnieskywalker approved these changes

2022-08-26 09:54 UTC, merged