new default states for ab and as
OasisDEX/oasis-borrow pull request #1403
Opened 2022-08-25 12:46 UTC by johnnieskywalker

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-08-26 09:02 UTC, piekczyk commented
I found regression following regression:

1) if trigger exists and you visit protection tab, after pills are visible immediately (isEditing is true)
![image](https://user-images.githubusercontent.com/39706811/186868015-21c05559-4768-472c-863c-50ac2eb7e604.png)

2) if you try to remove existing trigger stop loss coll ratio in summary is broken and additionally if you click on `Return to adjusting Stop-Loss` app crash
![image](https://user-images.githubusercontent.com/39706811/186868251-7ffd0017-eebe-4b2e-8dbf-2ceca68c0aac.png)

after clicking on `Return to adjusting Stop-Loss`:
![image](https://user-images.githubusercontent.com/39706811/186868361-fe822e01-148f-4dc5-97da-fb768b7733cd.png)

2022-08-26 09:06 UTC, piekczyk commented
When clicking on `Reset` dots switches their places. It may be potentially fixed if you merge dev.
![image](https://user-images.githubusercontent.com/39706811/186869234-67d352ee-7b24-4a81-9d74-ca5bfdd8d523.png)

2022-08-26 09:07 UTC, piekczyk commented
When clicking on reset after trigger removal nothing happens

![image](https://user-images.githubusercontent.com/39706811/186869577-f4c88816-3406-4b9a-97ad-49022ebe0694.png)

2022-08-26 09:12 UTC, piekczyk commented
when stop loss is set up close to maxium a default state after refresh push it out of range (after pills visible without editing)
![image](https://user-images.githubusercontent.com/39706811/186870463-a53bc331-84df-4ee1-8fef-113622c61725.png)

2022-08-26 09:14 UTC, piekczyk commented
**EDGE CASE** when stop loss is set up close to max value and you try to enable auto buy, default value is set up out of auto buy range (range 352 - 500, default set at 350)
![image](https://user-images.githubusercontent.com/39706811/186870807-884e8fcb-1445-493a-9ee7-0ec36be9d512.png)

2022-08-29 10:30 UTC, johnnieskywalker commented on features/automation/protection/controls/sidebar/SidebarAdjustStopLossEditingStage.tsx
> +                  stopLoss: stopLossLevel.isZero()
Behaviour of reset after this commit 
![image](https://user-images.githubusercontent.com/6871923/187181733-eda9acbf-c49e-40cd-9299-42be2a94a8f3.png)

2022-08-29 16:02 UTC, johnnieskywalker commented on features/automation/protection/common/stopLossTriggerData.ts
> +      stopLossLevel.gte(100) ? stopLossLevel.toString() : stopLossLevel.times(100).toString(),
probably not the best way to fix. Fixes when returning to adjust, but still value passed to UI remains wrong

2022-08-30 11:51 UTC, johnnieskywalker commented on features/automation/protection/useStopLossStateInitializator.ts
> -    uiChanges.publish(ADD_FORM_CHANGE, {
that was causing err when returning to adjust

2022-08-30 12:09 UTC, johnnieskywalker commented
> When clicking on `Reset` dots switches their places. It may be potentially fixed if you merge dev. ![image](https://user-images.githubusercontent.com/39706811/186869234-67d352ee-7b24-4a81-9d74-ca5bfdd8d523.png)

it fixed the issue 
![image](https://user-images.githubusercontent.com/6871923/187432936-8c2236b5-23d2-4e52-848d-d3f3ec641a3b.png)

2022-08-30 12:15 UTC, johnnieskywalker commented on components/vault/VaultChangesInformation.tsx
> +      const textGas = `$${formatAmount(gasEstimation?.usdValue, 'USD')}`
Fix works, sometimes usdValue was undefined, which was not checked and it caused an error
![image](https://user-images.githubusercontent.com/6871923/187434072-767ab1f2-9377-4558-86c9-cb5a8eadadc3.png)

2022-08-30 13:53 UTC, johnnieskywalker commented
> **EDGE CASE:** when stop loss is set up close to maxium a default state after refresh push it out of range (after pills visible without editing) ![image](https://user-images.githubusercontent.com/39706811/186870463-a53bc331-84df-4ee1-8fef-113622c61725.png)

issue seems to be gone but plz test
![Uploading image.png…]()

2022-08-30 14:37 UTC, johnnieskywalker commented
> **EDGE CASE** when stop loss is set up close to max value and you try to enable auto buy, default value is set up out of auto buy range (range 352 - 500, default set at 350). The same applies to auto sell form. ![image](https://user-images.githubusercontent.com/39706811/186870807-884e8fcb-1445-493a-9ee7-0ec36be9d512.png)
> 
> ![image](https://user-images.githubusercontent.com/39706811/186871027-178bc9a0-236d-44be-aedc-f3c5e62e1795.png)

Probably in such case none of values fo ab/as make sense
![image](https://user-images.githubusercontent.com/6871923/187465830-90c0ecb5-2af0-4f0c-ae3d-1f1e3a490a83.png)

This is handled in CM and will create another story to handle it in ab/as

![image](https://user-images.githubusercontent.com/6871923/187465946-adfed7e9-3a95-44ce-a63b-2c5e80627e60.png)

2022-08-31 14:18 UTC, halaprix requested changes
![image](https://user-images.githubusercontent.com/6533433/187701089-f80e5b52-48d6-4821-9776-4af544d2296e.png)
stop loss button disabled by default and after resetting

2022-09-01 07:34 UTC, halaprix approved these changes
The button works as intended. It goes back to the default state - which is disabled.

2022-09-01 07:38 UTC, merged