sidebar form add atp trigger wip
OasisDEX/oasis-borrow pull request #1488
Opened 2022-09-26 12:49 UTC by johnnieskywalker

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-09-29 14:07 UTC, piotrkonowrocki requested changes
Finished checking out code, proceed to manual testing.

2022-09-29 14:07 UTC, piotrkonowrocki commented on features/automation/optimization/autoTakeProfit/state/autoTakeProfitFormChange.ts
> +      return { ...state, collateralActive: action.toCollateral }
Question, not request change.

I see that Stop-Loss has it done in similar way. Is that something that needs to be passed to smart contract in that way? Variable is named `close-type`, but doesn't accepts a type but boolean? At least I think it's boolean.

2022-09-29 14:07 UTC, piotrkonowrocki commented on features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitFormControl.tsx
> +  const closePickerConfig = {
Okay, now after I scrolled down I see that you actually created `getAutoTakeProfitStatus` method, but did not used it here 😀

2022-09-29 14:07 UTC, piotrkonowrocki commented on features/automation/optimization/common/controls/OptimizationFormControl.tsx
> +      {autoTakeProfitEnabled && (
I think it's not needed here. Auto-Take Profit banner is disabled if this feature is off, I also made sure that dropdown won't display Auto-Take Profit without feature flag enabled.

2022-09-29 15:52 UTC, johnnieskywalker commented on features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitFormControl.tsx
> +  const closePickerConfig = {
:facepalm:

2022-09-29 16:05 UTC, johnnieskywalker commented on features/automation/optimization/autoTakeProfit/sidebars/SetupAutoTakeProfit.tsx
> +// import { Vault } from 'blockchain/vaults'
ah I thin it's leftover from before merging with dev with some place holders

2022-09-30 08:07 UTC, piotrkonowrocki commented on features/automation/optimization/autoTakeProfit/state/autoTakeProfitFormChange.ts
> +      return { ...state, collateralActive: action.toCollateral }
Resolved in DM.

2022-09-30 08:15 UTC, piotrkonowrocki approved these changes

2022-09-30 09:10 UTC, merged