Gf/pnl card update
OasisDEX/oasis-borrow pull request #1492
Opened 2022-09-27 15:27 UTC by George-field

# [Update PnL modal](https://app.shortcut.com/oazo-apps/story/5357/update-pnl-popup-card)

## Changes 👷‍♀️
  - Updated the PnL modal as per designs
  - Mobile view
  - added new values to PnL
  
## How to test 🧪
- head to a multiply vault that has transactions
- go to the overview page and click the Net Value section
- The modal will appear, check that the values are correct

Vault 392 on staging has a vault with history.

Please can we double check my calculations as well to make sure they are as expected.

2022-09-28 12:30 UTC, piotrkonowrocki requested changes
Additional note: I know it's not in the scope of that task, but maybe that's good moment to sort a little bit `HTML` semantics mess that we have in some places? I mean to add `as` prop to all `Box` and `Text` components that are missing it, so we can skip a `div` that should be `p` or `span`?

2022-09-28 12:30 UTC, piotrkonowrocki commented on .env
> +BLOCK_NUMBER=15616946
Not sure if we need to commit things like that? I assume we don't.

2022-09-28 12:30 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +            Total Col: {`${lockedCollateral} ${token}`}
Missing translation.

2022-09-28 12:30 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +            Debt: {lockedCollateralUSD}
Missing translation.

2022-09-28 12:30 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +    currentPnLValue: ``,
Why empty template literal instead of just empty string?

2022-09-28 12:30 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +    depositTotalAmounts: {
Wouldn't
```
depositTotalAmounts = formatted.depositTotalAmounts
```
be shorter? Or am I missing something?

2022-09-28 12:30 UTC, piotrkonowrocki commented on features/multiply/manage/utils.ts
> +      console.log(event.collateralAmount?.toString())
`console` left.

2022-09-28 12:30 UTC, piotrkonowrocki commented on features/multiply/manage/utils.ts
> +      console.log(event && event.gasFee?.toString())
`console`

2022-09-28 12:30 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +        <Text
General question: `depositTotalAmounts` is optional, is there a scenario where it is not provided to the component? Maybe it's worth to do couple ifs to skip entire `HTML` block if values are unavailable instead of displaying empty rows?

2022-09-28 12:40 UTC, piotrkonowrocki commented
I have a vault `210` on Goerli which I used for testing. That vault has long history of doing different things on it, so I was trying to check calculations:
![image](https://user-images.githubusercontent.com/16230404/192780525-5d6f8441-b568-45e0-be7e-20a065b0e8fd.png)
Why does Deposits and Withdraws are worth $0 in dollars? And also we are displaying total gas fees in ETH?

2022-09-28 13:50 UTC, George-field commented
> I have a vault `210` on Goerli which I used for testing. That vault has long history of doing different things on it, so I was trying to check calculations: ![image](https://user-images.githubusercontent.com/16230404/192780525-5d6f8441-b568-45e0-be7e-20a065b0e8fd.png) Why does Deposits and Withdraws are worth $0 in dollars? And also we are displaying total gas fees in ETH?

In reference to your point about the gas fee in eth, I mentioned it to sam and he asked that it be kept. And I will check this vault to debug

2022-09-28 15:29 UTC, George-field commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +    currentPnLValue: ``,
This is a mistake, shouldn't have been kept in.

2022-09-28 15:30 UTC, George-field commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +    depositTotalAmounts: {
Yeah, Think I have used the spread operator too much in my life 🤦

2022-09-29 12:32 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetValue.tsx
> +        <Text
Okay, understood. If you find a way to solve that, that's great, if not and empty rows needs to be there so it won't break down - feel free to resolve this comment.

2022-09-29 12:56 UTC, piotrkonowrocki commented
It looks like issue with zeros were resolved:
![image](https://user-images.githubusercontent.com/16230404/193036397-447abe1a-495a-4cab-ad19-200fc1c6014e.png)
Still not sure about rest of the values, can you confirm that this is correct? Deposit 4ETH and withdraw -4ETH? I'm not sure if that is right value in the context of this vault, even at this moment total collateral is 16+ETH. Or maybe I just don't get how is that suppose to work, if so, please a word of explanation 😄
![image](https://user-images.githubusercontent.com/16230404/193036969-c9370938-9339-4b4d-b9fb-4aa060c60999.png)


Also, another tiny UI issue, withdraws are formatted differently than the rest, no zeros after comma.
![image](https://user-images.githubusercontent.com/16230404/193036675-aef0cda8-1ac5-4168-bceb-becd35d70dea.png)

2022-10-05 13:04 UTC, adamskrodzki commented on features/multiply/manage/utils.ts
> +  return pnl.times(netValueUSD).dividedBy(pnl.plus(1))
let say pnl = 0.5 (user made +50% of initial investment) and netValueUSD aquals 1500 expected value is 500, right ?

0.5* 1500 / (0.5+1) == 500.

Seems ok

2022-10-06 10:33 UTC, adamskrodzki approved these changes

2022-10-06 13:42 UTC, piotrkonowrocki submitted a review, later dismissed

2022-10-13 09:49 UTC, merged