Earn: stETH/ETH product card
OasisDEX/oasis-borrow pull request #1496
Opened 2022-09-28 10:35 UTC by marcinciarka

# [Earn stETH/ETH product card](https://app.shortcut.com/oazo-apps/story/4804/configure-earn-steth-eth-product-card)
  
## Changes 👷‍♀️
 - added new product card on `/earn` for stETH/ETH product
  
## How to test 🧪
 - `/earn`
 - look for the new product card (blue instead of pink)

2022-10-03 12:20 UTC, jakubswierczek requested changes

2022-10-03 12:20 UTC, jakubswierczek commented on pages/index.tsx
> +      <DeferedContextProvider context={aaveContext}>
Please create a separate context for `earnPage`

2022-10-03 12:50 UTC, marcinciarka commented on components/productCards/ProductCard.tsx
> +    link: `https://makerburn.com/#/collateral/${strategyName}`,
This link is TBD as per shortcut description

2022-10-03 12:51 UTC, marcinciarka commented on components/productCards/ProductCardsContainer.tsx
> +  ilks: string[]
👌

2022-10-03 18:10 UTC, jakubswierczek approved these changes

2022-10-03 18:32 UTC, merged

2022-10-04 09:24 UTC, sennett commented on components/productCards/ProductCard.tsx
> +    ilk: strategyName,
With this, the ilks are on Maker, but this STETH/ETH strategy we are working on is not specific to Maker, so it will create a dead link I think.

2022-10-04 09:40 UTC, marcinciarka commented on components/productCards/ProductCard.tsx
> +    ilk: strategyName,
Link is TBD.