Speeds up AAVE stETH/ETH yields requests
OasisDEX/oasis-borrow pull request #1517
Opened 2022-10-06 13:53 UTC by marcinciarka

# Speeds up stETH yields requests

AAVE stETH/ETH queries varied in response time (sometimes even timed out) so after @sennett made some tweaks on the cache side we needed some changes on the front. Now the query (if needed) takes a list of parameters, which cuts down on response time significantly. In addition to that they are memoized properly and downloaded only once (once on `/earn` page and once on the open position page).
  
## Changes 👷‍♀️
- moved graphql query initialization to appcontext
- moved yields query to appcontext
- added opt-in option to query selected fields on stEthYields
- added proper memoization for stEthYields query
  
## How to test 🧪
 - go to `/earn` and see how fast the yields are displayed
 - switch to any other page
 - go to `/earn` page again - the yields should be there with no additional request needed
 - same as above but on the open position page

2022-10-07 14:45 UTC, sennett requested changes

2022-10-07 14:45 UTC, sennett commented on components/productCards/ProductCardEarnAave.tsx
> +            yields: await aaveSthEthYieldsQuery(maximumMultiple, ['7Days', '90Days']),
Nice.

2022-10-07 14:45 UTC, sennett commented on features/earn/aave/open/components/AaveOpenHeader.tsx
> +        simulationContext.yields.annualisedYield7daysOffset!,
This seems strange.  The multiples are already taken into consideration in the yields.  A yield is for a given multiple.  I think we should have two different queries for each yield here?

2022-10-11 08:21 UTC, marcinciarka commented on features/earn/aave/open/components/AaveOpenHeader.tsx
> +        simulationContext.yields.annualisedYield7daysOffset!,
That is correct, I need to fix that.

2022-10-11 08:24 UTC, marcinciarka commented on features/earn/aave/open/components/AaveOpenHeader.tsx
> +        simulationContext.yields.annualisedYield7daysOffset!,
I'll do that in another PR.

2022-10-11 08:27 UTC, jakubswierczek approved these changes

2022-10-11 08:28 UTC, merged