Ades/aave/adjust risk manage
OasisDEX/oasis-borrow pull request #1534
Opened 2022-10-11 15:33 UTC by sennett

# [Title](https://shortcutLink)
  
## Changes 👷‍♀️
- consolidates user input on state across open and manage flows
- read and write from UI to XState
- save not working yet.
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-10-11 15:43 UTC, marcinciarka requested changes

2022-10-11 15:43 UTC, marcinciarka commented on features/earn/aave/open/state/openAaveStateMachine.ts
> +        tokenBalance.gt(userInput.amount),
We could make a function to check multiple params:
```
function hasRequiredParams(...params) {
  if (params && params.length === 0) return false
  return !params.length || !params.includes(undefined)
}
```

2022-10-12 07:49 UTC, jakubswierczek approved these changes

2022-10-12 07:49 UTC, jakubswierczek commented on features/earn/aave/manage/state/manageAaveStateMachine.ts
> +        assignProtocolData: assign((context, event) => {
If you change one action to `return` conversion, please do it in every action.

2022-10-12 15:48 UTC, marcinciarka commented on features/earn/aave/common/components/SidebarAdjustRiskView.tsx
>      AT_RISK = 'AT_RISK',
This should end up in some constants file (unless it's temporary).

2022-10-12 15:48 UTC, marcinciarka commented on features/earn/aave/common/components/SidebarAdjustRiskView.tsx
>            minBoundry={minRisk.loanToValue || zero}
IDK if this is important, but boundry !== boundary (typo in SliderValuePicker component), if not plz disregard.

2022-10-12 15:48 UTC, marcinciarka commented on features/earn/aave/manage/state/manageAaveStateMachine.ts
> +          allDefined(proxyAddress, transactionParameters),
❤️

2022-10-14 12:08 UTC, sennett commented on features/earn/aave/common/components/SidebarAdjustRiskView.tsx
>      AT_RISK = 'AT_RISK',
Right now it's only relevant in this context, but it should be part of IPosition in the maths lib.

2022-10-17 07:12 UTC, jakubswierczek requested changes

2022-10-17 07:12 UTC, jakubswierczek commented on features/earn/aave/open/services/getParametersStateMachineServices.ts
> +          //   .send(callOperationExecutor, {
remove comments

2022-10-17 07:12 UTC, jakubswierczek commented on features/stateMachines/transaction/transactionStateMachine.ts
> +        console.log('startTransactionService', context.transactionParameters)
remove log

2022-10-17 07:12 UTC, jakubswierczek commented on helpers/swap.ts
> +    if (debug) {
please remove logs

2022-10-17 07:12 UTC, jakubswierczek commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +          const collateralToken = 'STETH'
maybe add `collateralToken` to the context

2022-10-17 07:12 UTC, jakubswierczek commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +            // gasQty = 700000
please remove that try/catch or add logging to sentry

2022-10-17 07:12 UTC, jakubswierczek commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +          const result = await aaveProtocolData(context.strategy!, context.proxyAddress!)
`const result` is unnecessary

2022-10-17 07:12 UTC, jakubswierczek commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +        getStrategyInfo: () => {
all services have defined returned value. Please add it here

2022-10-17 10:27 UTC, sennett commented on features/aave/index.ts
> +export function logPosition(position: IPosition, name: string) {
I'm using this to read the amounts in the BigNumbers.  It's a temp function I will delete.

2022-10-17 14:15 UTC, sennett commented on features/aave/index.ts
> +  const addresses = {
Done.

2022-10-17 14:18 UTC, sennett commented on helpers/swap.ts
> +    if (debug) {
This one is used for the library - it's easier to see issues with this without doing an `npm publish` cycle.  Worth keeping IMO.

2022-10-17 14:24 UTC, sennett commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +          const collateralToken = 'STETH'
Yes - we need to revisit this. I'm not sure if it would mean much to do it here though - we are referencing stETH/ETH elsewhere also.

2022-10-17 15:05 UTC, merged