Gf/stoploss confirmation screen
OasisDEX/oasis-borrow pull request #1538
Opened 2022-10-13 07:16 UTC by George-field

# [Confirmation Screens for auto buy, sell and stop loss](https://app.shortcut.com/oazo-apps/story/5353/stop-loss-add-order-summary-confirmation-screen)
  
## Changes 👷‍♀️
- Added Confirmation screens to auto buy, sell and stop loss flows
- Added step numbers
- Added edit order button
  
## How to test 🧪
- Go through the auto buy, sell and stop loss set up flows. You will see a new confirmation screen and added step numbers to the flow. 
- On the confirmation screen an edit order button should now also be present, when clicked it should take you back to the previous step.

2022-10-24 08:42 UTC, piekczyk requested changes

2022-10-24 08:42 UTC, piekczyk commented on features/automation/optimization/autoBuy/sidebars/SidebarAutoBuyEditingStage.tsx
> +      {isAwaitingConfirmation && (
I think that much better idea would be to have it extracted as separate component instead of doing conditions here. This comment applies for all auto features.

So in file `SidebarSetupAutoBuy`

```<>
              {isAddForm && (
                <SidebarAutoBuyEditingStage
                  vault={vault}
                  ilkData={ilkData}
                  autoBuyState={autoBuyState}
                  isEditing={isEditing}
                  autoBuyTriggerData={autoBuyTriggerData}
                  errors={errors}
                  warnings={warnings}
                  debtDelta={debtDelta}
                  collateralDelta={collateralDelta}
                  sliderMin={min}
                  sliderMax={max}
                  stopLossTriggerData={stopLossTriggerData}
                  isAwaitingConfirmation={isAwaitingConfirmation}
                />
              )}
              {isAwaisAwaitingConfirmation && (
                  <SidebarAutoBuyAwaitingConfirmation blabla... />
                )
              }
              {isRemoveForm && (
                <SidebarAutoBuyRemovalEditingStage
                  vault={vault}
                  ilkData={ilkData}
                  errors={cancelAutoBuyErrors}
                  warnings={cancelAutoBuyWarnings}
                  autoBuyState={autoBuyState}
                />
              )}
            </>```

2022-10-24 08:42 UTC, piekczyk commented on features/automation/optimization/autoBuy/sidebars/SidebarSetupAutoBuy.tsx
> +        label: `${
I think that this logic should be included within method that returns `primaryButtonLabel` and should be reusable in all auto features

2022-10-24 08:42 UTC, piekczyk commented on features/automation/protection/stopLoss/controls/StopLossFormControl.tsx
> +  console.log(isAwaitingUserConfirmation, 'confirmation state')
to be removed

2022-10-24 08:42 UTC, piekczyk commented on features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
> +            You are setting an Auto-Take Profit order to trigger at an ETH price of ${ethMarketPrice.toString()}. Your vault will be closed and your expected profit of $1.8m paid will be paid out in
translation

2022-10-24 08:47 UTC, piekczyk commented
Confirmation screen is missing when you decline transaction and try to send it again (to be verified in other auto features as well)

![image](https://user-images.githubusercontent.com/39706811/197486166-42b2ed91-9627-4003-8023-1e790cc44368.png)

2022-10-27 07:48 UTC, piekczyk requested changes

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +          label: isAwaitingUserConfirmation ? t('protection.edit-order') : textButtonLabel,
please move this logic to inside `getAutomationTextButtonLabel` method, so here we will use just `label: textButtonLabel`

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +          console.log(stage, 'stage')
to be removed

2022-10-27 07:48 UTC, piekczyk commented on features/automation/optimization/autoBuy/sidebars/SidebarAutoBuyEditingStage.tsx
> +      {isAwaitingConfirmation && (
this comment is still valid

2022-10-27 07:48 UTC, piekczyk commented on features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
> +      {!isAwaitingConfirmation && (
like I mentioned in previous comment - instead of doing this condition in 3 or 4 places in these files `...EditingStage.tsx` we could have dedicated, generic component for awaiting confirmation stage used across whole automation. Then it will be easy to distinguish what to render on the sidebar level (in files like `SidebarAutoTakeProfit.tsx`, `SidebarSetupAutoBuy` etc.)

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarAdjustStopLossEditingStage.tsx
> +      <>
is this extra fragment needed here?

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +  isAwaitingUserConfirmation: boolean
minor change, it could be just `isAwaitingConfirmation` - no need for creating different const names for the same value

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarStopLossAwaitingConfirmation.tsx
> +export function SidebarStopLossAwaitingConfirmation({
looks like perfect candidate for generic automation confirmation stage component

```
export function SidebarAwaitingConfirmationStage({
  feature,
  children,
}: SidebarAwaitingConfirmationStageProps) {
  const { t } = useTranslation()

  return (
    <>
      <Text as="p" variant="paragraph3" sx={{ color: 'neutral80' }}>
        {t('automation.confirmation-text', { feature })}
      </Text>
      {children}
    </>
  )
}
```

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +                {isAwaitingUserConfirmation && ['stopLossEditing', 'txFailure'].includes(stage) && (
I'm a little bit confused why `['stopLossEditing', 'txFailure'].includes(stage` this part is needed here. Once user confirm `isAwaitingUserConfirmation` should be set to false and we can forget about it.

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +                  ['stopLossEditing', 'txFailure'].includes(stage) && (
I will need a bit of explanation why it is needed here 
`['stopLossEditing', 'txFailure'].includes(stage)`

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/stopLoss/controls/StopLossFormControl.tsx
> +  const isAwaitingUserConfirmation = stopLossState.isAwaitingConfirmation
`const isAwaitingConfirmation = stopLossState.isAwaitingConfirmation`

no need to create different names for the same value

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/autoSell/sidebars/SidebarSetupAutoSell.tsx
> +                  isAwaitingConfirmation={false}
this one doesn't make sense since you checked if its true before you render this component

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAwaitingConfirmation.tsx
> +export function SidebarAutoSellAwaitingConfirmation({
this should be generic component which accepts child and feature name

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAwaitingConfirmation.tsx
> +export function SidebarAutoSellAwaitingConfirmation({
```
export function SidebarAwaitingConfirmationStage({
  feature,
  children,
}: SidebarAwaitingConfirmationStageProps) {
  const { t } = useTranslation()

  return (
    <>
      <Text as="p" variant="paragraph3" sx={{ color: 'neutral80' }}>
        {t('automation.confirmation-text', { feature })}
      </Text>
      {children}
    </>
  )
}
```

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
> +        {t('auto-sell.confirmation')}
it does not belong here

2022-10-27 07:48 UTC, piekczyk commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
> +      <>
why `isEditing` was removed? Warnings and errors should be displayed only when user starts to edit values in form.

2022-10-27 07:48 UTC, piekczyk commented on features/automation/optimization/autoTakeProfit/state/autoTakeProfitTriggerData.ts
> +export function pickTriggerWithLowestExecutionPrice(
this method is used only in scope of this file, no need to export it

2022-10-27 07:48 UTC, piekczyk commented on features/automation/common/sidebars/getAutomationPrimaryButtonLabel.ts
> +      return `${t(translationKey, { feature: t(sidebarAutomationFeatureCopyMap[feature]) })}`
template string is not needed here

2022-10-27 08:29 UTC, piekczyk commented
after successfully udpated ATP trigger I clicked on `Confirm 3/3` and I ended up here:

![image](https://user-images.githubusercontent.com/39706811/198232717-fd63cc2a-83ad-4da5-90bb-afcdf935825c.png)

2022-10-27 11:01 UTC, George-field commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +          label: isAwaitingUserConfirmation ? t('protection.edit-order') : textButtonLabel,
done

2022-10-27 11:04 UTC, George-field commented on public/locales/en/common.json
> +    "confirmation-text": "Confirm your Auto-Buy setup.",
done

2022-10-27 11:04 UTC, George-field commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +          console.log(stage, 'stage')
done

2022-10-27 14:01 UTC, George-field commented on features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
> +      {!isAwaitingConfirmation && (
done

2022-10-27 17:58 UTC, George-field commented on features/automation/protection/stopLoss/sidebars/SidebarAdjustStopLossEditingStage.tsx
> +      <>
Done

2022-10-27 18:00 UTC, George-field commented on features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
> +  isAwaitingUserConfirmation: boolean
Done

2022-10-27 18:00 UTC, George-field commented on features/automation/protection/stopLoss/sidebars/SidebarStopLossAwaitingConfirmation.tsx
> +export function SidebarStopLossAwaitingConfirmation({
Done

2022-10-27 18:02 UTC, George-field commented on features/automation/protection/stopLoss/controls/StopLossFormControl.tsx
> +  const isAwaitingUserConfirmation = stopLossState.isAwaitingConfirmation
done

2022-10-27 18:02 UTC, George-field commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAwaitingConfirmation.tsx
> +export function SidebarAutoSellAwaitingConfirmation({
done

2022-10-27 18:02 UTC, George-field commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
> +        {t('auto-sell.confirmation')}
done

2022-10-27 18:04 UTC, George-field commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
> +      <>
done

2022-10-27 18:06 UTC, George-field commented on features/automation/common/sidebars/getAutomationPrimaryButtonLabel.ts
> +      return `${t(translationKey, { feature: t(sidebarAutomationFeatureCopyMap[feature]) })}`
done

2022-10-31 12:04 UTC, piekczyk commented
Issue with copies.

![image](https://user-images.githubusercontent.com/39706811/199003679-18de50e1-550f-4e2f-98fc-a75cae1c3ea0.png)

2022-10-31 12:08 UTC, piekczyk commented
For all triggers beside SL - there is still second step with duplicated general information section.

![image](https://user-images.githubusercontent.com/39706811/199004093-dc6de36e-8af6-4221-9e64-d24535a7cd93.png)

2022-10-31 12:31 UTC, piekczyk commented
click on button in txSuccess stage still redirects to confirmation step
![image](https://user-images.githubusercontent.com/39706811/199008268-2c952e09-5785-476c-b555-3fe371622eff.png)

2022-10-31 12:45 UTC, piekczyk commented
there is inconsistency when you cancel transaction, for example if you do that in take profit form you will be moved back to confirmation screen without `Retry` button copy but in the other hand in stop loss form you will be moved to first step with `Retry` button

2022-10-31 12:51 UTC, piekczyk requested changes

2022-10-31 12:51 UTC, piekczyk commented on public/locales/en/common.json
> +    "auto-take-profit-confirmation-text": "You are setting an Auto-Take Profit order to trigger at an ETH price of ${{price}}. Your vault will be closed and your expected profit of ${{profit}} paid w
please double check if duplicated word 'paid' is expected here `of ${{profit}} paid will be paid out in DAI."`

2022-10-31 12:51 UTC, piekczyk commented on public/locales/en/common.json
> +    "auto-take-profit-confirmation-text": "You are setting an Auto-Take Profit order to trigger at an ETH price of ${{price}}. Your vault will be closed and your expected profit of ${{profit}} paid w
Also this particular key `auto-take-profit-confirmation-text` should be moved to 'auto-take-profit' object. 'automation' key is dedicated for generic translations

2022-10-31 12:51 UTC, piekczyk commented on public/locales/en/common.json
> +    "confirmation-text": "Confirm your Auto-Buy setup.",
If it's done it means that this key here (`auto-buy.confirmation-text`) and in other auto feature translation object is no needed anymore. Please remove it.

2022-10-31 12:51 UTC, piekczyk commented on public/locales/en/common.json
> +    "confirmation": "Confirm your auto-sell setup.",
to be removed

2022-10-31 12:51 UTC, piekczyk commented on public/locales/en/common.json
> +    "confirmation-text": "Confirm your Stop-Loss setup.",
to be removed

2022-10-31 12:51 UTC, piekczyk commented on features/automation/protection/stopLoss/state/useStopLossStateInitializator.ts
> +  useEffect(() => {
Please move it to inside of `useEffect` below (line 41). There is no reason why we should keep it in separate `useEffect`.

2022-10-31 12:51 UTC, piekczyk commented on features/automation/common/sidebars/getAutomationPrimaryButtonLabel.ts
> +function generateAutomationPrimaryButtonLabelTtext({
typo, `generateAutomationPrimaryButtonLabelText`

2022-10-31 12:51 UTC, piekczyk commented on features/automation/common/sidebars/getAutomationPrimaryButtonLabel.ts
> +      throw new UnreachableCaseError(stage as never)
there was typescript issue here because stage `isConfirming` was not handled within switch-case. I missed that in previous review but what you could do here is instead of passing `isAwaitingConfirmation` as props you could just add additional case `isConfirming` and return there  `t('protection.confirm')`

Example:
``` 
    case 'isConfirming':
      return t('protection.confirm')
```

In that was you wont need to cast stage as never

2022-10-31 12:51 UTC, piekczyk commented on features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
> +      <>
there is not need for this fragment

2022-10-31 12:51 UTC, piekczyk commented on features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
> +        {t('auto-sell.confirmation')}
its still here

2022-10-31 12:51 UTC, piekczyk commented on features/automation/optimization/autoTakeProfit/state/autoTakeProfitTriggerData.ts
> +export function pickTriggerWithLowestExecutionPrice(
please update it as well

2022-11-07 08:35 UTC, piekczyk commented
In success stage instead of `Edit Order` we should display `Remove trigger`. At least thats how it works on production currently. Also according to the designs, instead of `Confirm (x/x)` we should display `Finished (x/x)`

![image](https://user-images.githubusercontent.com/39706811/200262607-a49e865d-4c82-4644-8f73-ff752afae612.png)

2022-11-07 08:38 UTC, piekczyk commented
There is still Issue with wrong step after clicking button in success stage. Click on button should take user to first step (form). Please fix it and test it in other auto features including scenarios such as adding, updating and removing trigger.


![image](https://user-images.githubusercontent.com/39706811/200263545-4a165273-8b98-41fe-8f15-e24ad1d81304.png)

2022-11-07 08:46 UTC, piekczyk commented
If we are going to use multistep button when removing trigger we should ensure that step indicator is correct (after I clicked step changed from 1/3 to 3/3). Please fix it and test it also in scope of other auto features.

![image](https://user-images.githubusercontent.com/39706811/200265146-41ca9678-f6ad-481b-8d39-ab4e7fd92bbf.png)

2022-11-10 09:28 UTC, piekczyk approved these changes

2022-11-10 13:01 UTC, piekczyk approved these changes

2022-11-10 13:05 UTC, merged