Kk/discover-api
OasisDEX/oasis-borrow pull request #1590
Opened 2022-10-19 07:52 UTC by halaprix

# [Create (in oasis-borrow) next api function ](https://app.shortcut.com/oazo-apps/story/6229/backend-create-in-oasis-borrow-next-api-function-querying-oasisdiscover-subgraph-for-highest-multiply-p-l)
#[[Backend] Borrow DB tables and views](https://app.shortcut.com/oazo-apps/story/6358/backend-borrow-db-tables-and-views)
<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-10-20 13:09 UTC, adamskrodzki requested changes

2022-10-20 13:09 UTC, adamskrodzki commented on handlers/discover/discover.tsx
> +        data = (await prisma.largestDebt.findMany({
no orderBy

2022-10-20 13:09 UTC, adamskrodzki commented on server/database/migrations/010-discover.sql
> +    "net_value" DECIMAL(65, 30) NOT NULL,
isn't net_value possible to derive from collateral_value, vault_debt ?

btw collateral_value is it amount or amount*price if latter then maybe former makes more sense since i see price here as well

2022-10-20 13:37 UTC, halaprix commented on handlers/discover/discover.tsx
> +          take: AMOUNT_OF_ROWS,
it's in the view `ORDER BY "discover"."vault_debt" DESC;`

2022-10-24 11:24 UTC, adamskrodzki approved these changes

2022-10-24 11:43 UTC, adamskrodzki approved these changes

2022-10-24 13:13 UTC, merged