🧭 Discover mixpanel analytics
OasisDEX/oasis-borrow pull request #1592
Opened 2022-10-19 13:51 UTC by piotrkonowrocki

# [🧭 Discover mixpanel analytics](https://app.shortcut.com/oazo-apps/story/6185/discover-oasis-analytics)

All events are based on this sheet https://docs.google.com/spreadsheets/d/1Jie1SX_5i4-jDZLMKnCUkq4lhchkPKonIOVPNNJtsA8/edit#gid=308180383 with an exception of `ScrollTable` event which will be implemented differently, as a separated story.
  
## Changes 👷‍♀️

- Added dedicated events for tracking user behavior on Discover Oasis pages.
  
## How to test 🧪

- Try to trigger all trackable actions on Discover page UI, then look for request to `/api/t` and compare sent parameters with those required by Google sheet,
- please note that all parameters in `eventBody` were intentioanlly changed to camelCase and all event names to kebabCase.

2022-10-20 16:15 UTC, marcinciarka requested changes

2022-10-20 16:15 UTC, marcinciarka commented on analytics/analytics.ts
> +      mixpanelInternalAPI('btn-click', {
Use `EventTypes` enum from :70

2022-10-20 16:20 UTC, johnnieskywalker requested changes

2022-10-20 16:20 UTC, johnnieskywalker commented on features/discover/views/DiscoverView.tsx
> +      <DiscoverNavigation kind={kind} userContext={userContext} />
![image](https://user-images.githubusercontent.com/6871923/197003318-e1ba9af0-7e3c-4596-bd60-b76d4eb15b8f.png)
![image](https://user-images.githubusercontent.com/6871923/197003379-5db0481c-21fa-44ea-8f38-c4871b889850.png)
![image](https://user-images.githubusercontent.com/6871923/197003413-345a90e6-5b46-4b35-9f74-023bbaa8729c.png)

![image](https://user-images.githubusercontent.com/6871923/197003471-76435be3-6c80-4ea2-892e-26cdcc197a0a.png)

![image](https://user-images.githubusercontent.com/6871923/197003589-eea7a808-f4d5-4126-a513-da480fa829e9.png)

Seems all params are ok but Page is missing

2022-10-20 16:21 UTC, marcinciarka requested changes

2022-10-20 16:21 UTC, marcinciarka commented on analytics/analytics.ts
> +        id: 'Discover',
Theres `Page` name missing in all of these events (column B in the mixpanel event sheets).

2022-10-21 08:56 UTC, piotrkonowrocki commented on analytics/analytics.ts
> +      mixpanelInternalAPI('btn-click', {
Fixed.

2022-10-21 08:57 UTC, piotrkonowrocki commented on features/discover/views/DiscoverView.tsx
> +      <DiscoverNavigation kind={kind} userContext={userContext} />
For whatever wrong reason I somehow skipped first three params, `product`, `page` and `section`. All done now.

2022-10-21 08:58 UTC, piotrkonowrocki commented on analytics/analytics.ts
> +        id: 'Discover',
See: https://github.com/OasisDEX/oasis-borrow/pull/1592#discussion_r1001545892
Same comment applies.

2022-10-21 08:59 UTC, marcinciarka commented on analytics/analytics.ts
> +      mixpanelInternalAPI('btn-click', {
👌

2022-10-21 09:02 UTC, marcinciarka approved these changes

2022-10-21 09:13 UTC, johnnieskywalker approved these changes

2022-10-21 09:22 UTC, merged