Improve performance when adjusting positon
OasisDEX/oasis-borrow pull request #1608
Opened 2022-10-20 18:49 UTC by sennett

Moves to observable to do gas estimation in a separate async.  Updates the UI with all the values before doing gas estimation.

2022-10-20 18:51 UTC, sennett commented on features/earn/aave/manage/state/manageAaveStateMachine.ts
> +        }),
If anyone has any ideas about this I'm all ears 👂👂👂

2022-10-21 07:13 UTC, jakubswierczek requested changes

2022-10-21 07:13 UTC, jakubswierczek commented on features/earn/aave/manage/state/manageAaveStateMachine.ts
> +            data: {
You can't specify `data` in observable. 
Obervables have no data field. They can only send events.

2022-10-21 07:13 UTC, jakubswierczek commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +        ): Observable<{
what is the point of that change? 
For me, it's not a stream of values. It's a one-time job. You don't constantly observe that. It's a misunderstanding of observables. 
You only care about the first result. 
I prefer a machine for that because there are 3 steps. 3 atomic operations, not one.

2022-10-21 10:53 UTC, sennett commented on features/earn/aave/manage/state/manageAaveStateMachine.ts
> +            data: {
Ah great - maybe this is why I ad to account for the two types above.

2022-10-21 11:19 UTC, sennett commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +        ): Observable<{
Previously this service was a promise that returned simulation data (slow-ish) and gas costs (more slow) inside one promise, that took ~5 seconds to resolve.  The gas cost depends on the simulation data.  My fix was to replace this promise with an Observable that returns the same data in stages.  First the simulation as soon as it's ready, and then the gas cost (and simulation again) when the gas cost becomes ready. 

Observables are both long-lived streams (for example in polling situations) and promises that complete more than once.  We could use a machine here, but in my opinion it would require a lot more code, time and come with a fragility cost, with events, state, actions, spawning, and actors, and more files.  So I went with an Observable instead - in general I think we want to use machines to manage the state powering user journeys, and use other things that have less overhead in other situations.

2022-10-21 11:46 UTC, jakubswierczek commented on features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +        ): Observable<{
yes, I understand, but if you spawn a machine at the beginning of the parent machine lifecycle, you can send only an update or something like that. 
In the case of Observables or promises are the same. According to the docs, service and actor can be child machine, promise, or observable. 
It doesn't matter what is that. 
Actually in that case Observables don't have `onDone` event:
```
onDone: {
              actions: ['assignTransactionParameters', 'setAdjustOperationType'],
            },
```
Another weak point: you are calling that service only on entry to the `editing` state (and `review`), so if you change the risk, there is no action.
That's why I prefer a machine or callback service if you prefer that https://xstate.js.org/docs/guides/communication.html#invoking-callbacks
But in callbacks, you have to care about subscription and subscription. 

Machines also can send an event after one action. For example, you can return transaction parameters and still execute the gas estimation. 
In your previous implementation example, you have to wait for the gas estimation to see order information. Now, It's faster. But you can easily stop execution if parameters changed. In a machine, you can react to an event and start calculating one more time.

2022-10-21 14:08 UTC, jakubswierczek approved these changes

2022-10-21 14:08 UTC, merged