AAVE Positions, Generic way to call the library
OasisDEX/oasis-borrow pull request #1651
Opened 2022-10-29 13:45 UTC by jakubswierczek

# [Generic way for calling the library](https://app.shortcut.com/oazo-apps/story/6417/statemachines-make-generic-state-machine-to-get-parameters-from-the-library)
  
## Changes 👷‍♀️
- Open a generic state machine to call the library, estimate gas, and get the price for that gas. 
- Removed machines: `openAaveParameters`, `closeAaveParameters`
- Changed operations names for the adjust operations. 
  
## How to test 🧪
 - Try to open and close the AAVE position on a hardhat. 
 - Try also increase and decrease risk.

2022-11-16 09:48 UTC, marcinciarka commented on pages/aave/[address].tsx
> +              <WithStrategy address={address} />
Good thing we got rid of this monster ✌️

2022-11-16 13:07 UTC, sennett requested changes

2022-11-16 14:34 UTC, jakubswierczek commented on features/aave/open/state/openAaveStateMachine.ts
> +        },
yes, I tried it and have some thoughts: 
* Having atomic update is easier to understand (you can track which properties are changing)
* The machine should have an event to update context from a higher lever. We can try to implement that.
* We should have the possibility to change the state of the machine. 
Auto team creates something like that:
```
const [dept1, setDept1] = useState();

const machine = createMachine(dept1);

useEffect(() => { send({ type: 'CHANGED', dept1 }) }, [dept1]))

``` 
In that way, we don't have a lot of simple services but we have two stores - Xstate & internal react. 
I like Xstate because it's not coupled to any framework. It can be used in another app.

2022-11-16 14:39 UTC, jakubswierczek commented on blockchain/calls/aave/aaveLendingPool.ts
> +  address: string | undefined
good spot, I'll change it.

2022-11-16 14:49 UTC, jakubswierczek commented on features/stateMachines/transactionParameters/transactionParametersStateMachine.ts
> +export function createTransactionParametersStateMachine<T extends BaseTransactionParameters>(
Discussed on Discord

2022-11-16 21:42 UTC, sennett approved these changes

2022-11-16 21:43 UTC, sennett requested changes

2022-11-16 21:43 UTC, sennett commented on blockchain/calls/aave/aaveLendingPool.ts
> +    return [address || zeroAddress()]
It wasn't possible to remove this?

2022-11-17 08:22 UTC, sennett approved these changes

2022-11-17 08:35 UTC, marcinciarka approved these changes

2022-11-17 08:43 UTC, merged