Ades/risk slider
OasisDEX/oasis-borrow pull request #1670
Opened 2022-11-09 14:14 UTC by sennett

# [Configurable slider](https://app.shortcut.com/oazo-apps/story/6423/ui-ltv-slider)
  
## Changes 👷‍♀️
- inject config into risk adjustment slider, and inject component in strategy config
- co-locates strategy configs with the view components.
  
## How to test 🧪
- adjust risk slider on both multiply and earn products - the boundaries should work correctly, and the position should get creates as before.

2022-11-09 14:16 UTC, sennett commented on features/aave/common/components/SidebarAdjustRiskView.tsx
> +            rightLabel={t(viewConfig.rightBoundary.translationKey)}
This is the interesting bit in `AdjustRiskView` - the rest of the component is indented due to the config above.

2022-11-10 10:39 UTC, jakubswierczek submitted a review, later dismissed

2022-11-11 13:13 UTC, sennett commented on features/aave/common/components/SidebarAdjustRiskView.tsx
>  import { aaveStETHDefaultRiskRatio, aaveStETHMinimumRiskRatio } from '../../constants'
I have changed these for the multiply defaults and added to the cofnig.

2022-11-11 13:13 UTC, sennett commented on features/aave/common/components/SidebarAdjustRiskView.tsx
> +      aaveStETHMinimumRiskRatio.loanToValue
I have changed these for the multiply defaults and added to the strategy config.

2022-11-14 10:12 UTC, jakubswierczek requested changes

2022-11-14 10:12 UTC, jakubswierczek commented on features/aave/manage/services/getAaveProtocolData.ts
> +        // debugger
remove logs.

2022-11-14 10:12 UTC, jakubswierczek commented on features/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +              console.log('protocol data received')
remove log

2022-11-14 10:12 UTC, jakubswierczek commented on features/aave/open/services/getOpenAaveStateMachine.ts
> +        first(), // don't override current step when creating proxy in flow
It's not a good approach. If we don't only first we should make a promise from it.

2022-11-14 10:12 UTC, jakubswierczek commented on features/aave/view/sidebars/SidebarViewPositionAaveVault.tsx
> +                  .minus(strategyConfig.riskRatios.minimum.loanToValue)
I don't like a lot of nesting classes. but for now we can keep it.

2022-11-14 10:42 UTC, sennett commented on features/aave/view/sidebars/SidebarViewPositionAaveVault.tsx
> +                  .minus(strategyConfig.riskRatios.minimum.loanToValue)
Yeah it's either this or loads of types everywhere.  I think I prefer this, as long as we keep the StrategyConfig type nice and clear?

2022-11-14 10:44 UTC, sennett commented on features/aave/open/services/getOpenAaveStateMachine.ts
> +        first(), // don't override current step when creating proxy in flow
I'm not sure.  Promises should resolve, but if there is no proxy address we don't want to resolve with undefined because it creates more duplication in the machine when setting the proxy address.

2022-11-14 10:45 UTC, sennett commented on features/aave/manage/services/getAaveProtocolData.ts
> +        // debugger
Thanks - removed.

2022-11-14 10:45 UTC, sennett commented on features/aave/manage/services/getManageAavePositionStateMachineServices.ts
> +              console.log('protocol data received')
Removed.

2022-11-14 14:13 UTC, jakubswierczek commented on features/aave/open/services/getOpenAaveStateMachine.ts
> +        first(), // don't override current step when creating proxy in flow
But it's unclear. We are creating a stream of values aka Observable. If we only care about the first value, it should be resolved to `undefined` and skipped at the machine level.

2022-11-14 14:14 UTC, merged