Gf/move features toggles to db
OasisDEX/oasis-borrow pull request #1671
Opened 2022-11-09 14:14 UTC by George-field

# [Move Feature Flags To Database](https://app.shortcut.com/oazo-apps/story/5331/move-feature-flags-from-local-storage-to-db)

  
## Changes 👷‍♀️
- Added feature flags to schema
- Added a feature flags get endpoint on the api
- update the useFeatureFlag file to accommodate for database feature flags and local-storage

If you look at the code you will notice that in the event that the api request fails when fetching the feature flags, it will fall back to what ever is in local storage. 
  
## How to test 🧪
- update database and run the app with node env in production mode
- set a feature flag in the database, you can use the local storage dev tools to check that is has populated correctly.

2022-11-15 13:06 UTC, piotrkonowrocki requested changes
I don't feel like an expert of databases, but there are couple of things that I noticed and they have to be fixed before we can proceed with proper review.

1. Prisma migrations should contain only a diff of changes between current state of database and new one. In here migration seems to contain entire database structure.
2. Structure of `feature_flags` table is counterproductive. In its current state every feature flag is separated column. That means that whenever someone would have to create new feature flag we would need to update database structure and new set of migrations. Instead I strongly suggest that this table should consist of only two columns:
`feature: UNIQUE STRING NOT NULL`
`status: BOOLEAN NOT NULL`
With that setup every feature flag would become an item in database and for checking that one could simply try `SELECT status FROM feature_flags WHERE feature == "autoTakeProfit"`. IF status is returned as `true`, then it's enabled. If status is `false` or there are zero records, feature is disabled.
And thanks to that new feature flags won't require any change to database structure.

2022-11-15 13:59 UTC, adamskrodzki requested changes

2022-11-15 13:59 UTC, adamskrodzki commented on helpers/useFeatureToggle.ts
> +function capitalizeFirstLetter(string: string) {
is this name right? unless I'm terribly missing something this function changes first letter `toLowerCase`

2022-11-15 13:59 UTC, adamskrodzki commented on helpers/useFeatureToggle.ts
> +        if (process.env.NODE_ENV === 'production' && res.data) {
is staging `production` ? I think for staging it should also store in database.

2022-11-15 13:59 UTC, adamskrodzki commented on helpers/useFeatureToggle.ts
> +      if (localStorage !== undefined) {
so if it is undefined database entries are not loaded ?

2022-11-15 13:59 UTC, adamskrodzki commented on server/database/migrations/011-feature_flags.sql
> +-- CreateEnum
suspicious ? have you migrated database first ?
why script tries to create all that tables ?

2022-11-15 14:02 UTC, adamskrodzki commented on server/database/migrations/011-feature_flags.sql
> +CREATE TABLE "feature_flags" (
this table should be key/value 

something in lines of 

`CREATE TABLE "feature_flags" (
"id" SERIAL NOT NULL,
"featureName" varchar(20) NOT NULL,
"status" BOLEAN NOT NULL DEFAULT FALSE
)`

2022-11-15 14:18 UTC, George-field commented on helpers/useFeatureToggle.ts
> +        if (process.env.NODE_ENV === 'production' && res.data) {
Good point, I will check and add that

2022-11-15 14:26 UTC, George-field commented on helpers/useFeatureToggle.ts
> +function capitalizeFirstLetter(string: string) {
True, missed that, will update

2022-11-15 14:30 UTC, George-field commented
> 

Those are both good points @piotrkonowrocki. I also prefer your approach to the table so I'll implement them both.

2022-11-16 13:27 UTC, George-field commented on helpers/useFeatureToggle.ts
> +        if (process.env.NODE_ENV === 'production' && res.data) {
It is production on staging @adamskrodzki

2022-11-16 17:07 UTC, adamskrodzki approved these changes
Looks good, just set flags to correct defaults

2022-11-16 17:07 UTC, adamskrodzki commented on scripts/feature_flags_setup.ts
> +// TODD: Will need to get a list of all the feature flags that are currently set
resolve TODO

2023-02-14 09:45 UTC, closed without merging