Ades/aave/create calculation in usdc instead of eth
OasisDEX/oasis-borrow pull request #1719
Opened 2022-11-21 17:22 UTC by sennett

# [Create calculation in USDC instead of ETH
](https://app.shortcut.com/oazo-apps/story/6424/calculations-create-calculation-in-usdc-instead-of-eth)

- Formats things in order info panel to USDC instead of ETH. 
- Provides an observable that can be reused.
  
## How to test 🧪
- Create AAVE earn position - should be no regression.
- Go to create AAVE multiply position.  It should show in USDC.

2022-11-28 14:02 UTC, jakubswierczek requested changes

2022-11-28 14:02 UTC, jakubswierczek commented on components/AppContext.ts
> +
too much oxygen here

2022-11-29 08:20 UTC, sennett commented on features/aave/common/components/informationContainer/StrategyInformationContainer.tsx
> +        debtToken={state.context.token}
This has changed in the other PR with the generic flow.

2022-11-29 08:23 UTC, sennett commented on features/aave/common/components/informationContainer/FeesInformation.tsx
> +  const [currentDebtInDebtToken] = useObservable(
Good spot. FIxed.

2022-11-29 09:03 UTC, sennett commented on features/aave/common/components/informationContainer/OutstandingDebtInformation.tsx
> +  const { convertToAaveOracleAssetPrice$ } = useAppContext()
We can use swap price.  I will update in next PR.

2022-11-29 10:53 UTC, jakubswierczek approved these changes

2022-11-29 10:54 UTC, merged