Lw/5888 follow unfollow vault
OasisDEX/oasis-borrow pull request #1721
Opened 2022-11-22 08:36 UTC by johnnieskywalker

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-11-22 14:16 UTC, johnnieskywalker commented
the button atm
![image](https://user-images.githubusercontent.com/6871923/203336552-28d71c1d-1cfa-4303-8fd4-7db5de736101.png)

![image](https://user-images.githubusercontent.com/6871923/203336685-43388de4-1bc2-484e-b071-fe448b16d69a.png)

2022-11-22 14:58 UTC, johnnieskywalker commented
Added progress stages
![image](https://user-images.githubusercontent.com/6871923/203346021-2053cd13-4ac8-4bff-a133-8f5caa3361d6.png)

![image](https://user-images.githubusercontent.com/6871923/203346815-f0ab2d3d-02e0-4477-b784-c54d0aac6add.png)

2022-11-23 12:48 UTC, piekczyk requested changes

2022-11-23 12:48 UTC, piekczyk commented on scripts/docker/docker-compose.yaml
> +  # localnode:
uncomment it

2022-11-23 12:48 UTC, piekczyk commented on features/homepage/HomepageView.tsx
> +      <FollowButtonControl />
remove it from here since its not complete implementation

2022-11-23 12:48 UTC, piekczyk commented on features/follow/common/FollowButtonControl.tsx
> +  const [isProcessing, setProcessing] = useState(true)
its fine for now but eventually we will need also error handling

2022-11-23 13:09 UTC, piotrkonowrocki requested changes
In general, I feel like button is not entirely in line with designs.

- Different sizing and padding inside of a button.
- Different font size.
- Missing border.
- Different hover state, on design background color doesn't change, but border does.
- Loading icon is much smaller than on designs.
- When state of button is changing to loading, there is visible shift in text position. Maybe it would help to keep all types of icons, start and loading, in the same container that is positioned absolute? That way text always stays in the same place and only thing that is changing would be button width, which is totally okay.

2022-11-23 13:37 UTC, johnnieskywalker commented on scripts/docker/docker-compose.yaml
> +  # localnode:
oh sorry

2022-11-23 13:39 UTC, johnnieskywalker commented on features/follow/common/FollowButtonControl.tsx
> +  const [isProcessing, setProcessing] = useState(true)
True I'll put TODO mark

2022-11-24 14:44 UTC, piotrkonowrocki approved these changes

2022-11-24 14:48 UTC, piekczyk submitted a review, later dismissed

2022-11-24 15:11 UTC, piotrkonowrocki approved these changes

2022-11-24 15:17 UTC, merged