Lw/7315 unfollow api
OasisDEX/oasis-borrow pull request #1861
Opened 2023-01-12 15:11 UTC by johnnieskywalker

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2023-01-18 20:17 UTC, piotrkonowrocki requested changes

2023-01-19 12:19 UTC, johnnieskywalker commented on features/follow/common/FollowButtonControl.tsx
> +    if (vaultId && jwtToken && !isFollowing) {
you're right

2023-01-19 12:43 UTC, johnnieskywalker commented on features/follow/common/FollowButtonControl.tsx
> +    if (vaultId && jwtToken && !isFollowing) {
redactored this way
```ts

  async function buttonClickHandler() {
    setProcessing(true)
    const jwtToken = jwtAuthGetToken(followerAddress)
    if (vaultId && jwtToken) {
      if (!isFollowing) {
        await followVault(jwtToken)
      } else {
        await unfollowVault(jwtToken)
      }
    }
  }
  ```

2023-01-19 13:16 UTC, piotrkonowrocki approved these changes

2023-01-19 13:49 UTC, merged