Auto v1 v2 handling
OasisDEX/oasis-borrow pull request #1896
Opened 2023-01-17 14:02 UTC by piekczyk

# [Auto v1 v2 handling](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- tbd
  
## How to test 🧪
  <Please explain how to test your changes>
- tbd

2023-01-18 13:45 UTC, johnnieskywalker commented on blockchain/calls/automationBot.ts
> +  replacedTriggerIds: any // BigNumber[]
So maybe we just change implementation in common to be array-friendly ?

https://github.com/OasisDEX/common/blob/main/packages/transactions/src/types.ts#L15

2023-01-18 20:02 UTC, piotrkonowrocki requested changes

2023-01-18 20:02 UTC, piotrkonowrocki commented on package.json
> +    "@oasisdex/automation": "1.2.7-alpha.2",
Should that go to `dev` in that state?

2023-02-08 10:56 UTC, piotrkonowrocki approved these changes

2023-02-08 11:23 UTC, merged