Follow Vault Validation
OasisDEX/oasis-borrow pull request #1911
Opened 2023-01-19 18:24 UTC by johnnieskywalker

# [Validation following limited to 30 vaults](https://app.shortcut.com/oazo-apps/story/5893/validation-limit-number-of-followed-vaults)
  
## Changes 👷‍♀️
- Added Validation on API and frontend level
  
## How to test 🧪
- Insert more than 30 vaults into your db
```sql

INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2137, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2138, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2139, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2140, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2141, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2142, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2143, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2145, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2146, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2147, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2148, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2149, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2150, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2151, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2152, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2153, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2154, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2155, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2156, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2157, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2158, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2159, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2160, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2161, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2162, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2163, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2164, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2165, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2166, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2167, 'borrow'::public."vault_type", '0xasfsa', 1);
INSERT INTO public.vault
(vault_id, "type", owner_address, chain_id)
VALUES(2168, 'borrow'::public."vault_type", '0xasfsa', 1);

```

- Follow 29 or 30 vaults
```sql
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2138,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2139,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2140,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2141,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2142,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2143,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2144,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2145,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2146,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2147,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2148,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2149,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2150,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2151,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2152,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2153,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2154,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2155,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2156,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2157,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2158,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2159,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2160,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2161,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb171ddf49af82250d7723195d7e47ca38a95',2162,1);
INSERT INTO public.users_who_follow_vaults (user_address,vault_id,vault_chain_id)
	VALUES ('0x497cb [...]

2023-01-24 14:06 UTC, piotrkonowrocki requested changes

2023-01-24 14:09 UTC, piotrkonowrocki commented
I strongly suggest merging https://github.com/OasisDEX/oasis-borrow/pull/1924 first for two reasons.

1. You missed one thing from designs, blocked input when you are following to many vaults should have different background color and in PR above and rearranged a lot of styling, so it's going to be easier for you to work on that version.
2. There suppose to be a tooltip on short version of button, without it we don't have all cases covered.

2023-01-26 10:52 UTC, piotrkonowrocki requested changes
In figma there was a specific state for this button when you reached limit, background had different color, first screenshot is from implementation, second from figma. Also, something happend with positioning of the button, it's no longer in line with header text. You've added extra div around button and it fell apart. ~~Instead of `Box` component I suggest using `Flex` with `alignItems` set to `center`, that should do the trick.~~ Update: in https://github.com/OasisDEX/oasis-borrow/pull/1938 I've wrapped both follow and share button with `Flex` component, try merging dev to your branch first and see if it solves this issue.
![image](https://user-images.githubusercontent.com/16230404/214817203-ed68e415-5d53-4f96-8204-cce4a3ff9ffb.png)
![image](https://user-images.githubusercontent.com/16230404/214817291-73a16b78-2e5f-4d45-8bff-dd561d40ade7.png)



In some vault headlines components doesn't fit anymore. That should be probably consulted with someone from design team how to approach it. We have too much stuff in there, but this has to be solved. It's not even a small screen view, but full width.
![image](https://user-images.githubusercontent.com/16230404/214815368-bc316fdc-9cd1-4ec5-8330-ffe7c4e1d9ec.png)

Tooltip on follow button on discover table is inconsistent with design. Position is different, it's size and font color. First screenshot is from implementation, second from figma. Additionally, in my opinion that tooltip should be shown only when user is hovering over button. In its current state it is visible whenever you hover over entire table cell.
![image](https://user-images.githubusercontent.com/16230404/214816818-59303b95-2b11-423e-adba-f48d59e5c1d2.png)
![image](https://user-images.githubusercontent.com/16230404/214816865-65c98a05-5e2b-45de-b252-004e6b173aad.png)

2023-01-26 11:02 UTC, piotrkonowrocki requested changes
One final thought. Implementing `followVault` component on any page not became quite complicated. Besides just putting component with proper props, now you need to create a state outside of it and pass it to the controller. And that has to happen separately on every iteration whenever you use it on some pages. I wonder if Adam's suggestion about UI changes wouldn't work better here, since all `followVault` component would talk here between each other via UI changes, not parent.

@piekczyk, any thoughts about that? Also, @adamskrodzki? You were suggesting using UI changes from beginning.

2023-01-26 11:16 UTC, piekczyk commented on features/follow/common/FollowButtonControl.tsx
> +    // setIsFollowing(true)
> One final thought. Implementing `followVault` component on any page not became quite complicated. Besides just putting component with proper props, now you need to create a state outside of it and pass it to the controller. And that has to happen separately on every iteration whenever you use it on some pages. I wonder if Adam's suggestion about UI changes wouldn't work better here, since all `followVault` component would talk here between each other via UI changes, not parent.
> 
> @piekczyk, any thoughts about that? Also, @adamskrodzki? You were suggesting using UI changes from beginning.

agree, ui changes or dedicated react context in that case would be much better

2023-01-30 11:34 UTC, johnnieskywalker commented
> In figma there was a specific state for this button when you reached limit, background had different color, first screenshot is from implementation, second from figma. Also, something happend with positioning of the button, it's no longer in line with header text. You've added extra div around button and it fell apart. ~Instead of `Box` component I suggest using `Flex` with `alignItems` set to `center`, that should do the trick.~ Update: in #1938 I've wrapped both follow and share button with `Flex` component, try merging dev to your branch first and see if it solves this issue. ![image](https://user-images.githubusercontent.com/16230404/214817203-ed68e415-5d53-4f96-8204-cce4a3ff9ffb.png) ![image](https://user-images.githubusercontent.com/16230404/214817291-73a16b78-2e5f-4d45-8bff-dd561d40ade7.png)
> 
> In some vault headlines components doesn't fit anymore. That should be probably consulted with someone from design team how to approach it. We have too much stuff in there, but this has to be solved. It's not even a small screen view, but full width. ![image](https://user-images.githubusercontent.com/16230404/214815368-bc316fdc-9cd1-4ec5-8330-ffe7c4e1d9ec.png)
> 
> Tooltip on follow button on discover table is inconsistent with design. Position is different, it's size and font color. First screenshot is from implementation, second from figma. Additionally, in my opinion that tooltip should be shown only when user is hovering over button. In its current state it is visible whenever you hover over entire table cell. ![image](https://user-images.githubusercontent.com/16230404/214816818-59303b95-2b11-423e-adba-f48d59e5c1d2.png) ![image](https://user-images.githubusercontent.com/16230404/214816865-65c98a05-5e2b-45de-b252-004e6b173aad.png)

Fixed the positioning of an Tooltip like this: 
![image](https://user-images.githubusercontent.com/6871923/215465547-d6aed5ae-aeff-4ec3-a448-a0a15cc07528.png)


Regarding headline where button doesn't fit where limit is reached, can we agree that this is edge case, that could be addressed in different story, after redesigning headlines ? For vaults that have short names it meets requirements unfortunately some have longer names than that 

![image](https://user-images.githubusercontent.com/6871923/215466015-ce836c47-c071-4a46-9a94-61b1ead927e6.png)

2023-01-30 12:27 UTC, piotrkonowrocki requested changes
I'm ignoring button not fitting in headline as it's going to be fixed as separated story, right?

This is the third time I'm pointing out the same thing; according to the designs disabled button has different background color.
![image](https://user-images.githubusercontent.com/16230404/215472580-583c8c78-3811-4299-91d7-053187070b19.png)
Also, when button is disabled, there shouldn't be a hover on it. Right now when i mouseover it is still highlighting.
![image](https://user-images.githubusercontent.com/16230404/215472898-b511c69a-7ca0-48c3-80a2-6e8b0c1d3efb.png)
According to figma, tootlip should be centered, but I don't know, I think I'm ready to let it slide and accept as it is, that's no big difference. But there's different weird thing about this button, tooltip is showing only when I hover over the star in it, not on the entire button.
![image](https://user-images.githubusercontent.com/16230404/215473271-56461378-365b-4e2d-86ba-938d30f8b598.png)

2023-01-30 12:27 UTC, piotrkonowrocki commented on features/automation/common/consts.ts
> +export const LIMIT_OF_FOLLOWED_VAULTS = 30
Why is that `const` declared inside of an automation directory?

2023-01-30 12:27 UTC, piotrkonowrocki commented on features/automation/follow/followedVaultsLimitReached.ts
> +export const FOLLOWED_VAULTS_LIMIT_REACHED_CHANGE = 'FOLLOWED_VAULTS_LIMIT_REACHED_CHANGE'
This file and also the one below (`features/automation/follow/useFollowInitialization.ts`) shouldn't be stored inside of automation directory.

2023-01-30 12:27 UTC, piotrkonowrocki commented on features/discover/common/DiscoverData.tsx
> +            {...(!!walletAddress && {
Why is this initialized twice? The one below should be enough, especially that this initialization doesn't account for follow vault feature flag.

2023-01-30 12:27 UTC, piotrkonowrocki commented on features/follow/common/FollowButton.tsx
> +          pointerEvents: 'visible',
According to css documentation, `pointerEvents: visible` should be used only for svg files. For html there is `pointerEvents: none` if you want to remove events and `pointerEvents: auto` if you wan't to bring them back. But why in that case you wan't to add events to disabled button?

2023-01-30 12:27 UTC, piotrkonowrocki commented on features/follow/common/FollowButton.tsx
> +            width: ['auto'],
Why in bracket? There aren't any different rwd version for it.

2023-01-30 12:27 UTC, piotrkonowrocki commented on features/follow/common/FollowButton.tsx
> +              fontFamily: 'Inter',
For most of the cases in this `sx` you could just use variant `paragraph4`. It has compatible font size, family and weight and also line height. For font style - why is it there? Is this place italic by default and had to be removed for that part.

2023-01-30 12:27 UTC, piotrkonowrocki commented on pages/[vault]/index.tsx
> +    useFollowInitialization({ isLimitReached: false })
Just a thought, I'm not sure if it. I've counted this line:
```useFollowInitialization({ isLimitReached: false })```
Is there a chance to put it someplace more global, so you could use follow button without this initialization? Is there some wrapper or HOC that exist around all three pages that currently has follow? Position page, user's page and discover.

2023-01-30 12:31 UTC, johnnieskywalker commented on features/follow/common/FollowButton.tsx
> +          pointerEvents: 'visible',
as a trick to make tooltip appear when you're hovering over disabled button

2023-01-30 13:33 UTC, johnnieskywalker commented on features/discover/common/DiscoverData.tsx
> +            {...(!!walletAddress && {
probably mistake during resolving conflicts or something, removed duplication

2023-02-01 13:52 UTC, johnnieskywalker commented
> 1. Disabled button is STILL different color, than in figma. That should be `neutral30` if I'm not mistaken.
> 2. Hover effect is still visible on disabled button. Border color change is gone, but star is still changing it's color and stroke width.
> 3. Box shadow is gone from disabled button - is that intentional? Because if disabled button is next to share button it looks out of place. Especially that this change also affected disabled button when it's is in its progress state, not only when you reached limit of vaults you can follow.
> 4. Somehow follow button in discover stopped being perfectly round, now they are roundish. I compared to staging, on staging they are fine.

https://user-images.githubusercontent.com/6871923/216061730-dba39fad-256c-49b3-b762-5811c24ebd9c.mp4

2023-02-02 11:16 UTC, piekczyk commented
When button is disabled star is clipped

![image](https://user-images.githubusercontent.com/39706811/216310133-c1a72528-57b9-4670-a719-07fbc6a2ca49.png)

![image](https://user-images.githubusercontent.com/39706811/216310449-a7d2b7a3-40f7-4344-8ac9-56e68f844401.png)

2023-02-02 11:37 UTC, piekczyk requested changes

2023-02-02 11:37 UTC, piekczyk commented on features/discover/common/DiscoverData.tsx
> +                  chainId: NetworkIds.MAINNET,
shouldn't we use here id per specific network instead of hardcoded mainnet?

2023-02-02 11:37 UTC, piekczyk commented on features/follow/controllers/FollowButtonControl.tsx
>      await unfollowVaultUsingApi(vaultId, chainId, jwtToken)
a simple try catch should be used here and in `followVault` method, right now when there are connection issues or db is down on the UI it looks like user indeed unfollowed / followed vault but it's not true since that information wasn't stored in db

2023-02-02 11:37 UTC, piekczyk commented on features/follow/controllers/FollowButtonControl.tsx
>      await unfollowVaultUsingApi(vaultId, chainId, jwtToken)
and please move definitions `unfollowVault` and `followVault` above return statement. I know that hoisting do the job but it looks super weird.

2023-02-02 11:49 UTC, piotrkonowrocki commented on features/discover/common/DiscoverData.tsx
> +                  chainId: NetworkIds.MAINNET,
That is intentional, I did that. Discover always displays only mainnet vaults.

2023-02-02 12:13 UTC, johnnieskywalker commented
> I'm ignoring button not fitting in headline as it's going to be fixed as separated story, right?
> 
> This is the third time I'm pointing out the same thing; according to the designs disabled button has different background color. ![image](https://user-images.githubusercontent.com/16230404/215472580-583c8c78-3811-4299-91d7-053187070b19.png) Also, when button is disabled, there shouldn't be a hover on it. Right now when i mouseover it is still highlighting. ![image](https://user-images.githubusercontent.com/16230404/215472898-b511c69a-7ca0-48c3-80a2-6e8b0c1d3efb.png) According to figma, tootlip should be centered, but I don't know, I think I'm ready to let it slide and accept as it is, that's no big difference. But there's different weird thing about this button, tooltip is showing only when I hover over the star in it, not on the entire button. ![image](https://user-images.githubusercontent.com/16230404/215473271-56461378-365b-4e2d-86ba-938d30f8b598.png)

yes PR is ready https://github.com/OasisDEX/oasis-borrow/pull/1965

2023-02-02 13:43 UTC, piekczyk commented on features/follow/controllers/FollowButtonControl.tsx
>      const followedVaults = await followVaultUsingApi(vaultId, chainId, jwtToken)
this method should be within try block

2023-02-02 13:59 UTC, piekczyk approved these changes

2023-02-02 14:07 UTC, piotrkonowrocki approved these changes

2023-02-02 14:07 UTC, merged