Component for creating DPM and Allowance flow
OasisDEX/oasis-borrow pull request #1947
Opened 2023-01-27 15:55 UTC by marcinciarka

# TBD

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2023-01-31 15:34 UTC, piotrkonowrocki requested changes
Few comments about allowance stage:
- Before I select any option, the button should be disabled.
- Loader never stops spinning. Also, there's a funny effect, every time when I hover over anything inside of a sidebar it resets and try spinning from the top 💃
![image](https://user-images.githubusercontent.com/16230404/215802184-52c70f0e-156b-4969-95fd-18ec1bd72515.png)

After selecting amount and confirming transaction, the message in sidebar is incomplete. Shouldn't it say "(...) Your Smart Defi Account will be able to interact with up to: **AMOUNT**", since we know what was selected?
![image](https://user-images.githubusercontent.com/16230404/215803089-fe66a254-a2c3-438f-bb8e-69315fbfda52.png)
![image](https://user-images.githubusercontent.com/16230404/215803540-ac56b3d1-628b-44d8-bc5b-1444703e7b48.png)

Shouldn't there be something else on allowance success screen? An image similar to the on on dpm success screen?
![image](https://user-images.githubusercontent.com/16230404/215804213-1650dbe0-3d1d-4b3b-9813-b977c07a7d5f.png)

When I click continue on success screen, after a second or so success screen is shown up again. Data from `onEverthingReady` seems to be correct:
![image](https://user-images.githubusercontent.com/16230404/215804760-a7a72f9a-6a3c-4354-8925-e2cf43a8d08d.png)

2023-01-31 15:41 UTC, jakubswierczek requested changes

2023-01-31 15:41 UTC, jakubswierczek commented on helpers/useFlowState.ts
> +    const walletConnectionSubscription = context$.subscribe(({ status, account }) => {
`useObservable`

2023-01-31 15:41 UTC, jakubswierczek commented on helpers/useFlowState.ts
> +export function useFlowState({
why do we have two responsibilities in one flow? 
we should have one flow for DPMs and one for allowance.

2023-01-31 15:41 UTC, jakubswierczek commented on helpers/useFlowState.ts
> +}: UseFlowStateProps) {
I think we should take `owner` as a parameter. Not getting wallet address from `context$`.

2023-01-31 15:41 UTC, jakubswierczek commented on helpers/useFlowState.ts
> +  onEverythingReady?: (params: {
please make a type for an event

2023-01-31 15:41 UTC, jakubswierczek commented on helpers/useFlowState.ts
> +    isEverythingReady: isAllowanceReady, // just for convenience, allowance is always the last step
What about the situation when the user has approval for a given amount?

2023-01-31 16:30 UTC, piotrkonowrocki requested changes

2023-01-31 16:30 UTC, piotrkonowrocki commented on components/FlowSidebar.tsx
> +        return <DPMInfoStateView state={dpmState} send={dpmSend} />
Allowance is nicely split and separated into `AllowanceView`, I suggest moving DPM related components from this file to something similar.

2023-01-31 16:30 UTC, piotrkonowrocki commented on helpers/useFlowState.ts
> +export function useFlowState({
This is expected behavior. For our current needs there isn't a situation where you need only DPM or only allowance flows - they always come as a pair.

We also spoke that in the future that could be refined into a wrapped that merges two separated flow, but for now this is exactly what we need.

2023-01-31 16:30 UTC, piotrkonowrocki commented on helpers/useFlowState.ts
> +  onEverythingReady,
We are going to need one more callback: `onBack`. If function is passed, there should be a `textButton` passed to sidebar that would trigger this callback. Thanks to that you can always get back from allowance or dpm step back to from wherever you came from.

And I guess that button should be visible only on first steps of both flows. If we put it on progress, success or error screen then it doesn't make any sense.

2023-02-01 14:53 UTC, marcinciarka commented on helpers/useFlowState.ts
> +}: UseFlowStateProps) {
We're never gonna check the DPM accounts of another address than wallet and this simplifies things. If you have a strong opinion please reopen :v:

2023-02-01 14:56 UTC, marcinciarka commented on helpers/dummyStateMachine.ts
> +    dpmAccounts$: createdDpmAccount.asObservable(),
Nope in both cases, removed.

2023-02-01 14:59 UTC, marcinciarka commented on helpers/useFlowState.ts
> +  onEverythingReady,
This is ultimately _always_ the last step, thats why I named it like this.

2023-02-01 15:30 UTC, marcinciarka commented on helpers/useFlowState.ts
> +    isEverythingReady: isAllowanceReady, // just for convenience, allowance is always the last step
There's a check for that in `allowanceSubscription`.

2023-02-01 16:13 UTC, marcinciarka commented on components/FlowSidebar.tsx
> +        return <DPMInfoStateView state={dpmState} send={dpmSend} />
Done.

2023-02-01 16:58 UTC, marcinciarka commented on helpers/useFlowState.ts
> +  onEverythingReady,
Done, `onGoBack`.

2023-02-01 20:56 UTC, jakubswierczek submitted a review, later dismissed

2023-02-02 11:12 UTC, piotrkonowrocki commented on helpers/useFlowState.ts
> +  onEverythingReady,
❤️

2023-02-02 12:46 UTC, piotrkonowrocki approved these changes

2023-02-02 12:47 UTC, merged