🧿 Ajna header selector
OasisDEX/oasis-borrow pull request #1957
Opened 2023-02-01 10:44 UTC by piotrkonowrocki

# [🧿 Ajna header selector](https://app.shortcut.com/oazo-apps/story/7327/select-collateral-token-drop-down)

For now, just the selector part without table and connection to anything.
![image](https://user-images.githubusercontent.com/16230404/216020431-3c15d720-6825-4c15-b191-9f8ffb8130ec.png)

Additionally, `HeaderSelector` can be used in any context as it inherits font styles from its parent.
![image](https://user-images.githubusercontent.com/16230404/216021242-dbd072ef-1657-426a-acbb-58a0a76e2869.png)
  
## Changes 👷‍♀️

- Created `HeaderSelector` component,
- added some basic tokens config for Ajna as sources.
  
## How to test 🧪

Go to `/ajna/open/borrow` and see how selector behaves. Changing its value won't affect anything on that page (for now).

2023-02-02 17:54 UTC, johnnieskywalker requested changes

2023-02-02 17:54 UTC, johnnieskywalker commented on features/ajna/common/consts.ts
> +export const ajnaUnavailablePairs: AjnaPairs = {
I'd suggest to name it commingSoonPairs, well AFAIK we won't support all possible pairs but some recommended list, `unavailable` ones are in fact ones that in UI are `Comming Soon`

2023-02-02 17:54 UTC, johnnieskywalker commented on components/HeaderSelector.tsx
> +              {option.label}
Even this hypothetical edge case is fine :ok_hand: 
![image](https://user-images.githubusercontent.com/6871923/216402491-c00c0572-bab7-4881-8bcc-296355af813d.png)

2023-02-02 17:54 UTC, johnnieskywalker commented on features/discover/common/DiscoverTableHeading.tsx
> +        mt: [3, null, null, 4],
I just quickly checked if everything remains great on discovery table it does :heavy_check_mark: 

https://user-images.githubusercontent.com/6871923/216403501-324e6839-faa1-424d-a9db-c91ea55d4e9f.mp4

2023-02-03 06:56 UTC, piotrkonowrocki commented on features/ajna/common/consts.ts
> +export const ajnaUnavailablePairs: AjnaPairs = {
Fixed.

2023-02-03 06:58 UTC, piotrkonowrocki commented on components/HeaderSelector.tsx
> +              {option.label}
Well, in that case it doesn't look very good imo 😅 But guni tokens can't be used as a collateral and there's no way that amount of text could fit in there. If that situation ever happen, font would have to be smaller for mobiles. But it's not the case right now.

2023-02-03 07:17 UTC, piekczyk approved these changes

2023-02-03 07:31 UTC, piekczyk approved these changes

2023-02-03 08:55 UTC, johnnieskywalker approved these changes

2023-02-03 08:58 UTC, merged