FLEX HEADLINE
OasisDEX/oasis-borrow pull request #1965
Opened 2023-02-02 11:55 UTC by johnnieskywalker

# [Implemented new flex Headline](https://app.shortcut.com/oazo-apps/story/7770/implement-new-version-of-vault-headline)
  
## Changes 👷‍♀️
- Added couple of CSS properties to make headline more flex like in design https://www.figma.com/file/XeMo7s0ZJgXgCHmOd588QY/Discover-Oasis-%235366?node-id=2904%3A16028&t=vGcRRXMM8TnPPiGp-0
- 
  
## How to test 🧪
- Here's short video that tests multiple cases and all are fine IMHO

https://user-images.githubusercontent.com/6871923/216317831-f786001c-242a-428d-9dbd-0124cbb7a217.mp4

- This is longer version with more extreme trials, mobile issues found during this recording are fixed, but you can test it too, try think of even more unusual edge cases

https://user-images.githubusercontent.com/6871923/216317995-ab57c342-7cac-4557-9965-fbaa4ac0ecf3.mp4

2023-02-02 13:00 UTC, johnnieskywalker commented on features/follow/common/FollowButtonControl.tsx
> +  async function unfollowVault(jwtToken: string) {
this commit was for different branch I'll revert it however it doesn't break anything

2023-02-02 13:46 UTC, johnnieskywalker commented on features/follow/common/FollowButtonControl.tsx
> +  async function unfollowVault(jwtToken: string) {
I reset branch and force pushed without that commit that was supposed to go to another branch

2023-02-02 15:14 UTC, piotrkonowrocki requested changes
Checked, tried to break it, looks like everything works as intended. I have one tiny comment - according to the designs, there should be 16px gap between two lines when they can't fit next to each other. The easiest way to achieve it would be adding `rowGap: 3` their container.

Also, I would feel more comfortable if some other front-end beside me checked it, since there might be some edge cases here that I didn't thought of.

2023-02-03 11:41 UTC, johnnieskywalker commented
https://user-images.githubusercontent.com/6871923/216594826-3afacb10-6f92-4c2c-b711-b06e9063a17d.mp4

2023-02-03 12:20 UTC, marcinciarka approved these changes

2023-02-03 12:23 UTC, piotrkonowrocki approved these changes

2023-02-03 12:23 UTC, merged