Fixing owner page after adding a new position
OasisDEX/oasis-borrow pull request #1997
Opened 2023-02-10 15:28 UTC by marcinciarka

# [The my positions page is broken at the moment with this new position](https://app.shortcut.com/oazo-apps/story/7983/the-my-positions-page-is-broken-at-the-moment-with-this-new-position)

  
## Changes 👷‍♀️
- Fixing owner page when displaying Aave V3 position
  
## How to test 🧪
- `/owner/0x165d0df29d9262f8ee9e9874c906eab706a05c2c` - this has Aave V3 position

2023-02-10 17:29 UTC, jakubswierczek commented on features/vaultsOverview/pipes/positions.ts
> +type OnChainAavePositionTypes = 'AAVE_V2' | 'AAVE_V3'
Use the enum

2023-02-10 17:30 UTC, jakubswierczek requested changes
Great work,
The change with `ProtcolServices` is not very important, but please change the string type to an enum to have only one place with it.

2023-02-13 09:15 UTC, marcinciarka commented on features/vaultsOverview/pipes/positions.ts
> +  aaveV3: ProtocolsServices['AaveV3']
Fixed.

2023-02-13 09:16 UTC, marcinciarka commented on features/vaultsOverview/pipes/positions.ts
> +type OnChainAavePositionTypes = 'AAVE_V2' | 'AAVE_V3'
Fixed.

2023-02-13 10:17 UTC, jakubswierczek approved these changes

2023-02-13 10:17 UTC, merged