🧿 Ajna borrow validations handling
OasisDEX/oasis-borrow pull request #2030
Opened 2023-02-14 15:24 UTC by piekczyk

# [Ajna borrow validations handling](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- added handling for ajna borrow validations, both for library and local
- added local validation regarding collateral and quote token balance
- added local validation regarding funds for transaction
  
## How to test 🧪
  <Please explain how to test your changes>

- try to deposit more collateral than you have in wallet
- try to payback more debt than you have in wallet
- try to send tx with insufficient eth balance to pay for it

2023-02-15 13:40 UTC, piotrkonowrocki requested changes

2023-02-15 13:40 UTC, piotrkonowrocki commented on features/ajna/borrow/helpers.tsx
> +    !!errors.messages.length
Instead of that, shouldn't that be incorporated in `isStepValid`? That was the purpose of that prop.

2023-02-15 13:40 UTC, piotrkonowrocki commented on features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
> +  const { errors, warnings } = getAjnaBorrowValidations({
I'm not exactly sold if that's the best approach for it. Maybe errors and warnings should work as props for those components? Because right now you has to pass `paybackAmount`, but this place doesn't even use it. And it's duplicated four times for each component with form fields.

2023-02-15 13:40 UTC, piotrkonowrocki commented on features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
> +  const { errors, warnings } = getAjnaBorrowValidations({
Especially that it is already invoked above in `features/ajna/borrow/sidebars/AjnaBorrowFormContent.tsx`.

2023-02-15 14:08 UTC, piekczyk commented on components/ValidationMessages.tsx
> +  messages: string[]
but this is the part which is already within `additionalData`. If we would like to move it inside messages we will need to refactor exiting mappers which use that interfaces.

2023-02-15 15:02 UTC, piotrkonowrocki requested changes

2023-02-15 15:10 UTC, piekczyk commented on features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
> +      <AjnaValidationMessages
I did it on purpose to avoid situation where we will display to separate error lists next to each other.

2023-02-15 15:13 UTC, piekczyk commented on features/ajna/contexts/AjnaProductContext.tsx
> +      form.state.paybackAmount?.toString(),
maybe, but for now only `paybackAmount` and `depositAmount` are relevant for validations

2023-02-15 15:24 UTC, piotrkonowrocki commented on features/ajna/contexts/AjnaProductContext.tsx
> +      form.state.paybackAmount?.toString(),
But we have to remember that in the future library is going to validate entire form and will take in account rest of form state values. Anyway, I'm okay with leaving it as is right now if you don't want to update it right now. I'm keeping this thread open, please resolve it if you're not going to push any more changes related to it.

2023-02-15 15:25 UTC, piotrkonowrocki commented on features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
> +      <AjnaValidationMessages
In my opinion it's better to keep general errors and field specific errors as separated blocks, but that's just an opinion. I think we should let someone from design to decide on that.

2023-02-16 09:50 UTC, piotrkonowrocki approved these changes

2023-02-16 09:51 UTC, merged