Ajna product card links
OasisDEX/oasis-borrow pull request #2216
Opened 2023-04-03 08:08 UTC by piekczyk

# Ajna product card links

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- added links to product cards
- prepared initial version of ajna product cards observable which in next step will be extended with data needed for displaying stuff on UI per specific product card type
- extracted few common components

  
## How to test 🧪
  <Please explain how to test your changes>

- product cards available on Ajna lending page should redirect to proper pool selector

2023-04-06 11:13 UTC, piotrkonowrocki requested changes

2023-04-06 11:13 UTC, piotrkonowrocki commented on features/ajna/common/components/AjnaProductCardsWrapper.tsx
> +  <ProductCardsWrapper sx={{ mt: ['9px', '48px'], gap: ['88px', 3, 3] }}>
`9px` sounds kinda magic numbery, that should probably be `8px`, so just `2` from array.

2023-04-06 11:13 UTC, piotrkonowrocki commented on features/ajna/common/content.ts
> +type AjnaProductCardBorrowBase = {
1. Is this type anyhow Ajna specific? Could this component and it's type be reused in other places?
2. Even if not, file named `content.ts` doesn't sound like a good place to store type.

2023-04-06 11:13 UTC, piotrkonowrocki commented on features/ajna/common/content.ts
> +type AjnaProductCardEarnBase = AjnaProductCardBorrowBase
Yet another reason to make it more generic since both borrow and earn are using same type. Just `AlternateProductCardBase`.

2023-04-06 11:13 UTC, piotrkonowrocki commented on features/ajna/common/content.ts
> +export const benefitCardsAnja = [
Suggestion, let me know what you think. This is something that I actually wanted to talk about on front-end conventions panel, but time did not allowed to do that.

What about changing approach to design pattern with components in views? Instead of having this config in separated place and passing it directly to abstract component on landing page view, create controller. Controller doesn't have any props, you could include it directly in view. Then, inside of controller you could store those config directly since it's not abstract, it's Ajna specific, that one single place specific, and then pass it to abstract component.

~~Same could be applied to product cards config.~~ Now I noticed that product cards already have their controller working similar to what I just described, to that would be a better place to store all those data and its types and get rid of this file.

Happy to talk more about it more.

2023-04-06 11:13 UTC, piotrkonowrocki commented on patches/@oasisdex+oasis-actions+0.2.16.patch
Is that change related to this PR and intentional?

2023-04-06 11:33 UTC, piekczyk commented on patches/@oasisdex+oasis-actions+0.2.16.patch
yes, it is some kind of left over

2023-04-11 08:16 UTC, piotrkonowrocki approved these changes

2023-04-11 08:20 UTC, merged