🧿 Extend Ajna Context for Multiply Product
OasisDEX/oasis-borrow pull request #2223
Opened 2023-04-11 11:36 UTC by piotrkonowrocki

# [🧿 Extend Ajna Context for Multiply Product](https://app.shortcut.com/oazo-apps/story/8660/extend-ajna-context-for-multiply-product)

Extended `AjnaProductContext` and `AjnaProductController` to fit Multiply product. So far this is just the context, no UI changes were made.
  
## Changes 👷‍♀️

- Created fake `AjnaMuliplyPosition` interface to be replaced in the future with one from library,
- added support for Multiply product in Ajna context,
- created `AjnaMultiplyFormReducto` for opening part of the flow.
  
## How to test 🧪

- See if `/ajna/multiply/WBTC-USDC` doesn't break the application,
- see if Borrow/Earn flows are still working.

2023-04-11 13:26 UTC, piekczyk requested changes

2023-04-11 13:26 UTC, piekczyk commented on features/ajna/positions/common/contexts/AjnaProductContext.tsx
> +    product === 'borrow'
maybe instead of this we could use map? 

```
const context = {
   borrow: useContext(ajnaBorrowContext),
   earn: useContext(ajnaEarnContext),
   multiply: useContext(ajnaMultiplyContext),
}
```

2023-04-11 13:26 UTC, piekczyk commented on features/ajna/positions/common/controls/AjnaProductController.tsx
> +                        {dpmPosition.product === 'multiply' && (
It won't work for cases where product type was overwritten by user while switching position type on UI. Here we need to use data from borrow db.

2023-04-11 14:23 UTC, piotrkonowrocki commented on features/ajna/positions/common/contexts/AjnaProductContext.tsx
> +    product === 'borrow'
Then in the end of this method we would have to check which of those context from map has to be returned. This condition is inevitable, but if we use it in the beginning, at least we are creating only the context we actually need, not all three of them.

2023-04-12 10:20 UTC, piotrkonowrocki commented on features/ajna/positions/common/controls/AjnaProductController.tsx
> +                        {dpmPosition.product === 'multiply' && (
Fixed, product type is checked on observable level.

2023-04-12 10:55 UTC, piekczyk approved these changes

2023-04-12 11:19 UTC, merged