Ajna mining rewards
OasisDEX/oasis-borrow pull request #2227
Opened 2023-04-12 08:08 UTC by piekczyk

# [Ajna mining rewards](https://app.shortcut.com/oazo-apps/story/8562/fe-ajna-lm-reward-claiming)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- updated designs
- added transaction handling (not tested yet)
- added data source
  
## How to test 🧪
  <Please explain how to test your changes>

- TBD

2023-04-12 14:15 UTC, piotrkonowrocki requested changes
Comments about UI:

1. Missing "Exclusive to Oasis.app" pill.
![image](https://user-images.githubusercontent.com/16230404/231478551-5a583738-f3b7-4419-b378-a1ad78db8563.png)
2. I really don't like skeleton loading in place of entire box with rewards details, but that's just my personal opinion. I would prefer to display separated smaller animations in place of every value that isn't available from beginning. But on the other hand, that might look bad because of gradient background underneath it. I suggest getting some opinions about that from Hazel.
3. There are some minor deviations from design in terms of spacing in reward cards, but I think they are reasonable and there is nothing that might require reworking.

2023-04-12 14:15 UTC, piotrkonowrocki commented on features/ajna/rewards/useAjnaUserNfts.ts
> +    return {
Consider if it's doable to merge those two returns into a one response. They are both returning same interface, but imo would be easier to read instead of splitting depending on single condition.

If it's not possible, then just resolve this comment.

2023-04-12 15:51 UTC, piekczyk commented on components/WithArrow.tsx
> +      {...(as ? { as } : {})}
fixed

2023-04-12 16:03 UTC, piekczyk commented on features/ajna/rewards/useAjnaUserNfts.ts
> +    return {
I've done that in this way because I was able to define `tokenRewards` and use it in two places without making any additional conditions.

2023-04-13 09:48 UTC, piotrkonowrocki approved these changes

2023-04-13 10:33 UTC, merged