🧿 Manage Multiply Position Form
OasisDEX/oasis-borrow pull request #2241
Opened 2023-04-17 09:23 UTC by piotrkonowrocki

# [Manage Multiply Position Form](https://app.shortcut.com/oazo-apps/story/8744/manage-multiply-position-form)

Managing part of Ajna Multiply form.

![image](https://user-images.githubusercontent.com/16230404/232440619-535d4926-f4c1-4e83-9edb-cfeb58cf81d5.png)
![image](https://user-images.githubusercontent.com/16230404/232440487-80f7090e-e464-4be0-ab60-0ee6f05232fa.png)
![image](https://user-images.githubusercontent.com/16230404/232440407-bfe5e594-1bfe-422d-8070-e244940d2100.png)
  
## Changes 👷‍♀️

- Created manage form UI with all steps/layouts from form dropdown and pills,
- modified `InfoSection component`:
  - renamed `secondaryValue` to `change`, as it is always used to the same value, as in afterpill,
  - created actual `secondary` prop with `value` and `variant` properties to display secondary value shown in parenthesis (price impact etc.) with proper color.
  
## How to test 🧪

- In `oasis-borrow/pages/ajna/[product]/[pool].tsx:19` change `open` to `manage`,
- go to `/ajna/multiply/WBTC-USDC` to display opening flow with multiply UI,
- please note than primary button won't be visible in that setting since this is a manage form and the owner of it is `0x0000000000000000000000000000000000000000`.

2023-04-17 11:30 UTC, piekczyk requested changes

2023-04-17 11:30 UTC, piekczyk commented on features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
> +  const withBuying = action === 'deposit-quote-multiply'
I think `open-multiply`, `deposit-collateral-multiply` should be also considered here since you are able to adjust multiply while performing these actions

2023-04-17 11:30 UTC, piekczyk commented on features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
> +  const withSelling = action === 'close-multiply'
I believe that in maker there is a condition for checking whether user moved slider and then and only then additional data regarding buying / selling is shown

2023-04-17 11:32 UTC, piekczyk commented
I think we are missing `adjust` step.

2023-04-17 12:47 UTC, piotrkonowrocki commented on features/ajna/positions/common/helpers/getFlowStateConfig.ts
> +    case 'deposit-quote-multiply':
IMO they aren't related to any specific product, it's just that `open/deposit-earn` and `deposit-quote-multiply` requires exactly the same config for flow component. I'm okay with changing that if you feel that it's going to look better if I split it, just wanted to get confirmation.

2023-04-17 12:56 UTC, piotrkonowrocki commented on features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
> +  const withSelling = action === 'close-multiply'
As in above.

2023-04-17 14:00 UTC, piotrkonowrocki commented
> I think we are missing `adjust` step.

🤦 
Added.

2023-04-18 09:10 UTC, piekczyk approved these changes

2023-04-18 09:10 UTC, merged