Ad tenderly as rpc
OasisDEX/oasis-borrow pull request #2291
Opened 2023-05-18 07:58 UTC by adamskrodzki

# [Adjust /rpc endpoint to be switchable to tenderly fork]
https://app.shortcut.com/oazo-apps/story/8981/adjust-rpc-endpoint-to-be-switchable-to-tenderly-fork

  
## Changes 👷‍♀️
- new environment variable TENDERLY_FORK_ID  in format like b12b2b04-f54b-11ed-a05b-0242ac120003
- feature flag UseTenderlyRPC 
- if feature flag is set to true all RPC traffic is redirected to tenderly

  
## How to test 🧪

IN order to test it properly you need also set either tenderly or oasis rpc url as your RPC in a wallet

At that point any functionality that is not 1 inch dependent should work (draw debt for example) across whole aplication

2023-05-18 09:43 UTC, paszkowskiDamian requested changes
I would go with earn solution where you can change rpc on the UI level. @jakubswierczek

2023-05-18 09:45 UTC, jakubswierczek requested changes
We shouldn't use Tenderly explicitly in our app. We are working on a solution to provide a custom RPC node in the network switcher.
Tenderly isn't a network. It's a provider. 
Close the pull request and never bring it up again.

2023-05-18 09:45 UTC, jakubswierczek requested changes
We shouldn't use Tenderly explicitly in our app. We are working on a solution to provide a custom RPC node in the network switcher.
Tenderly isn't a network. It's a provider. 
Close the pull request and never bring it up again.

2023-05-18 09:47 UTC, marcinciarka commented
+1

2023-05-18 14:52 UTC, adamskrodzki commented
@jakubswierczek @marcinciarka We need a way to test ajna end-to-end with 1inch integration. Read epic related to the story and feel free to propose better solution, but ensure you understodd epic first. 

Problem is:

1) We need nodes that sync quickly (so hardhat is off the table)
2) We need node forked from relatively fresh block, so pasting url like https://rpc.tenderly.co/fork/[YOUR HARDCODED GUID HERE] is off the table.

we need some kind of proxy to change forks in a background.

2023-05-19 08:23 UTC, adamskrodzki commented on pages/api/rpc.tsx
> +  if (tenderlySecret === process.env.TENDERLY_SECRET && network === NetworkNames.ethereumTenderly) {
authorization,
to prevent random clients to use our tenderly. requires to set correct secret value in local storage

2023-05-22 14:38 UTC, jakubswierczek requested changes

2023-05-22 14:38 UTC, jakubswierczek commented on .env
> +TENDERLY_FORK_ID=b12b2b04-f54b-11ed-a05b-0242ac120003
Add empty string here.

2023-05-22 14:38 UTC, jakubswierczek commented on components/AppContext.ts
> +import { getTenderlyRpcUrl } from 'config/rpcConfig'
I prefer to avoid naming specific products. Can we call it `getCustomForkRpcUrl`?

2023-05-22 14:38 UTC, jakubswierczek commented on .env
> +TENDERLY_SECRET="test"
Avoid using the name "Tenderly."

2023-05-22 14:38 UTC, jakubswierczek commented on components/AppContextProvider.tsx
> +  }, [tenderlySecret])
We should not refresh the app context more than once, as our entire app relies on it. If we change it, the app will re-render. We should address this issue, but for now, we should simply refresh the page.

2023-05-22 14:38 UTC, jakubswierczek commented on components/AppContext.ts
> +export function setupAppContext(tenderlySecret: string) {
I have a negative opinion about including parameters in the app context initialiser.

2023-05-22 14:38 UTC, jakubswierczek commented on components/AppContext.ts
> +    chainIdToRpcUrl[NetworkIds.MAINNET] = getTenderlyRpcUrl(tenderlySecret)
Try not to alter the state.

2023-05-26 06:58 UTC, adamskrodzki commented on .env
> +TENDERLY_SECRET="test"
removed from TENDERLY_SECRET  but leaving in TENDERLY_FORK_ID

2023-05-26 07:01 UTC, adamskrodzki commented on components/AppContextProvider.tsx
> +  }, [tenderlySecret])
ok, I will change it back to [], my reasoning was that You want to refresh whole application if that value changes. But on other hand tenderlySecret is not reactive anyway

2023-05-26 07:08 UTC, adamskrodzki commented on components/AppContext.ts
> +export function setupAppContext(tenderlySecret: string) {
I do not have strong opinion on that matter I can add
`const tenderlySecret = getStorageValue<string>('tenderlySecret', '')` inside setupAppContext() 

but I feel that it's better to have in AppContextProvider since it is smaller AppContext so it is more visible, that we depend on some storage value

2023-05-26 07:20 UTC, adamskrodzki commented on components/AppContext.ts
> +    chainIdToRpcUrl[NetworkIds.MAINNET] = getTenderlyRpcUrl(tenderlySecret)
what do you mean? that is a place where `chainIdToRpcUrl ` is being created
do you want me to extract those 2 lines to a function ? i think that's overshooting

2023-05-26 07:20 UTC, adamskrodzki commented on helpers/useFeatureToggle.ts
> +export function useLocalSetting(setting: Setting): string {
done

2023-05-26 07:24 UTC, adamskrodzki commented on .env
> +TENDERLY_FORK_ID=b12b2b04-f54b-11ed-a05b-0242ac120003
I do not understand this comment

2023-05-29 09:02 UTC, merged