🧬 Oasis Create table
OasisDEX/oasis-borrow pull request #2292
Opened 2023-05-18 11:52 UTC by piotrkonowrocki

# Oasis Create table

Covers:
https://app.shortcut.com/oazo-apps/story/9002/update-assets-table-layout
https://app.shortcut.com/oazo-apps/story/8915/update-filter-dropdown
https://app.shortcut.com/oazo-apps/story/8918/add-filtering-for-oasis-create

This PR in reality is smaller than it seems. Some of the changes are new svg files or edits to existing ones and there is also a 400 lines file `oasisCreate/data.ts` that contains dummy data as a source for the table, that should be removed in the future and replaced with API call.

![image](https://github.com/OasisDEX/oasis-borrow/assets/16230404/8863de6e-9bd7-4b86-88a7-2e69646a8494)
  
## Changes 👷‍♀️

- Renamed `DiscoverMultiselect` to `GenericMultiselect`, updated its design and extended functionality - for some reason Github is showing entire file as new 😒,
- updated design of `AssetsTable` and its dependencies to match new layout,
- updated design of `GenericSelect` external plugin wrapper,
- updated design of `HeaderSelector`,
- redid some of Discover filters to make them more generic and usable also on Oasis Create page,
- changed layout background for Discover and owner's page,
- updated `WithArrow` component so it uses `span` instead of `div` and we can get rid of constant error messages in console about using `div` as a children of `p`,
   
## How to test 🧪

### Before you start testing:
- turn on `OasisCreate` feature flag,
- data is the table is fake, but filtering works,
- for the purpose of sorting, n/a means 0.

### Oasis Create page
Address of this page is changing dynamically, so you can reach it by different routes:
- `oasis-create/borrow`
- `oasis-create/multiply/WBTC`
of course, the final product is going to be available as oasis.app/multiply/WBTC

### Owner's page
This page design changed along with table update, please take a look if you're okay with how it looks in new design and if I need to change something. couple addresses with diversified portfolio for testing:
- `/owner/0xd0612c759fC6C512B7C3abceB2366C4f4096451C`.
- `/owner/0x165d0df29d9262f8ee9e9874c906eab706a05c2c`.
- `/owner/0x10649c79428d718621821Cf6299e91920284743F`.

2023-05-19 10:02 UTC, piekczyk requested changes

2023-05-19 12:54 UTC, piotrkonowrocki commented on features/discover/layout.tsx
> +export const discoverPageLayout = ({ children }: WithChildren) => (
Fixed.

2023-05-19 12:54 UTC, piotrkonowrocki commented on pages/oasis-create/[...slug].tsx
> +          .flat()
Fixed.

2023-05-19 12:54 UTC, piotrkonowrocki commented on features/oasisCreate/views/OasisCreateView.tsx
> +            content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis lorem in feugiat mattis."
Fixed.

2023-05-22 08:43 UTC, marcinciarka submitted a review, later dismissed

2023-05-22 08:43 UTC, marcinciarka commented on components/GenericMultiselect.tsx
> +    </>
Unnecessary fragment.

2023-05-22 08:43 UTC, marcinciarka commented on components/GenericMultiselect.tsx
> +            {icon && <Icon name={icon} size={32} sx={{ flexShrink: 0, mr: '12px' }} />}
If this is 32px, it should be "32px"

2023-05-22 09:10 UTC, piotrkonowrocki commented on components/GenericMultiselect.tsx
> +            {icon && <Icon name={icon} size={32} sx={{ flexShrink: 0, mr: '12px' }} />}
`size` expects `number`

2023-05-22 09:31 UTC, marcinciarka approved these changes

2023-05-22 09:48 UTC, piekczyk approved these changes

2023-05-22 09:51 UTC, merged