Show the protection on the portfolio page for Aave v3 mainnet
OasisDEX/oasis-borrow pull request #2516
Opened 2023-07-11 14:59 UTC by marcinciarka

# [Show the protection on the portfolio page for Aave v3 mainnet](https://app.shortcut.com/oazo-apps/story/10245/show-the-protection-on-the-portfolio-page-for-aave-v3-mainnet)
  
## Changes 👷‍♀️
- theres a Protection column in the _new_ owner table
- if position is protected theres a green shield
- if not, theres a button (label/pill) with available action or info (if youre not the owner)
  
## How to test 🧪
- go to your positions

2023-07-12 06:38 UTC, piekczyk requested changes

2023-07-12 06:38 UTC, piekczyk commented on features/vaultsOverview/helpers.tsx
> +  return stopLossData
in that case if stopLossData is missing we will bypass checks for autoSellData and always return zero

2023-07-12 06:38 UTC, piekczyk commented on features/vaultsOverview/helpers.tsx
> +  return stopLossData
at first glance something like this should do the job 
```
   stopLossData?.stopLossLevel.gt(zero)
      ? stopLossData.stopLossLevel.times(100)
      : autoSellData?.execCollRatio.gt(zero)
      ? autoSellData.execCollRatio
      : zero
```

2023-07-12 06:38 UTC, piekczyk commented on features/vaultsOverview/pipes/positions.ts
> +  autoSellData?: AutoBSTriggerData // this is just for type safety in positioins table, its not happening right now
typo in `positions`

2023-07-26 11:36 UTC, marcinciarka commented on features/vaultsOverview/helpers.tsx
> +  return stopLossData
Great catch dude.

2023-07-26 11:37 UTC, marcinciarka commented on features/vaultsOverview/pipes/positions.ts
> +  autoSellData?: AutoBSTriggerData // this is just for type safety in positioins table, its not happening right now
Fixde.

2023-07-27 08:57 UTC, piekczyk approved these changes

2023-07-27 08:59 UTC, merged