Mixpanel tracking for DSR
OasisDEX/oasis-borrow pull request #2598
Opened 2023-07-21 15:32 UTC by marcinciarka

# [Mixpanel tracking for DSR](https://app.shortcut.com/oazo-apps/story/9539/mixpanel-tracking-for-dsr)
  
## Changes 👷‍♀️
- implemented mixpanel tracking for DSR input and depositing

2023-07-24 08:07 UTC, piekczyk requested changes

2023-07-24 08:07 UTC, piekczyk commented on analytics/analytics.ts
> +  OpenPosition = 'OpenPosition',
shouldn't we use here just `Form` as OpenPosition is rather a page-like thing?

2023-07-24 08:07 UTC, piekczyk commented on features/dsr/helpers/dsrDeposit.tsx
> +    trackingEvents.daiSavingsRate(EventTypes.ButtonClick, {
I would distinguish between deposit and withdraw events using additional key in event payload, for example`action: 'deposit' | 'withdraw'`

2023-07-24 08:07 UTC, piekczyk commented on features/dsr/utils/formUtils.tsx
> +    if (amount) {
There was a requirement to track input? It may generate spam of events which IMO are meaningless until user actually send tx.

2023-07-24 14:27 UTC, marcinciarka commented on analytics/analytics.ts
> +  OpenPosition = 'OpenPosition',
Changed that.

2023-07-24 14:27 UTC, marcinciarka commented on features/dsr/helpers/dsrDeposit.tsx
> +    trackingEvents.daiSavingsRate(EventTypes.ButtonClick, {
Added that.

2023-07-24 14:27 UTC, marcinciarka commented on features/dsr/utils/formUtils.tsx
> +    if (amount) {
Product team wants it (doesn't see this as an issue).

2023-07-24 14:34 UTC, piekczyk submitted a review, later dismissed

2023-07-24 14:43 UTC, piekczyk approved these changes

2023-07-25 08:37 UTC, jakubswierczek approved these changes

2023-07-25 08:46 UTC, merged