Pk/pool finder form
OasisDEX/oasis-borrow pull request #2699
Opened 2023-08-10 14:10 UTC by piotrkonowrocki

# [Pool finder search form](https://app.shortcut.com/oazo-apps/story/10884/pool-finder-search-form)

![image](https://github.com/OasisDEX/oasis-borrow/assets/16230404/ade6d388-6e10-484d-a7b7-48fec765dfb5)
  
## Changes 👷‍♀️

- Created form controller and components for pool finder.
  
## How to test 🧪

Turn on `AjnaPoolFinder` feature flag, go to `/ajna/pool-finder` and try looking for some tokens.

## Stuff left to do 📝

- Searching by token symbol,
- nicer error messages,
- copy updates.

2023-08-10 14:44 UTC, piekczyk requested changes

2023-08-10 14:44 UTC, piekczyk commented on features/poolFinder/controls/PoolFinderFormController.tsx
> +          onClick={() => {
I'm confused by this part, could you elaborate why assigning to consts is necessary?

2023-08-11 08:56 UTC, piotrkonowrocki commented on features/poolFinder/controls/PoolFinderFormController.tsx
> +          onClick={() => {
Because if I do
```
setCollateralAddress(quoteAddress)
setQuoteAddress(collateralAddress)
```
at the moment when I'm updating quote address to collateral address, the collateral address might be already at the value of quote address. Both vars are cached so there's no mismatch between their states.

2023-08-11 09:56 UTC, piekczyk approved these changes

2023-08-11 10:00 UTC, merged