Piter/sc-10844/frontend-handle-claiming-of-the-referrals
OasisDEX/oasis-borrow pull request #2725
Opened 2023-08-17 14:30 UTC by piotrwitek

[Shortcut Story #10844: [frontend] - handle claiming of the referrals](https://app.shortcut.com/oazo-apps/story/10844/frontend-handle-claiming-of-the-referrals).

## Changes 👷‍♀️
Implemented a new claim mechanism for referral rewards. Now users will claim all accumulated rewards on the optimism network. Previously claimed rewards was taken from the cache api, now we will use a dedicated subgraph that will be tracking processed fees and claimed rewards.

There is a corresponding PR created in the library repo to update their redeemer contract address on the optimism network: https://github.com/OasisDEX/oasis-earn-sc/pull/422

2023-08-18 09:01 UTC, piotrkonowrocki requested changes

2023-08-18 09:47 UTC, piotrwitek commented on .env
> +REFERRAL_SUBGRAPH_URL="referral subgraph that calculate reward claims"
oh yes, thx

2023-08-18 09:50 UTC, piotrwitek commented on .env
> +REFERRAL_SUBGRAPH_URL="referral subgraph that calculate reward claims"
This env should setup an url to the new subgraph node, seem required to me

2023-08-18 09:51 UTC, piotrwitek commented on .env
> +REFERRAL_SUBGRAPH_URL="referral subgraph that calculate reward claims"
Or perhaps explain to me how are you setting up this env: AJNA_SUBGRAPH_URL

2023-08-18 09:53 UTC, piotrwitek commented on blockchain/calls/merkleRedeemer.ts
> +    // Claims are on the optimism only
You're assumption is correct it will prompt you to switch network to optimism if that's something different and only then execute the claim

2023-08-18 09:54 UTC, piotrwitek commented on blockchain/calls/merkleRedeemer.ts
> +    // Claims are on the optimism only
It will be implemented in the separate pr

2023-08-18 09:56 UTC, piotrwitek commented on features/referralOverview/user.ts
> +import { getClaimedReferralRewards } from './getClaimedReferralRewards'
gotcha

2023-08-18 10:01 UTC, piotrwitek commented on features/referralOverview/user.ts
> +import { getClaimedReferralRewards } from './getClaimedReferralRewards'
Normally you should treat it as an internal module of a feature so in my opinion it doesn't make sense to use absolute imports As it is not intended to be used outside of that feature. But if that's the convention that you set up across the board than I will align with that in the future.

2023-08-18 11:06 UTC, piotrkonowrocki commented on blockchain/calls/merkleRedeemer.ts
> +    // Claims are on the optimism only
Does it mean that until that time we're going to be blocked on potential prod release, so we don't release a page that isn't working on mainnet? Or is it somehow behind feature flag and won't affect users on prod?

2023-08-18 11:07 UTC, piotrkonowrocki commented on features/referralOverview/user.ts
> +import { getClaimedReferralRewards } from './getClaimedReferralRewards'
Yeah, it's about convention. Some time ago we decided to use absolute imports as a baseline. If there are relative imports, it's because it was overlooked during review.

The only place we are using relative imports are `index` files for exports.

2023-08-18 11:26 UTC, piotrwitek commented on blockchain/calls/merkleRedeemer.ts
> +    // Claims are on the optimism only
this is valid concern, however it shouldn't block because I'll have other pr ready today and merge it to this pr and only then merge the full work
this way review process is easier for reviewers and faster (because of the smaller prs)

2023-08-18 11:27 UTC, piotrwitek commented on features/referralOverview/user.ts
> +import { getClaimedReferralRewards } from './getClaimedReferralRewards'
ok good I'm fixing that

2023-08-18 11:33 UTC, piotrwitek commented on blockchain/calls/merkleRedeemer.ts
> +    // Claims are on the optimism only
Regarding the feature flag it's actually not needed because that's not a new feature but an upgrade of an existing feature and Old functionality will not be usable anymore

2023-08-18 11:35 UTC, piotrwitek commented on .env
> +REFERRAL_SUBGRAPH_URL="referral subgraph that calculate reward claims"
In my opinion that's necessary because we don't have a template so it's impossible to discover which secrets we need to set up locally and it's a problem I encountered as a newbie To the project

2023-08-18 11:42 UTC, piotrkonowrocki approved these changes

2023-08-21 17:10 UTC, marcinciarka commented on features/referralOverview/referral-claim-switch-network-modal.tsx
> +        </Flex>{' '}
Probably not needed.

2023-08-21 17:11 UTC, marcinciarka commented on features/referralOverview/user.ts
> +          ) as number[]
Unnecessary type assertion.

2023-08-21 17:17 UTC, marcinciarka submitted a review, later dismissed

2023-08-22 04:55 UTC, piotrwitek commented on features/referralOverview/referral-claim-switch-network-modal.tsx
> +        </Flex>{' '}
Fixed thx

2023-08-22 04:56 UTC, piotrwitek commented on features/referralOverview/user.ts
> +          ) as number[]
100% 👍

2023-08-22 05:48 UTC, jakubswierczek approved these changes

2023-08-22 06:19 UTC, piekczyk approved these changes

2023-08-22 06:23 UTC, merged