Extends Ajna borrow with close feature [sc-11316]
OasisDEX/oasis-borrow pull request #2808
Opened 2023-08-29 11:32 UTC by paszkowskiDamian

# [Close action on ajna borrow](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2023-08-30 10:49 UTC, piotrkonowrocki requested changes

2023-08-30 10:49 UTC, piotrkonowrocki commented on actions/ajna/multiply.ts
> +export const ajnaAdjust = ({
Since this is no longer multiply action, is should be moved into `actions/ajna/common.ts` file (which does not exist right now.

2023-08-30 10:49 UTC, piotrkonowrocki commented on actions/ajna/multiply.ts
> +export const ajnaClose = ({
Same as with `ajnaAdjust`.

2023-08-30 10:49 UTC, piotrkonowrocki commented on features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentClose.tsx
> +  if (product === 'earn') {
I think this condition is no longer needed and it's probably leftover from early development stages? Since `useAjnaProductContext('borrow')` is pointing directly to `borrow` product type, `earn` will never show in here.

2023-08-30 10:49 UTC, piotrkonowrocki commented on features/ajna/positions/common/components/AjnaAdjustSlider.tsx
> +    return null
How about throwing an error similar to what we have in `useAjnaProductContext`, instead of returning `null`? Might be easier to debug with `throw new Error`.

2023-09-01 09:58 UTC, piotrkonowrocki approved these changes

2023-09-01 10:41 UTC, piotrwitek approved these changes

2023-09-01 14:29 UTC, merged