Move marketing pages to Borrow
OasisDEX/oasis-borrow pull request #286
Opened 2021-07-02 04:32 UTC by ferni

# [Move marketing pages to Borrow](https://app.clubhouse.io/oazo-apps/story/2117/moving-marketing-pages-to-borrow)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- Imported pages: privacy, support, about, careers, careers/[slug] (the terms page was already imported).
- Added some entries to the theme file.
- Updated footer links.
  
## How to test 🧪
  <Please explain how to test your changes>

- Check out the pages.
- In order to see the careers page with mocked careers, revert this commit locally: 4bf77bb
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [x] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-07-02 09:38 UTC, pacxiu commented
Images doesn't seem to load for the team page - I think there is some helper function for linking static files, as we have this `/borrow` added to some paths.
![image](https://user-images.githubusercontent.com/19193499/124254983-f4ac3280-db29-11eb-937c-9df8bf865357.png)

2021-07-02 10:18 UTC, pacxiu requested changes

2021-07-02 10:18 UTC, pacxiu commented on features/landing/LandingView.tsx
> +      <Heading as="h1" variant="header1s" sx={{ mb: 3 }}>
I think this variant could be renamed to `header1Marketing` `s` doesn't provide much context about variant

2021-07-02 10:18 UTC, pacxiu commented on pages/about.tsx
> +        <Text variant="paragraph1" sx={{ color: 'text.focused', fontWeight: 600 }}>
600 could be swapped to `semiBold`

2021-07-02 10:18 UTC, pacxiu commented on pages/careers/[slug].tsx
> +        <Icon name="arrow_left" size="16px" sx={{ mr: 1 }} />
`size` could be `3` isntead of `16px`

2021-07-02 10:18 UTC, pacxiu commented on pages/careers/[slug].tsx
> +        <Text variant="paragraph2" sx={{ color: 'text.focused', fontWeight: 600 }}>
600 could be swapped to `semiBold`

2021-07-02 10:18 UTC, pacxiu commented on pages/careers/[slug].tsx
> +              fontWeight: 600,
600 could be swapped to `semiBold`

2021-07-02 10:18 UTC, pacxiu commented on pages/careers/[slug].tsx
> +            fontWeight: 400,
600 could be swapped to `normal`

2021-07-02 10:18 UTC, pacxiu commented on pages/careers/index.tsx
> +        borderRadius: '13px',
I would use design roken which is the closest here, I believe we have one for `12px`

2021-07-02 10:18 UTC, pacxiu commented on pages/careers/index.tsx
> +      <Text sx={{ fontSize: 1, fontWeight: 600, color: '#FFF' }}>{count}</Text>
600 could be swapped to `semiBold` and `#FFF` also with corresponding color token

2021-07-02 10:18 UTC, pacxiu commented on components/Layouts.tsx
> +  topBackground?: 'default' | 'light' | 'lighter' | 'none'
I think you could type it `keyof typeof marketingBackgrounds` so you don't have to update those 2 together

2021-07-05 17:33 UTC, ferni commented on features/content/privacy/es.mdx
> +*Última actualización: 2 de noviembre de 2020*
I think the translations would fall out of scope of this PR, its purpose is just to move the pages, but yeah I can ask if you want.

2021-07-05 18:30 UTC, ferni commented on features/landing/LandingView.tsx
> +      <Heading as="h1" variant="header1s" sx={{ mb: 3 }}>
I did a search and "header1" was not being used. I replaced it so "header1s" is now just "header1".

2021-07-05 18:36 UTC, ferni commented on components/Layouts.tsx
> +  topBackground?: 'default' | 'light' | 'lighter' | 'none'
Oh neat!

2021-07-06 06:29 UTC, pacxiu approved these changes

2021-07-06 06:29 UTC, merged