🔧 [AWS JSON config] Implement the new JSON configs in oasis-borrow
OasisDEX/oasis-borrow pull request #2865
Opened 2023-09-11 15:52 UTC by marcinciarka

TBD

2023-09-14 07:23 UTC, piekczyk requested changes

2023-09-14 07:23 UTC, piekczyk commented on helpers/config/access-config-context.ts
> +export function getAppConfigSync<T extends ConfigResponseTypeKey>(
maybe `getLocalAppConfig`? When I first saw this method in code I thought it's for forcing re-sync of config from AWS

2023-09-14 07:42 UTC, jakubswierczek requested changes

2023-09-14 07:42 UTC, jakubswierczek commented on components/context/ConfigContextProvider.tsx
> +    void setup()
please add here `catch`

2023-09-14 07:42 UTC, jakubswierczek commented on components/context/ConfigContextProvider.tsx
> +    method: 'POST',
why `POST` ? we don't save anything, we just want to obtain the data. We should use `GET`

2023-09-14 07:42 UTC, jakubswierczek commented on handlers/config/index.ts
> +export const configHandler = cacheObject<Record<string, string>>(
I don't know if we want to have cache for it. 
I think in first iteration we can use it without caching.

2023-09-14 07:42 UTC, jakubswierczek commented on pages/api/config.ts
> +  if (method === 'POST') {
please use `GET` and cache header without caching in memory

2023-09-14 11:20 UTC, jakubswierczek approved these changes

2023-09-14 12:47 UTC, piekczyk submitted a review, later dismissed

2023-09-14 13:40 UTC, jakubswierczek approved these changes

2023-09-14 13:40 UTC, jakubswierczek commented on features/borrow/open/tests/openVault.test.ts
> +jest.mock('helpers/config', () => ({
❤️

2023-09-14 13:50 UTC, piekczyk approved these changes

2023-09-15 08:02 UTC, jakubswierczek approved these changes

2023-09-15 08:02 UTC, merged