feat: [sc-11917] [Frontend/Library] Issues with flashloans
OasisDEX/oasis-borrow pull request #2878
Opened 2023-09-14 20:17 UTC by jakubswierczek

Story details: https://app.shortcut.com/oazo-apps/story/11917

2023-09-18 15:32 UTC, marcinciarka approved these changes

2023-09-19 08:16 UTC, piekczyk requested changes

2023-09-19 08:16 UTC, piekczyk commented on features/aave/components/order-information/FlashLoanInformation.tsx
> +            <Text>
add semantics, `as="p"` or `as="span"` or something

2023-09-19 08:16 UTC, piekczyk commented on features/aave/components/order-information/FlashLoanInformation.tsx
> +            <Text color={liquidityColor} sx={{ ml: 2 }}>
add semantics, `as="p"` or `as="span"` or something

2023-09-19 08:16 UTC, piekczyk commented on helpers/hooks/useBalancerLiquidity.ts
> +  // const cache = useRef(zero)
to be removed

2023-09-19 09:11 UTC, piekczyk approved these changes

2023-09-19 09:15 UTC, merged