Package updates + lifi widget config update
OasisDEX/oasis-borrow pull request #2892
Opened 2023-09-18 12:30 UTC by marcinciarka

# Package chores

  
## Changes 👷‍♀️
- Updated next
- removed @next/font
- updated web3-onboard
- ramda has to be transpiled
- updated lifi widget and [its config](https://app.shortcut.com/oazo-apps/story/11898/update-config-for-lifi-swap) 
- node 18 yay

## How to test 🧪
- app should work as before (a bit faster?)

2023-09-18 12:37 UTC, jakubswierczek submitted a review, later dismissed

2023-09-20 13:29 UTC, piotrwitek requested changes

2023-09-20 13:29 UTC, piotrwitek commented on test-configs/setup.ts
> +import '@inrupt/jest-jsdom-polyfills'
Could you leave a comment please for history why this was added?

2023-09-20 13:46 UTC, marcinciarka commented on test-configs/setup.ts
> +import '@inrupt/jest-jsdom-polyfills'
@jakubswierczek ⬆️

2023-09-24 11:34 UTC, jakubswierczek commented on test-configs/setup.ts
> +import '@inrupt/jest-jsdom-polyfills'
Some libraries are using certain parts of the Web API that do not appear in jsdom (which is used in the Jest framework). 

Error:
```
ReferenceError: TextEncoder is not defined
```

As a result, some of the tests are skipped, but we can enable that now (in the follow up). 

Polyfills can resolve this issue.

2023-09-24 11:34 UTC, jakubswierczek approved these changes

2023-09-26 09:05 UTC, piotrwitek approved these changes
looks great 🐸

2023-09-26 09:07 UTC, merged