🔧 fix(spark stop-loss): Fix remaining issues with spark stop loss
OasisDEX/oasis-borrow pull request #2923
Opened 2023-09-27 11:13 UTC by BackToTheCode

# [🔧 fix(spark stop-loss): Fix remaining issues with spark stop loss](https://app.shortcut.com/oazo-apps/story/11987/spark-stop-loss-finish-up)

## Changes 👷‍♀️
- Fix coverage issue for Spark Stop Loss
  
## How to test 🧪
- `yarn test`

2023-09-27 11:45 UTC, piotrwitek requested changes

2023-09-27 11:45 UTC, piotrwitek commented on features/automation/protection/stopLoss/state/stopLossTriggerData.ts
> +    TriggerType.SparkStopLossToCollateralV2
@BackToTheCode Did you miss the comparison here for `TriggerType.SparkStopLossToCollateralV2`?

2023-09-27 11:45 UTC, piotrwitek commented on scripts/docker/compose.yml
> +#      - '../.hardhat/cache:/usr/src/mpa/cache'
Is this intended? as it looks to me like out of the scope of the fix

2023-09-27 12:10 UTC, BackToTheCode commented on scripts/docker/compose.yml
> +#      - '../.hardhat/cache:/usr/src/mpa/cache'
TY. Not intended at all

2023-09-27 12:11 UTC, BackToTheCode commented on features/automation/protection/stopLoss/state/stopLossTriggerData.ts
> +    TriggerType.SparkStopLossToCollateralV2
I did. TY :)

2023-09-28 10:34 UTC, piotrwitek approved these changes

2023-10-09 08:23 UTC, merged