Morpho blue UI
OasisDEX/oasis-borrow pull request #2984
Opened 2023-10-16 15:11 UTC by piekczyk

# Morpho blue UI

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2023-10-18 15:28 UTC, piotrwitek commented
> Moving @paszkowskiDamian comment from the closed PR: As we are trying to come up with a standard for handling lending protocols. What do you think about this crazy idea to forget about `borrow | multiply` positions. How about having a position (probably it would be just current multiplyPosition), as the multiply is just `Summer.fi` name and does not have any influence how the position looks like from the blockchain perspective. The difference would be that the details section and some labels in form. Especially when product wants to add all multiply features to borrow it makes it easer to maintain just one state. @piekczyk @piotrwitek @piotrkonowrocki ?

I think we should have a `BasePosition` interface that all other specialized positions inherit from and just add differences on top.
I don`t understand why we have IAjnaEarn and IAjnaPosition which are both very similar and shuould inherit from a common ancestor and be a BasePosition specializations instead

2023-10-18 15:35 UTC, piotrwitek commented
My Proposal:
1) extract common props from IAjnaEarn and IAjnaPosition to IPosition
2) refactor IAjnaEarn and IAjnaPosition to extend IPosition and rename according to specialization e.g. IEarnPosition

2023-10-18 17:06 UTC, piekczyk commented
> > Moving @paszkowskiDamian comment from the closed PR: As we are trying to come up with a standard for handling lending protocols. What do you think about this crazy idea to forget about `borrow | multiply` positions. How about having a position (probably it would be just current multiplyPosition), as the multiply is just `Summer.fi` name and does not have any influence how the position looks like from the blockchain perspective. The difference would be that the details section and some labels in form. Especially when product wants to add all multiply features to borrow it makes it easer to maintain just one state. @piekczyk @piotrwitek @piotrkonowrocki ?
> 
> I think we could have an `IPosition` interface that all other specialized positions inherit from and just add differences on top. we have IAjnaEarn and IAjnaPosition which are both very similar and shuould inherit from a common ancestor IPosition and become specializations instead.
> 
> Added this proposal in the library PR

I think borrow / multiply position interface shouldn't be mixed up with earn. I created BorrowishPosition interface in lib with idea to use it both for borrow / multiply stuff.

2023-10-18 17:09 UTC, piotrwitek commented
> I think borrow / multiply position interface shouldn't be mixed up with earn. I created BorrowishPosition interface in lib with idea to use it both for borrow / multiply stuff. Here is draft PR in lib library: https://github.com/OasisDEX/oasis-earn-sc/pull/498/files

Why you think it shouldn't be "mixed up", please clarify...

2023-10-18 17:28 UTC, piekczyk commented
> > I think borrow / multiply position interface shouldn't be mixed up with earn. I created BorrowishPosition interface in lib with idea to use it both for borrow / multiply stuff. Here is draft PR in lib library: https://github.com/OasisDEX/oasis-earn-sc/pull/498/files
> 
> @piekczyk Why you think it shouldn't be "mixed up" with earn, please clarify...

Earn products are very specific and vary a lot from product to product not mentioning the differences between protocols (take Ajna Earn vs everything as example). In the other hand borrow / multiply is more or less the same everywhere. That is why we still didn't entirely figure out the dependency injection for Earn product and we are leaving it as last bit since Morpho won't have Earn product at the launch. Omni Earn interface most likely will be limited to very narrow scope (for example quoteToken / token pairs, apy values, pnl,  deposit / withdraw actions) and the rest will be fully configurable & handled through metadata.

2023-10-18 18:30 UTC, piotrwitek commented
> > > I think borrow / multiply position interface shouldn't be mixed up with earn. I created BorrowishPosition interface in lib with idea to use it both for borrow / multiply stuff. Here is draft PR in lib library: https://github.com/OasisDEX/oasis-earn-sc/pull/498/files
> > 
> > 
> > @piekczyk Why you think it shouldn't be "mixed up" with earn, please clarify...
> 
> Earn products are very specific and vary a lot from product to product not mentioning the differences between protocols (take Ajna Earn vs everything as example). In the other hand borrow / multiply is more or less the same everywhere. That is why we still didn't entirely figure out the dependency injection for Earn product and we are leaving it as last bit since Morpho won't have Earn product at the launch. Omni Earn interface most likely will be limited to very narrow scope (for example quoteToken / token pairs, apy values, pnl, deposit / withdraw actions) and the rest will be fully configurable & handled through metadata.

@piekczyk Thanks for clarification. what you written makes sense for the product interface, but I thought we're discussing Position interface...
Could you elaborate on that, why are you referring to a Product entity instead of position?

2023-10-18 19:31 UTC, piotrwitek commented on features/morpho/common/layout.tsx
> +export function MorphoLayout({ children }: WithChildren) {
this layout could be generalized

2023-10-26 09:05 UTC, jakubswierczek requested changes
General comments:

Great work, but the code isn't proving anything. We don't have tests here, which (in my opinion) is a crucial thing to have confidence in implementing a new protocol. Without tests and very big files, the implementation will be a pain in the ass.
Like I mentioned before, creating a context for Borrow and Multiply isn't a good idea. We have evidence that even in Maker, it's sufficient to have only one set of pipelines because the actions remain the same.

2023-10-26 09:09 UTC, jakubswierczek commented
> > > Moving @paszkowskiDamian comment from the closed PR: As we are trying to come up with a standard for handling lending protocols. What do you think about this crazy idea to forget about `borrow | multiply` positions. How about having a position (probably it would be just current multiplyPosition), as the multiply is just `Summer.fi` name and does not have any influence how the position looks like from the blockchain perspective. The difference would be that the details section and some labels in form. Especially when product wants to add all multiply features to borrow it makes it easer to maintain just one state. @piekczyk @piotrwitek @piotrkonowrocki ?
> > 
> > 
> > I think we could have an `IPosition` interface that all other specialized positions inherit from and just add differences on top. we have IAjnaEarn and IAjnaPosition which are both very similar and shuould inherit from a common ancestor IPosition and become specializations instead.
> > Added this proposal in the library PR
> 
> I think borrow / multiply position interface shouldn't be mixed up with earn. I created BorrowishPosition interface in lib with idea to use it both for borrow / multiply stuff. Here is draft PR in lib library: https://github.com/OasisDEX/oasis-earn-sc/pull/498/files

But you're mixing up two different things. - Yields Loops are Multiply positions, only Supply positions like `DSR` don't have the same functionality. From other hand - In Aave/Spark switching from Supply to Lend it's a one action and can be done within one position.

2023-10-26 09:09 UTC, jakubswierczek commented
What do we need to do to support multi collateral positions in this generalisation?

2023-10-26 09:36 UTC, piekczyk commented
> What do we need to do to support multi collateral positions in this generalisation?

Currently nothing as it's not something that is currently supported in app, we can't do everything at once. When the time for multi collateral positions will come, for sure we will need to make a lot of changes to support that, but it's something to research and develop once all requirements are defined and clear.

2023-10-26 09:49 UTC, piekczyk commented on features/omni-kit/views/OmniFormView.tsx
> +  return (
Agree, but it's hard to split code since a tons of parameters are required. I could extract some parts of logic from this file to custom hook, but then this new hook will be enormously big. The good thing is, that this particular view component is reused everywhere and in general shouldn't be a subject of changes. So to sum up, if you don't mind I would leave it as it is.

2023-10-26 10:01 UTC, piekczyk commented on features/omni-kit/state/omniFormReductoActions.ts
> +  paybackAmountUSD?: BigNumber
The question shouldn't be about the passing it somewhere but rather where to perform the calculations. For example here it's done while updating state in reducto, so `paybackAmountUSD` is eventually available everywhere on UI without need to calculate it locally within components which uses it. 

Imagine that you have 5 different UI components that displays payback amount in USD. If we won't have it stored within reducer we would need to calculate it 5x times on the UI, or calculate it on parent level and pass as props assuming that these have common parent.

2023-10-26 10:02 UTC, piekczyk commented on features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
> +              // TODO to be defined
there is entire epic which will cover integration :)

2023-10-26 10:06 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardLiquidationPriceV2.tsx
> +  quoteToken: string
I prefer using quote instead of debt and I think all places in omni kit are using that name except maybe couple labels for users. Quote is more universal as it works for both borrow and earn type of products, but debt doesn't make sense for earn as you are not depositing debt.

2023-10-26 10:07 UTC, paszkowskiDamian commented on actions/ajna/getAjnaOmniParameters.ts
> +  const defaultPromise = Promise.resolve(undefined)
you may just return `undefined` in default.

2023-10-26 10:08 UTC, piotrkonowrocki commented on components/vault/detailsSection/ContentCardNetBorrowCost.tsx
> +              debtToken: quoteToken,
Naming is consistent, the problem here is using aave translations which uses `debtToken` as a name, but I think there is a TODO somewhere about it and you commented about creating a story for it.

2023-10-26 10:09 UTC, piotrkonowrocki commented on features/aave/components/AaveBorrowPositionData.tsx
> +import { useAutomationContext } from 'components/context/AutomationContextProvider'
Unrelated to OmniKit, should be reported as separated story to refactor file structure and index files for automation.

2023-10-26 10:11 UTC, piotrkonowrocki commented on features/aave/components/AaveBorrowPositionData.tsx
> +              quotePrice={debtTokenPrice}
See https://github.com/OasisDEX/oasis-borrow/pull/2984#discussion_r1372918663

2023-10-26 10:15 UTC, piekczyk commented
> General comments:
> 
> Great work, but the code isn't proving anything. We don't have tests here, which (in my opinion) is a crucial thing to have confidence in implementing a new protocol. Without tests and very big files, the implementation will be a pain in the ass. Like I mentioned before, creating a context for Borrow and Multiply isn't a good idea. We have evidence that even in Maker, it's sufficient to have only one set of pipelines because the actions remain the same.

Agree that code for now isn't proving anything, omni-kit will be battle tested in ajna relaunch epic and morpho. Regarding tests - what kind of tests do you think of? For sure we should have unit tests, when it comes to protocol specific things I think the crucial part would be to have tests within library. On UI it would be nice to have integration tests but as you probably know it's not that simple and definitely time consuming. Regarding last bit, omni-kit underneath uses the same actions and logic for handling actions from borrow and multiply, so it's completely different to what we had in maker.

2023-10-26 10:15 UTC, piotrkonowrocki commented on features/omni-kit/contexts/OmniGeneralContext.tsx
> +  collateralPrecision: number
`collateralPrecision` is token precision of token's contract, `collateralDigits` is amount of decimal places for token. Weird, but out internal token configuration has that already and this omni config had to mimic it for the purpose of oracless mode where we're not relying on internal config, but on external data.

2023-10-26 10:19 UTC, piotrkonowrocki commented on features/omni-kit/state/omniFormReductoActions.ts
> +  paybackAmountUSD?: BigNumber
It's not a value for just displaying, but a part of form with text fields that allow data input directly in USD. That's why we are keeping it separately, so we can store user's direct input.

2023-10-26 10:43 UTC, piekczyk commented on components/vault/detailsSection/ContentCardLiquidationPriceV2.tsx
> +    // TODO remove aave from translations keys as this card may be common for different protocols
created https://app.shortcut.com/oazo-apps/story/12461/omni-kit-translations

2023-10-26 12:37 UTC, piotrkonowrocki commented on actions/ajna/getAjnaOmniParameters.ts
> +    case 'payback-multiply':
Done.

2023-10-26 12:42 UTC, piotrkonowrocki commented on actions/ajna/getAjnaOmniParameters.ts
> +  context: Context
Removed from interface.

2023-10-26 12:44 UTC, piotrkonowrocki commented on actions/ajna/getAjnaOmniParameters.ts
> +    network: 'mainnet' as Network,
Replaced with direct usage of `Network` enum.

2023-10-26 12:50 UTC, piotrkonowrocki commented on features/ajna/positions/common/hooks/useTransition.ts
> +    productType === 'borrow'
We do, but in `useOmniTransition` file - this one is from Ajna legacy implementation which is going to be removed. The only reason it's listed as one of the changes is because there was global ajna/omni rename from `product` to `productType`.

2023-10-26 12:52 UTC, piotrkonowrocki commented on features/ajna/positions/common/notifications.tsx
>      case 'multiply':
Like before 😅
`getAjnaOmniNotifications` is using enum, this one is from Ajna legacy.

2023-10-26 12:57 UTC, piekczyk commented on features/omni-kit/protocols/morpho-blue/hooks/useMorphoOmniData.ts
> +  // const { context$ } = useMainContext()
done

2023-10-26 12:59 UTC, piekczyk commented on features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
> +    // @ts-ignore TODO
done

2023-10-26 12:59 UTC, piekczyk commented on features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
> +    // @ts-ignore TODO
done

2023-10-26 13:02 UTC, piekczyk commented on features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
> +  const gasEstimation = useGasEstimationContext()
Eventually yes, but right now it would be a too big change to make as whole Ajna and automations are using it.

2023-10-26 13:04 UTC, piekczyk commented on features/aave/components/AaveBorrowPositionData.tsx
> +  const {
I'm not sure what do you mean here, it's Aave component. The changes that were made here and in multiply was purely related to the UI components which were duplicated and not extracted.

2023-10-26 13:06 UTC, piekczyk commented on features/morpho/common/observables/getMorphoPosition.ts
> +export function getMorphoPosition$(
I have the same exact feeling, I don't want to changes things that were working fine on Ajna, because if we start to do so, we would end up which way to many moving parts and if something won't work as expected we won't know whether it's related to the omni-kit or other changes.

2023-10-26 13:12 UTC, piekczyk commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentPayback.tsx
> +export function OmniMultiplyFormContentPayback() {
It's a wrapper specific for multiply since UI is slightly different. We could potentially generalize it at some point but I would rather go with approach to not try hard to generalize everything in step 1.

2023-10-26 13:25 UTC, piekczyk commented on features/omni-kit/controllers/OmniProductController.tsx
> +interface OmniProductControllerProps<A, H, P> {
yes we do, there is no way to make generalization without generic arguments while a load of different data is pass through this interface depends on the product

2023-10-26 13:26 UTC, piekczyk commented on features/omni-kit/contexts/omniTxManager.ts
> +import { TxStatus } from '@oasisdex/transactions'
it would be a breaking change in compare to ajna legacy approach, we would like to avoid that in first iteration of omni-step since it will bring unnecessary chaos

2023-10-26 13:55 UTC, piotrkonowrocki commented on features/morpho/common/consts.ts
> +    open: ['setup', 'dpm', 'transaction'],
Done.

2023-10-26 14:07 UTC, piotrkonowrocki commented on features/morpho/positions/common/getMorphoSidebarTitle.tsx
> +export const getMorphoSidebarTitle = ({
Done.

2023-10-26 14:09 UTC, piotrkonowrocki commented on features/omni-kit/components/OmniDupePositionModal.tsx
> +  const type = productType === OmniProductType.Earn ? 'lender' : 'borrower'
In that case, that shouldn't be an enum. This is just a piece of string that is used later in only one place, for a translation:
```
{t(`ajna.position-page.common.dupe-modal.description-${type}-${amount}`)}
```

2023-10-26 14:11 UTC, piotrkonowrocki commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentGenerate.tsx
> +      state: { generateAmount },
It's called generate to be constant with names of actions that are returned from dma-library. For now, I would keep it as it is.

2023-10-26 14:24 UTC, piotrkonowrocki commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
> +    [
Done.

2023-10-26 14:26 UTC, piotrkonowrocki commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
> +  const formatted = {
Function that will do what? It's going to return exactly the same thing, but will require all the same params to be passed to it, so it won't improve readability at all, but add one step of complexity.

2023-10-26 14:29 UTC, piotrkonowrocki commented on features/omni-kit/helpers/getOmniSidebarButtonsStatus.ts
> +  action?: OmniFormAction
Done.

2023-10-26 14:30 UTC, piotrkonowrocki commented on features/omni-kit/helpers/isOmniFormValid.ts
> +}: {
Done.

2023-10-26 14:43 UTC, piotrkonowrocki commented on features/omni-kit/hooks/useOmniProtocolData.ts
> +  const tokensAddresses = useMemo(
Done.

2023-10-26 14:43 UTC, piotrkonowrocki commented on features/omni-kit/protocols/ajna/constants.ts
> +    open: ['risk', 'setup', 'dpm', 'transaction'],
Done.

2023-10-26 14:46 UTC, piotrkonowrocki commented on features/omni-kit/types.ts
> +  | 'open-borrow'
Done.

2023-10-26 16:13 UTC, piotrwitek requested changes
some changes requested, ping me if you need clarification

2023-10-26 16:13 UTC, piotrwitek commented on features/omni-kit/controllers/OmniProductController.tsx
> +interface OmniProductControllerProps<A, H, P> {
Could you fix the type arguments naming convention so they are readable? e.g. A => Auction
It's hard to read one-letter arguments, types should also convey semantic meaning same as variables

2023-10-26 16:13 UTC, piotrwitek commented on features/omni-kit/helpers/getOmniIsFormEmpty.ts
> +        state as OmniBorrowFormState
I agree, it can be easily implemented with the type system by introducing a wrapper type with a discriminate property which would be productType in this case. would guarantee type safety without casting and guaranteed safe usage. 
Now you can call it with error and it wont complain, e.g.:
```getOmniIsFormEmpty(OmniProductType.Borrow, omniMultiplyFormState, currentStep, txStatus)```

2023-10-27 07:10 UTC, piotrkonowrocki commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentGenerate.tsx
> +      state: { generateAmount },
1. Finite amount of time.
2. This was named as `generate` in library by one of the smart contract developers when they released dma actions for Ajna, so we reused the name assuming that they know better what actions should protocol provide.

2023-10-27 07:16 UTC, piotrkonowrocki commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
> +  const formatted = {
How is `formatted` as a object name not clear as what this object does? The component takes some external data and then in formatted object uses the same exact keys as component interface for user readable formatted values.

This is a pattern used in more than just that component, there are many instances of that in the codebase so that could be addressed as a form of tech debt, not selectively for this feature. But still - I think that name `formatted` is perfectly transparent.

2023-10-27 07:23 UTC, piotrkonowrocki commented on features/omni-kit/contexts/OmniGeneralContext.tsx
> +  collateralPrecision: number
Then it's going to be inconsistent with global token configuration that we have right now and because of time shortage I don't want to update global configs and all occurrences of its usage at this point of this feature development.

2023-10-27 07:25 UTC, piotrkonowrocki commented on features/omni-kit/contexts/omniTxManager.ts
> +import { TxStatus } from '@oasisdex/transactions'
I doubt it's going to happen next iteration. This was used in Ajna almost a year ago and was working fine, so we can consider it as a tech debt and try to address it in that process, but I wouldn't consider it as a must have as a part of feature development.

2023-10-27 07:29 UTC, piekczyk commented on features/morpho/common/layout.tsx
> +export function MorphoLayout({ children }: WithChildren) {
Good catch, it was leftover when I initially thought that Morpho will have it's own, custom theme. No need to create omni layout, we can use just `AppLayout

2023-10-27 07:37 UTC, piekczyk commented on features/omni-kit/controllers/OmniProductController.tsx
> +interface OmniProductControllerProps<A, H, P> {
done

2023-10-27 08:09 UTC, piotrwitek commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentGenerate.tsx
> +      state: { generateAmount },
@piotrkonowrocki thanks,
@jakubswierczek could you put that feedback somewhere in the backlog to request the SC team to fix that or at least comment on the rationale? so we don't loose that valuable feedback

2023-10-27 08:17 UTC, piotrwitek commented on features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
> +  const formatted = {
@piotrkonowrocki simply because it's a too generic term, so it's confusing what was the intention, and anything could be put there. 
having more specific name serve two critical purposes for clean code:
- setting a clear intention so I don't have to analyze implementation details
- documenting the code
right now when reading this I have no idea what it does until I check implementation details that's why it's failing at intention and what this object does

2023-10-27 08:19 UTC, piotrwitek commented on features/omni-kit/contexts/OmniGeneralContext.tsx
> +  collateralPrecision: number
@piotrkonowrocki isn't it just global refactor? why the hesitation? how much time it takes?

2023-10-27 08:20 UTC, piotrwitek commented on features/omni-kit/contexts/omniTxManager.ts
> +import { TxStatus } from '@oasisdex/transactions'
ok fair thanks

2023-10-27 08:21 UTC, piotrwitek commented on features/omni-kit/helpers/getOmniIsFormEmpty.ts
> +        state as OmniBorrowFormState
@piotrkonowrocki

2023-10-27 08:23 UTC, piotrwitek commented on features/morpho/common/layout.tsx
> +export function MorphoLayout({ children }: WithChildren) {
nice thx

2023-10-27 08:49 UTC, piotrwitek commented on features/omni-kit/helpers/getOmniIsFormEmpty.ts
> +        state as OmniBorrowFormState
@piekczyk  here is a ready solution:
you have this type
`export type OmniFormState = OmniBorrowFormState | OmniMultiplyFormState | OmniEarnFormState`

1) it would be easiest to add a common property type to each of these types so that you can discriminate on the basis of this Property

2. there is also a second approach where we can use a wrapper type
 this StateTypeWrapper type would have 3 possible variations defined. each variation for each of the possible states i.e. borrow / multiply / earn

```
type StateTypeWrapper = { type: OmniProductType.Borrow, state: OmniBorrowFormState } | { type: OmniProductType.Earn, state: OmniEarnFormState } | { type: OmniProductType.Multiply, state: OmniMultiplyFormState }
```

now you can use this type as a Guard in this function, you have a ready solution
and of course,  you can change the name it's just for demo purpose
```
interface GetIsFormEmptyParams {
  currentStep: OmniSidebarStep
  stateTypeWrapper: StateTypeWrapper
  txStatus?: TxStatus
}```

2023-10-27 08:54 UTC, jakubswierczek commented on features/omni-kit/protocols/ajna/controllers/AjnaOmniTokensBannerController.tsx
> +  isPriceBelowLup?: boolean // used only in earn product
if we have optional parameter, maybe we can introduce another type?

2023-10-27 08:54 UTC, jakubswierczek commented on features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
> +            <AjnaOmniTokensBannerController
it looks like there would be a two separate components `OpeningBannerCollotroller` and `BelowLupBannerController` 
Testing flags is always problematic.

2023-10-27 10:55 UTC, jakubswierczek approved these changes

2023-10-27 11:32 UTC, piotrwitek approved these changes
looks good to me, agreed on further changes in step 2. great effort everyone. Thanks

2023-10-27 11:36 UTC, merged