🍿 [Portfolio] Aave V3 positions WIP
OasisDEX/oasis-borrow pull request #3107
Opened 2023-11-09 16:49 UTC by marcinciarka

# 🍿 [Portfolio] Aave V3 positions WIP

2023-11-10 07:23 UTC, piotrwitek requested changes
Added comments regarding the quality concerns

2023-11-10 07:23 UTC, piotrwitek commented on handlers/portfolio/positions/handlers/dpm/index.ts
> +      subgraphListDict[networkId as DpmSupportedNetworks]
this type casting breaks all the ideas behind the typesafety, please fix it by adding simple reusable type guard helper function

2023-11-10 07:23 UTC, piotrwitek commented on handlers/portfolio/positions/handlers/aaveV3/index.ts
> +type getPositionHandler = (dpm: DpmList[number], tickers: Tickers) => Promise<PortfolioPosition>
use first capital letter for type

2023-11-13 14:58 UTC, piotrkonowrocki approved these changes

2023-11-13 14:59 UTC, merged