updated FAQ
OasisDEX/oasis-borrow pull request #312
Opened 2021-07-15 13:58 UTC by lucianken

adding new questions.

# [Title](https://clubhouseLink)

Updated FAQ per requested. 
  
## Changes 👷‍♀️

adding question specific to borrow. 
  
## How to test 🧪

Make sure I didn't break any code in the header.

2021-07-15 14:39 UTC, FBrinkkemper approved these changes
Approving just to check if that triggers heroku deployment

2021-07-15 14:42 UTC, FBrinkkemper requested changes
few changes to be made before merging

2021-07-15 14:42 UTC, FBrinkkemper commented on features/content/support/en.ts
> +    { title: 'Using Oasis Borrow', id: 'using-borrow' },
We now refer to Oasis Borrow as `Oasis`, and Oasis.app as `Daiwallet`. Please update the PR by removing Borrow from the app names and removing /borrow from the links

2021-07-15 14:56 UTC, lucianken commented on features/content/support/en.ts
> +    { title: 'Using Oasis Borrow', id: 'using-borrow' },
fixed

2021-07-15 15:06 UTC, FBrinkkemper commented on features/content/support/en.ts
>            answer: `Dai is a better, smarter digital currency for everyone. It is the world’s first unbiased currency and its value consistently tracks the US Dollar, which means it doesn't suffer fro
/dai -> /daiwallet/dai

2021-07-15 15:07 UTC, FBrinkkemper commented on features/content/support/en.ts
>            answer: `Oasis.app doesn't take any of the fees when you buy Dai or ETH through one of our partner providers. The fee you pay goes solely and directly to the third-party provider.`,
Oasis.app ... -> Our Dai Wallet ...

2021-07-15 15:07 UTC, FBrinkkemper commented on features/content/support/en.ts
> +      title: 'Using Daiwallet',
Using Daiwallet > Using Dai Wallet

2021-07-15 15:08 UTC, FBrinkkemper commented on features/content/support/en.ts
> +              'If you have any questions, reach out to us through our [Contact page](/contact) or on [Twitter](https://twitter.com/oasisdotapp).',
/contact -> /daiwallet/contact

2021-07-15 15:09 UTC, FBrinkkemper commented on features/content/support/en.ts
> +          answer: `To open a Vault, select the relevant Collateral and sub-type (e.g. ETH-A) from the homepage (Oasis.app/borrow) and connect your preferred wallet and follow the on screen instructio
Oasis.app/borrow -> Oasis.app

2021-07-16 07:26 UTC, FBrinkkemper commented
Created new PR within oasis-borrow repo and did some changes to make it work - https://github.com/OasisDEX/oasis-borrow/pull/315

2021-07-16 07:26 UTC, closed without merging