updated prisma added vault type and created migrations
OasisDEX/oasis-borrow pull request #340
Opened 2021-08-04 13:59 UTC by johnnieskywalker

# [Store 'multiply' or 'regular' View - Step 1 -  no localStorage, backend database based implementation](https://app.clubhouse.io/oazo-apps/story/2356/store-multiply-or-regular-view-step-1-localstorage-backend-database-based-implementation)

  
## Changes 👷‍♀️
  <Please add short list of changes>
- Updated prisma
- added script `yarn prisma:migrate`
- added table vault and data type vault_type in schema 
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-08-04 14:03 UTC, johnnieskywalker commented on server/database/migrations/20210804120727_tos_approval/migration.sql
> +    "address" CHAR(66) NOT NULL,
That's difference in previous script it was   address CHARACTER VARYING(66) NOT NULL,

I tried to define it the same way in prisma.schema but not sure if it's possible couldn't find an example. The best way would be to have consistency everywhere. In prisma.schema and in scripts. If it's not possible I will just use new migration script do changes to prisma.schema... updating prisma has couple of nice features for devs anyway.

2021-08-04 14:20 UTC, johnnieskywalker commented on package.json
> +    "node-sass": "^6.0.1",
IF you want I can revert it I do it everytime on my machine to successfully run `yarn` otherwise I have this python2/3 issue with nod3e-gyp

2021-08-04 14:22 UTC, johnnieskywalker commented on server/database/schema.prisma
> +  address     String     @db.Char(66)
wanted it to be represented in schema.prisma the same way as in database. Before there was small inconsistency however it generated different script... maybe I should just manually edit this part in it

2021-08-10 09:05 UTC, pacxiu commented on server/database/schema.prisma
> +  type VaultType
we could add `proxyAddress: String` to this model as we might need that already also for `VaultsOverview` task, when we will list user vaults, based on his/her proxyAddress, rather than pinging for each vault data separately.

2021-08-11 07:20 UTC, paszkowskiDamian commented on package.json
> +    "node-sass": "^6.0.1",
I would live it with newer version 👍

2021-08-11 07:27 UTC, paszkowskiDamian commented on server/database/schema.prisma
> +  type VaultType
We will need to somehow handle the case when vault is moved to another proxy. 

Maybe we can have an endpoint what will get an array of vault ids and we will get the array/object of vaults with types?

```
[1,2,3] -> [{id: 1, type: Borrow}, ....]
```

2021-08-17 13:44 UTC, paszkowskiDamian commented on features/shared/vaultApi.ts
> +          type: 'borrow' | 'multiply'
`'borrow' | 'multiply'` can be just `'borrow' | 'multiply'` 

and also I would add a type for response, not inline it.

2021-08-18 18:24 UTC, pacxiu commented on server/middleware/vault/get.ts
> +      // proxyAddress: vault.proxy_address
This can be removed

2021-08-18 18:24 UTC, pacxiu commented on server/middleware/vault/createOrUpdate.ts
> +    proxy_address: params.proxyAddress,
This can be removed

2021-08-18 18:24 UTC, pacxiu commented on server/middleware/vault/createOrUpdate.ts
> +  proxyAddress: z.string(),
This can be removed

2021-08-18 18:24 UTC, pacxiu commented on server/database/schema.prisma
> +  proxy_address String
This can be removed

2021-08-18 18:24 UTC, pacxiu commented on server/database/migrations/20210811122014_vault/migration.sql
> +-- CreateEnum
This file can be removed. Probably we had different timestamps in migrations

2021-08-18 18:24 UTC, pacxiu commented on server/app.ts
> +export function postVault() {
This can be removed

2021-08-18 18:24 UTC, pacxiu commented on helpers/stories/ManageVaultStory.tsx
> +      // generalManageVault$: memoize(() =>
This can be reverted.

2021-08-19 14:09 UTC, pacxiu requested changes

2021-08-19 14:09 UTC, pacxiu commented on helpers/stories/ManageVaultStory.tsx
> -      generalManageVault$: memoize(() =>
This part shouldn't be deleted as storybooks will stop working.

2021-08-19 14:09 UTC, pacxiu commented on server/database/migrations/migration_lock.toml
> +# Please do not edit this file manually
This file could be deleted - I guess it is leftover from prisma 2.28

2021-08-24 08:18 UTC, pacxiu approved these changes

2021-08-24 08:45 UTC, merged

2021-09-01 13:55 UTC, johnnieskywalker commented
in tyhe end prisma was not updated in this pr