Add new positon types on Aave v3 mainnet (Borrow & multiply)
OasisDEX/oasis-borrow pull request #3418
Opened 2024-01-22 15:51 UTC by piotrwitek

All the pairs should have Borrow & multiply enabled
Only pairs with usdc, usdt, and dai as borrowed token should have stop loss automation enabled

cbETH_supply | GHO_borrow
cbETH_supply | USDC_borrow
DAI_supply | MKR_borrow
LDO_supply | USDT_borrow
LINK_supply | DAI_borrow
LINK_supply | GHO_borrow
LINK_supply | USDC_borrow
LINK_supply | USDT_borrow
LINK_supply | WETH_borrow
MKR_supply | DAI_borrow
rETH_supply | GHO_borrow
rETH_supply | USDT_borrow
sDAI_supply | GHO_borrow
sDAI_supply | USDT_borrow
sDAI_supply | WBTC_borrow
sDAI_supply | WETH_borrow
USDC_supply | GHO_borrow
USDC_supply | USDT_borrow
USDC_supply | wstETH_borrow
USDT_supply | WETH_borrow
WBTC_supply | GHO_borrow
WBTC_supply | LUSD_borrow
WBTC_supply | USDT_borrow
WBTC_supply | WETH_borrow
WETH_supply | GHO_borrow
WETH_supply | USDT_borrow
WETH_supply | WBTC_borrow
wstETH_supply | cbETH_borrow
wstETH_supply | GHO_borrow
wstETH_supply | LUSD_borrow
wstETH_supply | RPL_borrow

2024-01-22 17:37 UTC, piotrwitek commented
@marcinciarka just missing icons for LDO and RPL, any idea how to get them?

2024-01-22 17:38 UTC, marcinciarka requested changes

2024-01-22 17:38 UTC, marcinciarka commented on blockchain/token-metadata-list/token-configs.ts
> +    icon: deprecated_icon,
We need actual icons here.

2024-01-23 11:58 UTC, marcinciarka requested changes
MKR icon is too big, we need to change it.

2024-01-23 11:58 UTC, marcinciarka commented on theme/icons/susd_circle.tsx
> +    <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Thats not needed, it's being wrapped in `svg` in the component.

2024-01-24 13:51 UTC, marcinciarka approved these changes

2024-01-24 13:54 UTC, merged