Dp/adjust position proxy action
OasisDEX/oasis-borrow pull request #345
Opened 2021-08-10 12:36 UTC by paszkowskiDamian

# [Integrate adjust position proxy actions](https://app.clubhouse.io/oazo-apps/story/2183/connect-adjust-position-actions-to-proxy-actions-smart-contract)
  
## Changes 👷‍♀️
 - make a call to blockchain to adjust position - multiply/demultiply 
  
## How to test 🧪
- setup hardhat locally
- deploy proxy actions
- use form to adjust position
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-08-10 14:19 UTC, johnnieskywalker approved these changes

2021-08-10 14:19 UTC, johnnieskywalker commented on features/manageMultiplyVault/manageMultiplyVaultTransitions.ts
> +  // state.exchangeAction === 'BUY_COLLATERAL'
[minor] please remove comment if it won't be needed soon

2021-08-11 08:36 UTC, adamskrodzki requested changes
I think if not changes then at least some explanations

2021-08-11 08:36 UTC, adamskrodzki commented on features/manageMultiplyVault/manageMultiplyVaultTransactions.ts
> +          requiredDebt: debtDelta?.abs() || zero,
shouldn't be current debt added somewhere here ? or just naming is wrong?

2021-08-11 08:36 UTC, adamskrodzki commented on features/manageMultiplyVault/manageMultiplyVaultTransactions.ts
> +          borrowedCollateral: collateralDelta?.abs() || zero,
same as above

2021-08-11 08:37 UTC, adamskrodzki commented
Doesn't this stuff sopposed to have some tests ?

2021-08-11 08:37 UTC, pacxiu submitted a review, later dismissed

2021-08-11 08:48 UTC, paszkowskiDamian commented on features/manageMultiplyVault/manageMultiplyVaultTransactions.ts
> +          requiredDebt: debtDelta?.abs() || zero,
I thought the contract accepts the debt change and collateral change, I can change to calculated `afterDebt` value

2021-08-11 08:50 UTC, adamskrodzki commented on features/manageMultiplyVault/manageMultiplyVaultTransactions.ts
> +          requiredDebt: debtDelta?.abs() || zero,
ok, naming is wrong on SC side

2021-08-11 08:51 UTC, adamskrodzki commented on features/manageMultiplyVault/manageMultiplyVaultTransactions.ts
> +          borrowedCollateral: collateralDelta?.abs() || zero,
again naming is wrong on SC side

2021-08-11 09:35 UTC, paszkowskiDamian commented
From this point you will need to set 

```
MULTIPLY_PROXY_ACTIONS=
EXCHANGE=
```

addresses in `.env`

2021-08-12 06:58 UTC, paszkowskiDamian commented on features/manageMultiplyVault/manageMultiplyVaultTransitions.ts
> +  // state.exchangeAction === 'BUY_COLLATERAL'
It will be removed in next iteration ;)

2021-08-12 08:31 UTC, merged