Refinance context overhaul
OasisDEX/oasis-borrow pull request #3775
Opened 2024-04-05 16:02 UTC by piekczyk

# Refinance context overhaul

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- refactored refinance context so its possible to maintain multiple context states
- added refinance context to portfolio
  
## How to test 🧪
  <Please explain how to test your changes>

- nothing to test right now

2024-04-09 05:44 UTC, piotrwitek requested changes

2024-04-09 05:44 UTC, piotrwitek commented on features/refinance/MakerRefinanceContext.tsx
these files were moved could you try to use git mv to preserve the file history instead? I dunno what was changed

2024-04-09 05:44 UTC, piotrwitek commented on features/refinance/RefinanceContext.tsx
same here

2024-04-09 06:11 UTC, piekczyk commented on features/refinance/MakerRefinanceContext.tsx
this one was actually deleted

2024-04-10 09:00 UTC, piotrwitek commented on features/refinance/MakerRefinanceContext.tsx
To be fair, it wasn't deleted but refactored as helper

2024-04-10 17:33 UTC, piotrwitek approved these changes
Looks good

2024-04-10 17:37 UTC, merged