Bugfix/copy changes
OasisDEX/oasis-borrow pull request #379
Opened 2021-08-31 14:12 UTC by johnnieskywalker

# [Title](https://www.notion.so/oazo/Multiply-MVP-copy-changes-5a0bad7b570245cbbb6b3bc46b66bdba)

  
## Changes 👷‍♀️
Copies and modals changed as in https://www.notion.so/oazo/Multiply-MVP-copy-changes-5a0bad7b570245cbbb6b3bc46b66bdba

## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ x] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

![image](https://user-images.githubusercontent.com/6871923/131518114-c0d93e14-db43-480a-8f9a-f2eb2313606d.png)

![image](https://user-images.githubusercontent.com/6871923/131518070-87caea1a-e08d-4bf8-823a-3c3ecc7cb261.png)

2021-08-31 14:32 UTC, johnnieskywalker commented
![image](https://user-images.githubusercontent.com/6871923/131521724-89186819-46cd-4210-bb06-552c9272a065.png)

![image](https://user-images.githubusercontent.com/6871923/131521788-6bf52b43-2b16-45dc-93cf-730cd96c201c.png)

2021-09-01 08:26 UTC, johnnieskywalker commented
I will add title to net value and make Liquidation price header smaller

2021-09-01 09:14 UTC, pacxiu requested changes

2021-09-01 09:14 UTC, pacxiu commented on public/locales/en/common.json
> +      "net-value": "The Net Value is calculated as the current value of the collateral in your vault minus the current debt.\nNote: This will not be exactly equal to the amount you will receive if yo
We have titles for all other modals so I guess it was missing in Notion to have `Net Value` title, and this bit as `description`

2021-09-01 09:14 UTC, pacxiu commented on public/locales/en/common.json
> +      "more-info-oracles": "More information on Maker oracles can be found here: https://kb.oasis.app/help/the-oracle-security-module",
This link should be `clickable`, it can be done like that - https://github.com/OasisDEX/oasis-app/blob/74b183d6702ce2cb66a9e6fecd3cf7032b13c077/components/cookies/NoticePrivacy.tsx#L79

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +        <Heading variant="header3">{`${t('manage-vault.card.current-price')}`}</Heading>
{`$ can be omitted here

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +        <Heading variant="header3">{`${t('manage-vault.card.next-price')}`}</Heading>
{`$ can be omitted here

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +          {`${t('manage-vault.card.next-price-description')}`}
{`$ can be omitted here

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +        <Text>{`${t('manage-vault.card.more-info-oracles')}`}</Text>
{`$ can be omitted here

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +        <Text>{`${t('manage-vault.card.more-info-oracles')}`}</Text>
Also this text is not styled as rest of the modal - `<Text variant="subheader" sx={{ fontSize: 2, pb: 2 }}>`

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +        <Text variant="subheader" sx={{ fontSize: 2, pb: 2 }}>
Heading is missing in this modal

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +        <Heading variant="header1">{`${t('system.liquidation-price')}`}</Heading>
variant should be `header3` to match other modals for title

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +          <Heading variant="header3">
Numbers here doesn't seem to be displayed at all:
![image](https://user-images.githubusercontent.com/19193499/131644826-6b99df83-8e96-49f4-bf72-7f31b935fe63.png)

2021-09-01 09:14 UTC, pacxiu commented on components/vault/VaultDetails.tsx
> +          <Heading variant="header3">
Also just looking from the design perspective I think only values were supposed to be on those gray card boxes.

So `Heading` shouldbe moved out of a card. Value ``$${formatAmount(liquidationPrice, 'USD')}`,` can be left inside card and removed from translation.

And text `liquidation-percentage-below` could be just under this card, and value here probably should be inlined rather than card as it is just some helper value, while liqPrice is sort of a main one.

2021-09-01 09:15 UTC, pacxiu commented
One more thing would  be to ask for copy for those 2 cards (Manage Regular vault):
![image](https://user-images.githubusercontent.com/19193499/131645495-e7e73ccc-9c4e-41c8-9dc4-0732f20f10d5.png)

2021-09-01 11:14 UTC, johnnieskywalker commented on public/locales/en/common.json
> +      "confirm-in-progress": "Your Vault is currently being. Transaction can take up to 5 minutes",
hmm https://www.notion.so/oazo/Multiply-MVP-copy-changes-5a0bad7b570245cbbb6b3bc46b66bdba I guess it was word `created` good job on spotting this one

2021-09-01 12:50 UTC, johnnieskywalker commented on components/vault/VaultDetails.tsx
> +          <Heading variant="header3">
![image](https://user-images.githubusercontent.com/6871923/131674092-ef16b4cb-60c5-4cfe-92c4-bd3e1862f4f1.png)

you meant result like this?

2021-09-01 12:52 UTC, johnnieskywalker commented
> One more thing would be to ask for copy for those 2 cards (Manage Regular vault):
> ![image](https://user-images.githubusercontent.com/19193499/131645495-e7e73ccc-9c4e-41c8-9dc4-0732f20f10d5.png)

I'll ask @FBrinkkemper for those as we don't yet have them in notion

2021-09-01 12:54 UTC, johnnieskywalker commented
After changes:
![image](https://user-images.githubusercontent.com/6871923/131674485-0651d2d4-4967-4422-a2ab-9314c7c91bbc.png)

![image](https://user-images.githubusercontent.com/6871923/131674523-6f853b6d-e5bc-43d0-8095-66fe60e41bd1.png)

![image](https://user-images.githubusercontent.com/6871923/131674564-76e15af9-7a67-477f-bfb0-2d014ef53ad2.png)

![image](https://user-images.githubusercontent.com/6871923/131674600-d8194418-dc52-4ad4-a956-5735e8dffd71.png)

2021-09-02 12:52 UTC, johnnieskywalker commented
new modals for old borrow vaults
![image](https://user-images.githubusercontent.com/6871923/131846831-e42b1114-153a-4cc4-a8d9-7697627b5de8.png)

![image](https://user-images.githubusercontent.com/6871923/131846770-f61cd9a0-3135-42b0-96f8-90b11c9fdc54.png)

2021-09-03 13:43 UTC, johnnieskywalker commented on public/locales/en/common.json
> +      "more-info-oracles": "More information on Maker oracles can be found here: https://kb.oasis.app/help/the-oracle-security-module",
![image](https://user-images.githubusercontent.com/6871923/132015154-9e71c4a3-a42f-4eb8-abb1-05bb33b7992f.png)
fixed

2021-09-03 14:31 UTC, pacxiu approved these changes

2021-09-03 14:32 UTC, merged