Bugfix/copy changes
OasisDEX/oasis-borrow pull request #391
Opened 2021-09-06 17:52 UTC by johnnieskywalker

# [Title](https://clubhouseLink)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

![image](https://user-images.githubusercontent.com/6871923/132250503-c177c496-c16a-462e-8fa7-b4156bae7e9d.png)

2021-09-07 13:24 UTC, johnnieskywalker commented
not sure if wrap this text ort make form wider ? contacted design team 

![image](https://user-images.githubusercontent.com/6871923/132352234-f15e25b0-1e39-42fd-bca9-e4734d686b4f.png)

2021-09-07 14:28 UTC, johnnieskywalker commented
thanks @peculiarity  
![image](https://user-images.githubusercontent.com/6871923/132362131-e2084c2b-5986-4cd7-9023-3c903f385f10.png)

2021-09-07 14:31 UTC, peculiarity commented on features/manageVault/ManageVaultView.tsx
> +          {t('vault-form.subtext.checkmark1', { token: vault.token })}
`token.toUpperCase()` ? I see that little bit higher .. you used it like that

2021-09-07 14:32 UTC, peculiarity commented on features/openVaultOverview/SelectVaultTypeModal.tsx
> +              token: token,
`token` only is ok

2021-09-07 15:06 UTC, johnnieskywalker commented on features/manageVault/ManageVaultView.tsx
> +          {t('vault-form.subtext.checkmark1', { token: vault.token })}
you're right looks good now but we cant be sure token is uppercase 
![image](https://user-images.githubusercontent.com/6871923/132367967-812858b6-20aa-4b5e-92a6-d9c4225bbe41.png)

2021-09-08 08:14 UTC, peculiarity approved these changes

2021-09-08 08:16 UTC, peculiarity requested changes
Please apply all copy to other `common.json` files for the other languages

2021-09-08 12:43 UTC, paszkowskiDamian commented
![image](https://user-images.githubusercontent.com/15217169/132511270-bb19376d-9496-4b08-8d3f-6b03399a88a1.png)

can we round it?

2021-09-08 13:00 UTC, paszkowskiDamian submitted a review, later dismissed

2021-09-08 13:00 UTC, paszkowskiDamian commented
Translations look good 👍

2021-09-08 13:11 UTC, paszkowskiDamian commented on features/openVaultOverview/SelectVaultTypeModal.tsx
> +  const maxBorrowAmount = ((1 / liquidationRatio) * 100000).toFixed(2)
I think you should take `liquidationRatio` and `user token balance` from context.

![image](https://user-images.githubusercontent.com/15217169/132515673-366ebe25-6732-4375-8c40-f7f2a0f0e7b1.png)

`maxBorrowAmount` should be based on user balance

2021-09-08 13:15 UTC, paszkowskiDamian commented on features/openVaultOverview/SelectVaultTypeModal.tsx
> +  const maxBorrowAmount = ((1 / liquidationRatio) * 100000).toFixed(2)
But I wondering whether it is possible to `useAppContext` in `useRedirectToOpenVault` 🤔

2021-09-08 13:20 UTC, johnnieskywalker commented on features/openVaultOverview/SelectVaultTypeModal.tsx
> +  const maxBorrowAmount = ((1 / liquidationRatio) * 100000).toFixed(2)
This took me lot of time on Monday and after few trials I decided to stop overcomplicate it and did this way. Well both solutions have some pros and cons

2021-09-08 13:54 UTC, peculiarity approved these changes

2021-09-08 13:59 UTC, merged