fixed bug now total exposure and multiplier is shown on OpenMultiplyV…
OasisDEX/oasis-borrow pull request #408
Opened 2021-09-09 13:52 UTC by johnnieskywalker

…aultDetails

# [Title](https://www.notion.so/oazo/Multiply-MVP-tests-Feedback-bugs-2a776db8d0cf4acdb42717c96ccdf9d2#d466d439ce204927a7e0b955dd46d0d6)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
Fixed following error https://www.notion.so/oazo/Multiply-MVP-tests-Feedback-bugs-2a776db8d0cf4acdb42717c96ccdf9d2#d466d439ce204927a7e0b955dd46d0d6
 changed expected behavior of the summary box for multiply: available to withdraw becomes Total Collateral, available to Generate becomes the multiple

## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

Result of fix:

![image](https://user-images.githubusercontent.com/6871923/132698408-7802cb6a-3dc8-4b65-8ec2-4492962d737b.png)

2021-09-09 14:06 UTC, adamskrodzki submitted a review, later dismissed
just minor comments

2021-09-09 14:06 UTC, adamskrodzki commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> +            {multiply?.toFixed(2)}
isn't here this x missing?

if i understand correctly this will display

2.41 exposure

instead of 

2.4x exposure 

not sure how frank itself is strict about it

2021-09-09 14:06 UTC, adamskrodzki commented on public/locales/en/common.json
> +    "multiply": "Multiply",
Multiple (on screen)

2021-09-09 14:13 UTC, pacxiu requested changes

2021-09-09 14:13 UTC, pacxiu commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> -        valueAfter={
Pls add `afterTotalExposure`

2021-09-09 14:13 UTC, pacxiu commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> -        valueAfter={
Pls add `afterMultiply` also take into consideration it should be `n/a` when we are in a closeTo operation

2021-09-09 14:17 UTC, pacxiu commented
Please confirm with Frank if those shouldn't be also added to `ManageMultiply` as now those boxes are inconsisten between those 2 flows.

2021-09-09 14:25 UTC, paszkowskiDamian commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> +            {multiply?.toFixed(2)}
![image](https://user-images.githubusercontent.com/15217169/132704146-8c59f773-3f7c-4582-9727-96cd683e325d.png)

Can you check whether on the forms there should be `multiple` instead of `multiply`

2021-09-09 14:25 UTC, paszkowskiDamian commented on public/locales/en/common.json
> +    "multiply": "Multiply",
![image](https://user-images.githubusercontent.com/15217169/132704146-8c59f773-3f7c-4582-9727-96cd683e325d.png)

Can you check whether on the forms there should be `multiple` instead of `multiply`

2021-09-09 14:26 UTC, paszkowskiDamian commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> -        valueAfter={
![image](https://user-images.githubusercontent.com/15217169/132704387-96f39137-eb59-44fc-8520-657507d155b2.png)

2021-09-09 19:05 UTC, johnnieskywalker commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> +            {multiply?.toFixed(2)}
x is in the copy maybe it's not most obvious way of doing... but on other hand I thought maybe in some locales like cn this x may not be used, maybe some other sign from another alphabet I don't know

2021-09-09 19:06 UTC, johnnieskywalker commented on public/locales/en/common.json
> +    "multiply": "Multiply",
AFAIK it should be Multiply but yeah on some design screenshots I saw Multiple too...

2021-09-09 19:08 UTC, johnnieskywalker commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> -        valueAfter={
Good point @FBrinkkemper also mentioned that I will change it

2021-09-09 19:09 UTC, johnnieskywalker commented
> Please confirm with Frank if those shouldn't be also added to `ManageMultiply` as now those boxes are inconsisten between those 2 flows.

@pacxiu yeah confirmed with @FBrinkkemper it should be added also on manage multiply

2021-09-09 19:24 UTC, johnnieskywalker commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> -        valueAfter={
![image](https://user-images.githubusercontent.com/6871923/132749843-3f210ab7-ddb5-4b44-beb3-24a08beb8961.png)

2021-09-09 19:26 UTC, johnnieskywalker commented on features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> -        valueAfter={
this way with dual precision zero :) 
![image](https://user-images.githubusercontent.com/6871923/132750065-edee14f8-e1e7-44e6-9054-0f379f50b0e1.png)

2021-09-09 19:32 UTC, johnnieskywalker commented on public/locales/en/common.json
> +    "multiply": "Multiply",
it turned out multiple is correct. 
`It is a multiply Vault, but that has a multiple of X so in this case I would say it's multiple. Also can be updated in the sidebar
`

2021-09-09 20:41 UTC, johnnieskywalker commented
> Please confirm with Frank if those shouldn't be also added to `ManageMultiply` as now those boxes are inconsisten between those 2 flows.

@pacxiu I guess we should use lockedCollateral on manage multiply view the same way as in `ManageMultiplyVaultChangesInformation`

```
            {formatCryptoBalance(lockedCollateral)} {token}
            <VaultChangesInformationArrow />
            {formatCryptoBalance(afterLockedCollateral)} {token}
```

2021-09-10 10:11 UTC, johnnieskywalker commented
Fixed for manage multiply vault view 
![image](https://user-images.githubusercontent.com/6871923/132838259-1617a051-98e8-4c5a-ae06-5821185438c8.png)

2021-09-10 11:22 UTC, pacxiu approved these changes

2021-09-10 11:23 UTC, merged