Rz/pnl calcs
OasisDEX/oasis-borrow pull request #488
Opened 2021-09-23 14:45 UTC by pacxiu

# [Title](https://clubhouseLink)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-10-19 09:03 UTC, peculiarity commented on helpers/multiply/calculations.ts
> +  //   starting ${cummulativeDepositUSD.minus(cummulativeWithdrawnUSD).toFixed()}
Remove this please

2021-11-02 12:47 UTC, adamskrodzki requested changes

2021-11-02 12:47 UTC, adamskrodzki commented on helpers/multiply/calculations.ts
> +      return total.plus(event.daiAmount)
is sign here correct ? no abs() and - required ?

2021-11-02 12:47 UTC, adamskrodzki commented on helpers/multiply/calculations.ts
> +function getCumulativeDepositUSD(total: BigNumber, event: VaultEvent) {
where this methods are in use ?

2021-11-02 12:49 UTC, paszkowskiDamian commented on helpers/multiply/calculations.ts
> +      return total.plus(event.daiAmount)
Here `daiAmount` will always be positive as we increase the debt.

2021-11-02 12:50 UTC, paszkowskiDamian commented on helpers/multiply/calculations.ts
> +function getCumulativeDepositUSD(total: BigNumber, event: VaultEvent) {
```
export function calculatePNL(events: VaultEvent[], currentNetValueUSD: BigNumber) {
  const cumulativeDepositUSD = events.reduce(getCumulativeDepositUSD, zero) // here line 299
  const cumulativeWithdrawnUSD = events.reduce(getCumulativeWithdrawnUSD, zero)
  const cumulativeFeesUSD = events.reduce(getCumulativeFeesUSD, zero)

  return cumulativeWithdrawnUSD
    .plus(currentNetValueUSD)
    .minus(cumulativeFeesUSD)
    .minus(cumulativeDepositUSD)
    .div(cumulativeDepositUSD)
}
```

2021-11-02 12:51 UTC, paszkowskiDamian commented on helpers/multiply/calculations.ts
> +    // TODO: move_src
this requires changes in cache

2021-11-02 12:51 UTC, paszkowskiDamian commented on helpers/multiply/calculations.ts
> +      return total.plus(event.gasFee.times(event.marketPrice)) // TODO add ethPrice to all events
this requires change in cache

2021-11-02 12:54 UTC, adamskrodzki commented on helpers/multiply/calculations.ts
> +    case 'OPEN_MULTIPLY_VAULT':
only Gas Fees for multiply ? we do not have one for not multiply events ?

2021-11-02 12:56 UTC, adamskrodzki approved these changes

2021-11-02 12:57 UTC, merged