Cookie Banner
OasisDEX/oasis-borrow pull request #582
Opened 2021-11-15 21:29 UTC by ferni

# [Create Cookie banner](https://app.shortcut.com/oazo-apps/story/2994/create-cookie-banner)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- Add cookie banner to landing page.
- Can enable/disable Mixpanel (analytics cookie). Marketing cookie is yet to be implemented (adroll).
- Extract ChevronUpDown component, for all your chevron up/down needs.

2021-11-16 15:00 UTC, johnnieskywalker commented
when rejected 
![image](https://user-images.githubusercontent.com/6871923/142009424-a5dfc72f-f439-4f7f-bbaf-67ead62a917e.png)

2021-11-16 15:03 UTC, johnnieskywalker commented
When one goes to app to other page then landing, using for example URL somebody may copy paste it from somewhere or have a bookmark in browser then cookieBanner doesn't show up on other pages and cookieSetting in localStorage is not existing

2021-11-16 15:52 UTC, johnnieskywalker requested changes
Everything works as expected and implementation is correct. Just please make sure CookieBanner will appear on every page that one can visit using URL. 
So it will appear also on pages like: 

https://localhost:3443/owner/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266?network=hardhat

https://localhost:3443/vaults/list?network=hardhat

also ones that allow one to view somebody's vault in read only mode like:
https://staging.oasis.app/25862

Not sure how pages like /about but guess there it should appear too please verify with @FBrinkkemper 

https://staging.oasis.app/about

2021-11-16 15:52 UTC, johnnieskywalker commented on features/landing/LandingView.tsx
> +      <CookieBanner />
This CookieBanner should appear in all pages that are reachable by URL. User may have for ex bookmarked URL to vault or send some URL to someone else etc. CookieBanner should appear there too. 
So AFAIK besides LandingPage it should be added to all pages in /`oasis-borrow/pages` directory and maybe in couple other Vault views.

2021-11-16 15:52 UTC, johnnieskywalker commented on features/landing/CookieBanner.tsx
> +    // enable/disable based on settings
[minor] So maybe instead comment other name of function would be better idea? Maybe `saveAcceptedCookies` or `saveAcceptedAndRejectedCookies`, `saveCookiesSettings` ? Something like this

2021-11-16 15:52 UTC, johnnieskywalker commented on features/landing/CookieBanner.tsx
> +    // enable/disable based on settings
Ah I got this name because it's related to acceptButton. Maybe it should be just `acceptSelectedCookies` ? 
Well one may unselected both and click accept so actually nothing will be accepted but I guess for method name it will be fine.
![image](https://user-images.githubusercontent.com/6871923/142017988-26933aa8-98c4-463c-8c31-0d208043cb90.png)

2021-11-16 15:52 UTC, johnnieskywalker commented on features/landing/CookieBanner.tsx
> +      <Button variant="beanActive" sx={{ fontSize: 2 }} onClick={() => acceptCookies()}>
[minor] Method name suggestion `acceptSelectedCookies()`

2021-11-17 03:33 UTC, ferni commented on features/landing/CookieBanner.tsx
> +    // enable/disable based on settings
You made me realize that also a more accurate name for cookieSettings is "selectedCookies", that way one gets information about what the true/false value stands for, so I changed that as well.

2021-11-17 03:35 UTC, ferni commented
The build fails now after merging dev, but you can test it locally by undoing the merge commit: 57305208b452e8dfadeecef8e914e73b5db40f44

2021-11-17 10:23 UTC, johnnieskywalker commented
CookieBanner still doesn't appear on vault page
example URL https://localhost:3443/owner/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266?network=hardhat

![image](https://user-images.githubusercontent.com/6871923/142182694-0046d0de-8f09-4435-8d32-2ac030bf629e.png)

2021-11-17 10:25 UTC, johnnieskywalker approved these changes
Approved sir! Everything looks okay tested couple of scenarios, visiting vault, about team page and cookieBAnner appears everywhere

2021-11-29 23:30 UTC, merged