fixed @ts-ignores
OasisDEX/oasis-borrow pull request #615
Opened 2021-11-30 08:21 UTC by piekczyk

# [Typescript fixes](https://app.shortcut.com/oazo-apps/story/3122/1-5-days-timebox-get-rid-of-any-type-and-ts-ignore)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- removed @ts-ignore decorators and any types where possible
  
## How to test 🧪
  <Please explain how to test your changes>
- hardhat, this PR shouldn't have impact on how app works
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-11-30 15:44 UTC, sennett commented on features/account/Account.storiesx.tsx
> +      // transactions={[protoSuccessTx, { ...protoPendingTx, lastChange: newTime }]}
Why this commenting?

2021-12-01 08:16 UTC, adamskrodzki requested changes

2021-12-01 08:16 UTC, adamskrodzki commented on features/account/Account.storiesx.tsx
> +      // transactions={[protoSuccessTx, { ...protoPendingTx, lastChange: newTime }]}
+1

2021-12-01 08:36 UTC, piekczyk commented on features/account/Account.storiesx.tsx
> +      // transactions={[protoSuccessTx, { ...protoPendingTx, lastChange: newTime }]}
protoSuccessTx and protoPendingTx are not declared so suppressing may lead to unexpected behavior

2021-12-09 15:15 UTC, adamskrodzki approved these changes

2021-12-09 15:16 UTC, merged