Feature/automation set sl form
OasisDEX/oasis-borrow pull request #618
Opened 2021-12-01 08:23 UTC by adamskrodzki

# [Automation](https://app.shortcut.com/oazo-apps/story/2947/auto-implement-automation-approval-transaction)

  
## Changes 👷‍♀️

- Added ability to send on Goerli transaction setting a trigger
- Added ability to set a stop loss level and choose type of stop loss
  
## How to test 🧪
 - Switch to goerli network
 - Create a new vault
 - Go to protection tab (Stop loss should have value '-')
 - set a stop loss and wait 
 - stop loss should set itself to proper value on the ui
 - edit stop loss again
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-12-01 08:38 UTC, adamskrodzki commented on components/AppContext.ts
> +function createUIChangesSubject() {
This monster right here is a wrapper over BehaviorSubject
Ensuring that:

- subscriptions to the channel might be done before channel actually exist (wrong control rendering order)
- many subscriptions from one control (due to any bug in control) end up creating only one subscription 
- subscription can be identified by pair (subjectName, subscriberId)

2021-12-01 08:45 UTC, adamskrodzki commented on components/AppContext.ts
> +  const automationTriggersData$ = memoize(
This Observable is responsible for fetching Events (TriggerAdded) from AutomationBot Smart contract, currently with use of web3 in future will be replaced with oasis-borrow-cache

2021-12-01 08:47 UTC, adamskrodzki commented on components/AppContext.ts
> +  const uiChanges = createUIChangesSubject()
This observable (Subject) allows to both subscribe and publish data, it is ment to be used as a way of informing other controls about UI changes, currently used only once but written in generic fashion also as a proposal for change in User Input handling

2021-12-01 08:49 UTC, adamskrodzki commented on components/stateless/PickCloseState.tsx
> +
All controls in stateeless folder are supposed to be suitable for reuse, this should be reusable in Close Multiply Vault

2021-12-01 08:50 UTC, adamskrodzki commented on components/stateless/RetryableLoadingButton.tsx
> +export function RetryableLoadingButton(props: RetryableLoadingButtonProps) {
This is implementation of our standard button (with loading and retry option) as standalone component

2021-12-01 08:52 UTC, adamskrodzki commented on components/stateless/SliderValuePicker.tsx
> +import { Box, Flex, Grid, Slider, Text } from '@theme-ui/components'
This is encapsulated component for slider with possible additional headers and texts

2021-12-01 08:52 UTC, adamskrodzki commented on components/stateless/TxStatusSection.tsx
> +import { TxState } from '@oasisdex/transactions'
This is just a draft of a component responsible for displying current status of transaction as a poc how it can be done.

2021-12-01 08:53 UTC, adamskrodzki commented on components/vault/CloseVaultCard.tsx
> +  optionName,
creation of 
components/stateless/PickCloseState.tsx

required those adjustments

2021-12-01 08:54 UTC, adamskrodzki commented on components/vault/DefaultVaultHeaderControl.tsx
> +import BigNumber from 'bignumber.js'
example of refactor of existing vault headers

2021-12-01 09:02 UTC, adamskrodzki commented on features/automation/common/StopLossTriggerDataExtractor.ts
> +import BigNumber from 'bignumber.js'
util functions transforming and filtering general Triggers data to specifically StopLoss data

2021-12-01 09:03 UTC, adamskrodzki commented on features/automation/common/UITypes/AddFormChange.ts
> +export interface AddFormChange {
data model of possible UI change for setting automation, pushed to UIChanges subject

2021-12-01 09:04 UTC, adamskrodzki commented on features/automation/common/enums/TriggersTypes.ts
> +}
Currently possible triggers, every Id corresponds to  typeId in event on blockchain, will be extended once new type of triggers (like straategies) will e added

2021-12-01 09:13 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +function isTxStatusFinal(status: TxStatus) {
probably should be moved to some utils file, but did not found

2021-12-01 09:22 UTC, adamskrodzki commented on components/TabSwitchLayout.tsx
> +import { Box, Button, Grid } from '@theme-ui/components'
Naming convention, if name ends with "Layout" it should be simple control just drawing componentsUI and possibly doing some simple arithmetic calculations specific to that control, all information is passed via explicitly stated props and returned via collbacks

If "Control" postfix is used then the control communicates with data layer of application - for instance it is using pilepines. Usually Controls are responsible for building params for "Layout"

2021-12-01 09:24 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +  } = useAppContext()
explicitly states what part of context is in use

2021-12-01 09:25 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +  uiChanges.createIfMissing<AddFormChange>(uiSubjectName, {
this control publishes UI changes inside it

2021-12-01 09:26 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +  function renderLayout(
when all observables are ready this method is executed and it fetches all the data and sets all the props

2021-12-01 09:28 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +      onClick: (finishLoader: (succeded: boolean) => void) => {
finishLoader is a handler that stateless button control passes when clicked to allow parent control to finish loading when desired

2021-12-01 09:28 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +      isLoading: false,
initial state

2021-12-01 09:30 UTC, adamskrodzki commented on features/automation/controls/ProtectionDetailsControl.tsx
> +    uiChanges.subscribe<AddFormChange>(uiSubjectName, subscriberId, (value) => {
subscribing to changes from AdjustSLFormControl

2021-12-01 09:36 UTC, adamskrodzki commented on features/automation/triggers/AutomationTriggersData.ts
> +      var testProvider = new ethers.providers.Web3Provider((window as any).ethereum)
this might be incorrect for wallets other than metamask

2021-12-02 10:18 UTC, piekczyk requested changes

2021-12-02 10:18 UTC, piekczyk commented on components/stateless/PickCloseState.tsx
> +  const OnClickHandler = (op: string) => {
onClickHandler

2021-12-02 10:18 UTC, piekczyk commented on components/stateless/RetryableLoadingButton.tsx
> +    setLoading(props.isLoading)
if you wanted to set here defaults you can do it directly in useState hook:
const [isLoading, setLoading] = useState(props.isLoading)

2021-12-02 10:18 UTC, piekczyk commented on components/stateless/RetryableLoadingButton.tsx
> +            {t(isRetry ? 'retry' : props.translationKey)}
missing translation?

2021-12-02 10:18 UTC, piekczyk commented on components/vault/detailsCards/VaultDetailsCardCollateralLocked.tsx
> +  collateralLockedUSD: BigNumber | undefined
collateralLockedUSD?: BigNumber

2021-12-02 10:26 UTC, adamskrodzki commented on components/stateless/RetryableLoadingButton.tsx
> +    setLoading(props.isLoading)
I believe I encountered some problems with react life cycle when doing that way, will check again

2021-12-02 10:29 UTC, adamskrodzki commented on components/stateless/RetryableLoadingButton.tsx
> +            {t(isRetry ? 'retry' : props.translationKey)}
do not understand ? 
if isRetry button is supposed to display "Retry"  - t("retry")
if !isRetry button is supposed whatever you have set (for instance "Add Stop Loss") which is supposed to be under t(props.translationKey)

Any suggestin how to make it more readable ?

2021-12-02 10:33 UTC, adamskrodzki commented on components/vault/detailsCards/VaultDetailsCardCollateralLocked.tsx
> +        <Heading variant="header3">{`${t('system.collateral-locked')}`}</Heading>
not sure if i understand a comment, but besides that - it is your code Dude i just merged it

2021-12-02 10:33 UTC, piekczyk commented on components/stateless/RetryableLoadingButton.tsx
> +            {t(isRetry ? 'retry' : props.translationKey)}
ah sorry, I missed that this condition is within t()

2021-12-02 13:01 UTC, piekczyk commented on components/vault/detailsCards/VaultDetailsCardCollateralLocked.tsx
> +        <Heading variant="header3">{`${t('system.collateral-locked')}`}</Heading>
yep I see :D I meant that instead of `{`${t('system.collateral-locked')}`}` it could be just `{t('system.collateral-locked')}`.

2021-12-03 13:57 UTC, adamskrodzki commented on components/AppContext.ts
@sennett please re-review this file. I guess it is simple now

2021-12-06 09:21 UTC, paszkowskiDamian commented on blockchain/calls/automationBot.ts
> +export type AutomationBotAddTriggerData = TxMeta & {
We do not use `TxMeta` like this. `TxMeta` is just a general type how tx meta should look like. 

You should add new kind to `TxMetaKind` enum and use it here.
``` typescript 
export type AutomationBotAddTriggerData = {
kind: TxMetaKind.automationTrogger
...
}
```

2021-12-06 09:26 UTC, paszkowskiDamian commented on components/AppContext.ts
> +  }
There is already build-in type `Record`, I would name it differently.

2021-12-06 09:34 UTC, paszkowskiDamian commented on components/AppContext.ts
> +      shareReplay(1),
> subscriptions to the channel might be done before channel actually exist (wrong control rendering order)

Actually this will emit just one last "event" for late subscribers.

2021-12-06 09:35 UTC, sennett commented on components/AppContext.ts
Nice.

2021-12-06 09:37 UTC, paszkowskiDamian commented on components/AppContext.ts
> +function createUIChangesSubject() {
> Why not just one stream for all the things, which can have keys on them?

I would agree here with @sennett 

I don't understand why should we reinvent a wheel. What you are trying to achieve here is basically redux + rxjs integration with is redux-observable.

2021-12-06 09:38 UTC, sennett commented on components/AppContext.ts
> +  const uiChanges = createUIChangesSubject()
@paszkowskiDamian @piekczyk what do you think of this versus React `Context`?

2021-12-06 09:40 UTC, paszkowskiDamian commented on components/AppContext.ts
>    const chainIdToDAIContractDesc = mapValues(networksById, (network) => network.tokens.DAI)
I don't know when it was added but the. It was already implemented in such manner if you get `context.tokens.DAI` you will get proper address depending to which chain you are connected. The was really good that you do not care about chain id.

2021-12-06 09:49 UTC, adamskrodzki commented on components/AppContext.ts
> +      shareReplay(1),
I think it is ok, since it is last state of input

2021-12-06 09:50 UTC, adamskrodzki commented on components/AppContext.ts
>    const chainIdToDAIContractDesc = mapValues(networksById, (network) => network.tokens.DAI)
I'm not using thin anywhere It's not my code :D

2021-12-06 09:53 UTC, paszkowskiDamian commented on components/TabSwitchLayout.tsx
> +          sx={{ ...padding }}
no need for deconstruction, the padding object can be moved out of the `TabSwitchLayout` so you do not create new object for each rerender. If you would use `useCallback` hook it would be even possible to prevent Buttons from rerendeing when not necessary. However I think it will not improve performance noticeably.

2021-12-06 09:59 UTC, adamskrodzki commented on blockchain/calls/automationBot.ts
> +export type AutomationBotAddTriggerData = TxMeta & {
I had problems with yarn typecheck when not doing that way

2021-12-06 10:01 UTC, adamskrodzki commented on components/AppContext.ts
> +  }
changed to PublisherRecord

2021-12-06 10:05 UTC, paszkowskiDamian commented on components/TabSwitchLayout.tsx
> +}: {
You describeLayout components as something reusable, but here I see that is an exact switch which has exactly 3 (or less) tabs with exact names.

2021-12-06 14:24 UTC, paszkowskiDamian commented on blockchain/calls/automationBot.ts
> +export type AutomationBotAddTriggerData = TxMeta & {
https://github.com/OasisDEX/oasis-borrow/pull/628

2021-12-06 15:11 UTC, paszkowskiDamian commented on components/dumb/TxStatusSection.tsx
> +  txState: TxState<AutomationBotAddTriggerData> | undefined
does it need to be coupled to `AutomationBotAddTriggerData`?

2021-12-06 15:29 UTC, paszkowskiDamian commented on features/automation/controls/AdjustSlFormControl.tsx
> +        })
1. I don't really like this. It looks like we do not have single source of truth for ` selectedSLValue, collateralActive,` as the values are stored in 2 places. 
2. Did you check whether it works? `setCloseToCollateral(optionName === validOptions[1])` changes `collateralActive` but the value will be updated in subsequent render so there are cases when the value might be wrong
3. Whenever you change anything on the UI you have to remember to pass all state so you do not remove anything by accident. I can imagine that we will need to add new filed in "subjectState" so then should we find all occurrences where it was used and update it with new key?  Thats why in my opinion action reducer architecture it cleaner.

2021-12-07 17:18 UTC, adamskrodzki commented on components/AppContext.ts
> +  function subscribe<T>(subjectName: string): Observable<T> {
what is your suggestion? It returns observable so it is kind of subscription

2021-12-07 17:27 UTC, adamskrodzki commented on components/AppContext.ts
> +  function subscribe<T>(subjectName: string): Observable<T> {
suggestions welcome :) Usage example:
` 
 const subscription = uiChanges$.subscribe((value) => {
      lastUIStateSetter(value)
    })   
`

looks like sobscription to me ;)

2021-12-07 17:29 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +        })
fixed @paszkowskiDamian  please re-review

2021-12-07 17:30 UTC, adamskrodzki commented on components/TabSwitchLayout.tsx
> +}: {
will upgrade it

2021-12-07 17:31 UTC, adamskrodzki commented on components/dumb/TxStatusSection.tsx
> +  txState: TxState<AutomationBotAddTriggerData> | undefined
thanks for spotting, will upgrade it

2021-12-08 09:14 UTC, adamskrodzki commented on helpers/observableHook.ts
> +  const { uiChanges } = useAppContext()
This is little nasty, dependency to useAppContext, but encapsulates initialisation

@sennett @paszkowskiDamian

2021-12-08 09:25 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +    const dispatch = useUIChanges(reducerHandler, initial, uiSubjectName)
this is whole required initialisation to have functional dispatcher propagating new versions of a state to uiCHanges Observable @sennett @paszkowskiDamian

2021-12-08 09:26 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +
Above reducer which need to be defined once for each UIState model, for now in a control in this form, but probably theree is a better place for it

2021-12-08 09:26 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +
@sennett @paszkowskiDamian

2021-12-08 09:27 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +        })
Above, example usage of dispatch updating the state @sennett @paszkowskiDamian

2021-12-08 09:29 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +      },
example use of dispatch updating the state @paszkowskiDamian @sennett

2021-12-08 10:11 UTC, adamskrodzki commented on components/TabSwitchLayout.tsx
> +}: {
Added todo: I want to exclude this from this PR to not make it even bigger than it is

2021-12-10 09:30 UTC, paszkowskiDamian commented on components/dumb/RetryableLoadingButton.tsx
> +  }, [])
Is it your intention that you set loading and retry only once at component mount?

2021-12-10 09:37 UTC, paszkowskiDamian commented on components/dumb/TxStatusSection.tsx
> +}
``` typescript 
import { TxMeta, TxState } from '@oasisdex/transactions'
import React from 'react'

import { TxStatusCardProgress } from '../vault/TxStatusCard'

export interface TxStatusSectionProps<A extends TxMeta> {
  txState: TxState<A> | undefined
}

export function TxStatusSection<A extends TxMeta>(props: TxStatusSectionProps<A>) {
  return (
    <>
      {!props.txState ? (
        <></>
      ) : (
        <TxStatusCardProgress
          text={`Transaction is processing ${props.txState?.status.toString()}`}
          etherscan={''}
          txHash={(props.txState as any).txHash}
        />
      )}
    </>
  )
}
```

Here you go :)

2021-12-10 09:37 UTC, paszkowskiDamian commented on components/dumb/TxStatusSection.tsx
> +          text={`Transaction is processing ${props.txState?.status.toString()}`}
Don't we have translation for this?

2021-12-10 09:38 UTC, paszkowskiDamian commented
I hope all `console.log`s will be removed when merged to `dev`

2021-12-10 09:40 UTC, adamskrodzki commented on components/dumb/RetryableLoadingButton.tsx
> +  }, [])
yes as a default value

2021-12-10 09:43 UTC, paszkowskiDamian commented on components/dumb/RetryableLoadingButton.tsx
> +  }, [])
👍

2021-12-10 09:45 UTC, adamskrodzki commented on components/dumb/TxStatusSection.tsx
> +          text={`Transaction is processing ${props.txState?.status.toString()}`}
will check

2021-12-10 10:23 UTC, paszkowskiDamian approved these changes

2021-12-10 10:34 UTC, merged