market price max slippage fixed
OasisDEX/oasis-borrow pull request #638
Opened 2021-12-07 13:02 UTC by piekczyk

# [Market price max slippage value fixed](https://app.shortcut.com/oazo-apps/story/3140/bug-slippage-wrongly-accounted-for-in-worst-case-market-price-calculation)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- fixed calculation of max market price max slippage
  
## How to test 🧪
  <Please explain how to test your changes>
- heroku / local
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-12-07 14:55 UTC, adamskrodzki requested changes
does this change requre corresponding change in Exchange SC ? @fenris85 i believe Georgie changes are not merged

2021-12-07 15:02 UTC, fenris85 commented
> does this change requre corresponding change in Exchange SC ? @fenris85 i believe Georgie changes are not merged

no, this change is not merged in SC

2021-12-17 10:28 UTC, sennett commented on features/openGuniVault/openGuniVault.ts
> +
I think it's strange that we are passing the state subject back into the middle of itself.  The state subject is the view state, which is the result of this pipeline, and composed from other streams.  I'm not 100% sure of having a stream (`OpenGuniVaultState`) depend on itself in this way - it seems like a code smell if we are having to do this.

2021-12-17 10:30 UTC, sennett reviewed
I'm keen to have a chat about passing the stream back into itself and see if we can find another solution.

2021-12-17 11:15 UTC, piekczyk commented on features/openGuniVault/openGuniVault.ts
> +
Yep, it's pretty hacky, but for now we couldn't find better way to fix this problem. Other pipelines don't have this issue.

2021-12-17 11:18 UTC, adamskrodzki requested changes
Is there possibility to split this PR to two:

One responsible for UI part - passing slippage to a user and second for fixing calculaton, I think it is important from testability perspective. 

Not a requirement (since i was creating similar PR's myself :) ), but would help to review

2021-12-17 11:18 UTC, adamskrodzki commented on features/openGuniVault/openGuniVault.ts
>    return ilks$.pipe(
I have a feeling like we could Use some tests of this pipeline modification,
some similar tests already exists for other flows
features/openMultiplyVault/tests/openMultiplyVault.test.ts

In perfect scenario there woould be separate PR with test of slippage value change impact on Guni pipeline

2021-12-17 12:15 UTC, piekczyk commented on features/manageGuniVault/manageGuniVault.ts
> -                            minToTokenAmount: swap.daiAmount.times(one.minus(SLIPPAGE)),
sorry for that, the update related to market price max slippage is in following commit:

https://github.com/OasisDEX/oasis-borrow/pull/638/commits/5b03a1fc020328a5808533ec5b3090400a489d9e

2021-12-17 12:33 UTC, piekczyk commented on features/openGuniVault/openGuniVault.ts
>    return ilks$.pipe(
Yep, we currently don't have tests for guni and I believe question if we should prepare these test before / after refactor has been left without answer / decision. Anyway this PR will be merge to feature branch so it won't ruin staging.

2022-01-06 16:39 UTC, sennett approved these changes
Seems good to me - it's a shame about the coverage decreasing and the state getting passed back in to the stream, but I don't know enough yet to offer a better solution quickly.

2022-01-10 10:16 UTC, merged