consolidate features/manageVault/ManageVaultCollateralAllowance.tsx into
OasisDEX/oasis-borrow pull request #674
Opened 2021-12-18 16:05 UTC by sennett

Applies some refactoring form Sonarcloud (nice one Adam), with goal of reducing duplication.

- Creates a common base type for defining vault stages `features/openMultiplyVault/common/TBaseManageVaultStage.ts`.
- Creates a new type `TAllVaultStages` which can be used by the view components so that they can accept all of the vault stages - i.e. the same view component used in different user flows.

From a recent discussion with Seba, `features/openMultiplyVault/common` is the place where we are starting to collect common things across these flows, but it currently contains files that should be renamed.  `features/openMultiplyVault` should be renamed to `features/vault` at some point in the future.  We should talk more to align on some form of file structure.

2021-12-21 08:48 UTC, paszkowskiDamian commented on features/openMultiplyVault/common/TBaseManageVaultStage.ts
> +  | 'daiAllowanceSuccess'
Did we have dai Allowances in open multiply flow?

2021-12-21 11:55 UTC, sennett commented on features/openMultiplyVault/common/TBaseManageVaultStage.ts
> +  | 'daiAllowanceSuccess'
It is in both:

- [manage multiply vault](https://github.com/OasisDEX/oasis-borrow/pull/674/files#diff-9a0a1eddaa66411209f121193ab1b410ba34af9ec93a3afe8ce7b0df4c820d09L129-L133)
- [manage vault](https://github.com/OasisDEX/oasis-borrow/pull/674/files#diff-1e0d6743dffaa9fabbe32e5dc62e86c6eb35c274bf1e85f64570a13545f337aeL113-L117)

2021-12-21 13:40 UTC, piekczyk requested changes
Don't forget to delete this file as is empty for now :) 

features/openMultiplyVault/common/TProxyChange.ts

2021-12-21 13:40 UTC, piekczyk commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
>    depositAmount,
depositAmount = zero

2021-12-21 13:40 UTC, piekczyk commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
> +  const _depositAmount = depositAmount || new BigNumber(0)
no need if default is set for this variable

btw. instead of creating new big number which equals to 0 you can use "zero" from helpers

2021-12-21 13:40 UTC, piekczyk commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
> +  selectedCollateralAllowanceRadio: 'unlimited' | 'depositAmount' | 'custom'
I believe that this type could be extracted as well

2021-12-21 13:40 UTC, piekczyk commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
> +              {t('token-depositing', { token, amount: formatCryptoBalance(_depositAmount!) })}
! - wont be necessary if default is defined

2021-12-21 13:40 UTC, piekczyk commented on features/openMultiplyVault/common/TAllVaultStages.ts
> +export type TAllVaultStages = ManageMultiplyVaultStage | ManageBorrowVaultStage
This variable is called TAllVaultStages but contains only common state across managing flows. 

Additionally I'm not sure if we want to introduce new naming convention for types (I'm referring to "T" prefix).

Last thing - I know that current folder structure will be refactored soon but we could already think about folders devoted for types for specific flows.

2021-12-21 13:48 UTC, sennett commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
> +  const _depositAmount = depositAmount || new BigNumber(0)
Nice.  Sorted.

2021-12-21 14:00 UTC, sennett commented on features/openMultiplyVault/common/TAllVaultStages.ts
> +export type TAllVaultStages = ManageMultiplyVaultStage | ManageBorrowVaultStage
Yeah looking for feedback on the TPrefix.  I started adding it because this is a convention we used for Interfaces in C# which was helpful.  You can tell at a glance whether a file contains a Type (or Interface) or a concrete implementation.

Yeah I agree regarding folder structure.  We should do it in a quick fashion asap after christmas to avoid hilarious merge conflicts.

2021-12-21 16:55 UTC, sennett commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
> +  selectedCollateralAllowanceRadio: 'unlimited' | 'depositAmount' | 'custom'
Sorted

2021-12-21 16:56 UTC, sennett commented on features/openMultiplyVault/common/ManageVaultCollateralAllowance.tsx
> +              {t('token-depositing', { token, amount: formatCryptoBalance(_depositAmount!) })}
Thanks/

2021-12-22 09:41 UTC, sennett commented on features/openMultiplyVault/common/TAllVaultStages.ts
> +export type TAllVaultStages = ManageMultiplyVaultStage | ManageBorrowVaultStage
I removed the T prefix and put them in their own directory.

2022-01-07 08:56 UTC, sennett commented
> Don't forget to delete this file as is empty for now :)
> 
> features/openMultiplyVault/common/TProxyChange.ts

Done!

2022-01-07 14:09 UTC, piekczyk approved these changes

2022-01-07 14:09 UTC, piekczyk commented on features/openMultiplyVault/common/ManageVaultDaiAllowance.tsx
> +export type SelectedDaiAllowanceRadio = 'unlimited' | 'paybackAmount' | 'custom'
not for now but we could think about moving types which are exported from components to common file (that should ensure that we won't fall into circular dependency)

2022-01-07 14:09 UTC, piekczyk commented on .gitignore
> +/types
hmm, normally this slash is not needed for defining paths in root folder. Since you are using macOs it's weird that you had to add it

2022-01-07 14:10 UTC, sennett commented on features/openMultiplyVault/common/ManageVaultDaiAllowance.tsx
> +export type SelectedDaiAllowanceRadio = 'unlimited' | 'paybackAmount' | 'custom'
+1

2022-01-07 14:11 UTC, sennett commented on .gitignore
> +/types
It was needed because this rule was picking up the nested `features/openMultiplyVault/common/types` dir.

2022-01-07 14:11 UTC, merged