feat: add ens name and avatar support
OasisDEX/oasis-borrow pull request #677
Opened 2021-12-21 04:20 UTC by bigint

# Add ens name and avatar support
  
## Changes 👷‍♀️

- Removed react-jazzicon which is unmaintained for 3 years
- Add davatar package which has ens avatar support
- Add useENS hook

<img width="494" alt="image" src="https://user-images.githubusercontent.com/69431456/146870395-fafd6828-21a0-4471-8587-ce2873635f35.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/69431456/146870416-b2106c9b-3fc6-479f-b890-935ceaf4f830.png">
  
## How to test 🧪

- Login with an account that has ens name
- Check the navbar
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-12-21 04:21 UTC, bigint commented
/cc @adamskrodzki @Padraic-O-Mhuiris

2021-12-21 04:25 UTC, bigint commented on features/account/Account.tsx
> +                  <Davatar size={30} address={account} generatedAvatarType="jazzicon" />
```suggestion
                  <Davatar size={28} address={account} generatedAvatarType="jazzicon" />
```

2021-12-21 06:17 UTC, adamskrodzki requested changes

2021-12-21 06:17 UTC, adamskrodzki commented on helpers/useENS.ts
> +  const infuraUrlBackend = `https://mainnet.infura.io/v3/${process.env.INFURA_PROJECT_ID_BACKEND}`
this should not be hardcoded here, 

search useAppContext and and context property for details

2021-12-21 10:26 UTC, closed without merging

2021-12-21 10:28 UTC, adamskrodzki commented
@bigint  closing for now, but we will implement this after new year. Thanks for contribution

2021-12-23 04:31 UTC, brantlymillegan commented
ser we're trying to get to 420 ENS integrations by the end of 2021