guni - close to dai click triggers form update
OasisDEX/oasis-borrow pull request #678
Opened 2021-12-21 08:00 UTC by piekczyk

# [Guni form update](https://app.shortcut.com/oazo-apps/story/3208/update-guni-manage-so-that-the-close-needs-to-be-clicked-for-the-order-information-to-show)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- user has to click on close to dai button in order to see changes information
  
## How to test 🧪
  <Please explain how to test your changes>
- heroku
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2021-12-21 08:42 UTC, adamskrodzki approved these changes

2021-12-21 08:42 UTC, adamskrodzki commented on features/manageGuniVault/manageGuniVault.ts
> +  const s7 = applyGuniDataChanges(s6, change as GuniTxDataChange)
reversed parameter order, mistake or inconsistency ?

2021-12-21 08:42 UTC, adamskrodzki commented on features/openMultiplyVault/variants/guni/manage/GuniManageMultiplyVaultForm.tsx
> +          {stage !== 'adjustPosition' && <ManageMultiplyVaultButton {...props} />}
button do not display at all instead of being disabled ?

2021-12-21 09:11 UTC, adamskrodzki requested changes

2021-12-21 09:11 UTC, adamskrodzki commented on features/openMultiplyVault/variants/guni/manage/GuniManageMultiplyVaultEditing.tsx
> +      {!debt.isZero() && <GuniManageMultiplyVaultChangesInformation {...props} />}
how not showing summary if debt is zero relates to the task ?

2021-12-21 10:01 UTC, adamskrodzki submitted a review, later dismissed

2021-12-21 11:44 UTC, piekczyk commented on features/openMultiplyVault/variants/guni/manage/GuniManageMultiplyVaultForm.tsx
> +          {stage !== 'adjustPosition' && <ManageMultiplyVaultButton {...props} />}
The first one - from my point of view displaying button which says "Adjust your position" (even if disabled) doesn't make sense from managing GUNI perspective.

![image](https://user-images.githubusercontent.com/39706811/146924786-39ba9bb1-b7db-4ab1-83da-2ab5e4883796.png)

2021-12-21 11:46 UTC, piekczyk commented on features/openMultiplyVault/variants/guni/manage/GuniManageMultiplyVaultEditing.tsx
> +      {!debt.isZero() && <GuniManageMultiplyVaultChangesInformation {...props} />}
I added this condition due to the fact that showing Changes information in form doesn't make sense when vault is already closed.

2021-12-21 11:48 UTC, piekczyk commented on features/manageGuniVault/manageGuniVault.ts
> +  const s7 = applyGuniDataChanges(s6, change as GuniTxDataChange)
I added applyManageGuniVaultTransition after s2 and thats why each state later is renamed.

2021-12-21 11:51 UTC, adamskrodzki commented on features/manageGuniVault/manageGuniVault.ts
> +  const s7 = applyGuniDataChanges(s6, change as GuniTxDataChange)
I ment that all except  applyGuniDataChanges
have parameter order 
change, state
and this one has
state, change 

which is inconsistent

2021-12-21 12:07 UTC, piekczyk commented on features/manageGuniVault/manageGuniVault.ts
> +  const s7 = applyGuniDataChanges(s6, change as GuniTxDataChange)
I see it now, definitely inconsistency, I will fix it.

2021-12-22 09:24 UTC, adamskrodzki approved these changes

2021-12-22 09:25 UTC, merged