slippage fix
OasisDEX/oasis-borrow pull request #684
Opened 2022-01-06 09:32 UTC by piekczyk

# [Slippage fix](https://app.shortcut.com/oazo-apps/story/3140/bug-slippage-wrongly-accounted-for-in-worst-case-market-price-calculation)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- adjusted slippage calculations
  
## How to test 🧪
  <Please explain how to test your changes>
- heroku / dev
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2022-01-06 15:01 UTC, adamskrodzki requested changes
While change is correct I think it is not applied everywhere gave several examples but that is not all most likely (found occurence also in calculations.ts)

2022-01-06 15:01 UTC, adamskrodzki commented on features/openMultiplyVault/openMultiplyVaultCalculations.ts
> +  const marketPriceMaxSlippage = marketPrice ? marketPrice.div(one.minus(slippage)) : undefined
In this file line 148 theree is also some thing I guess

I suggest to create util function 

applySlippage somwhere and then implement fix there and use function everywhere.

2022-01-07 08:51 UTC, adamskrodzki commented on features/openMultiplyVault/openMultiplyVaultCalculations.ts
> +  // const toTokenAmount = buyingCollateral
it might be ok, there should be in tx payload minToTOkenAmount which should be equal to buyingCollateral
and toTokenAmount should be equal to optimistic value (when actual slippage was 0)

2022-01-07 08:51 UTC, adamskrodzki commented on helpers/multiply/calculations.ts
> +  // TODO I guess we are calculating here extremes that's why one.minus
I think it is related to the fact if we are buying or selling here we are buying collateral

2022-01-10 09:51 UTC, sennett commented on features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
> +  const marketPriceMaxSlippage = marketPrice ? marketPrice.div(one.minus(slippage)) : undefined
This is covered under the guni slippage PR here I think?  https://github.com/OasisDEX/oasis-borrow/pull/638/files#diff-77ffa6529284a25a64d63d07c21c08c5a134723b7cd67c06c111ff6a7727d4cdR470

2022-01-10 10:30 UTC, piekczyk commented on features/openMultiplyVault/openMultiplyVaultCalculations.ts
> +  // const toTokenAmount = buyingCollateral
make sense, I will undo these comments

2022-01-10 10:39 UTC, piekczyk commented on features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
> +  const marketPriceMaxSlippage = marketPrice ? marketPrice.div(one.minus(slippage)) : undefined
@sennett true, I removed these changes from feature branch so this PR is now the only source of truth regarding slippage fix

2022-01-10 10:45 UTC, johnnieskywalker commented on features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
> +  const marketPriceMaxSlippage = marketPrice ? marketPrice.div(one.minus(slippage)) : undefined
Correct me if I'm wrong I'm not sure about the requirements. I'm not sure if we want to be strict about slipagge of swap or allow user to decide, and take the risk? IMHO in Piece of code mentioned here https://github.com/OasisDEX/oasis-borrow/blob/59d47caed86c012587e6f641e32e093bb1227481/features/openGuniVault/openGuniVault.ts#L443 uses pre-defined slippage of 0.1% for minimal to token amount and doesn't allow configuring this one.

2022-01-10 11:04 UTC, johnnieskywalker approved these changes

2022-01-10 11:05 UTC, merged