added product card to storybook
OasisDEX/oasis-borrow pull request #694
Opened 2022-01-11 14:39 UTC by piekczyk

# [Product card](https://app.shortcut.com/oazo-apps/story/3225/create-generic-product-card)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- added product card component to the storybook
  
## How to test 🧪
  <Please explain how to test your changes>
- storybook
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2022-01-11 15:25 UTC, paszkowskiDamian commented on components/FloatingLabel.tsx
> +  variant?: 'primary'
are there any other options available?

2022-01-11 15:31 UTC, paszkowskiDamian commented
Did you figure out what about this hover effect?

2022-01-11 15:32 UTC, johnnieskywalker commented
![image](https://user-images.githubusercontent.com/6871923/148972301-f906544e-3e33-481a-ae98-e211ec917b11.png)

![image](https://user-images.githubusercontent.com/6871923/148972337-a4603b14-20cb-4fc6-aa73-6412171d9262.png)

cards look as in design

2022-01-11 15:34 UTC, paszkowskiDamian submitted a review, later dismissed

2022-01-11 15:36 UTC, paszkowskiDamian commented on public/locales/en/common.json
> +    "with": "With {{value}} {{token}} \uD83D\uDC47",
Maybe we might need to use an image of emoji, other systems might display it differently than we want.

2022-01-11 15:38 UTC, sennett commented on components/ProductCard.tsx
> +  floatingLabel,
```suggestion
  floatingLabelText,
```

2022-01-11 15:38 UTC, sennett commented on components/FloatingLabel.tsx
> +export function FloatingLabel({
Does `FloatingLabel` get reused outside of `ProductCard`?  Perhaps we can keep them as their own files for now?

2022-01-11 15:39 UTC, johnnieskywalker requested changes
Please add keys and English texts to common.json for Spanish, Portuguese and Chinese then it is easier to find new keys and translate for our native-speaking colleagues

2022-01-11 15:43 UTC, johnnieskywalker commented on public/locales/en/common.json
> +    "with": "With {{value}} {{token}} \uD83D\uDC47",
It's supported on most modern operating systems one can check here https://emojipedia.org/backhand-index-pointing-down/
We can use it this way IMO

2022-01-12 08:03 UTC, piekczyk commented on components/FloatingLabel.tsx
> +  variant?: 'primary'
for now no, but I'm almost certain that we will have these labels with different colors as well. I'll keep it in my mind and if there won't be any other variant I will remove this logic.

2022-01-12 08:07 UTC, piekczyk commented on components/FloatingLabel.tsx
> +export function FloatingLabel({
No, but I wanted to keep components files as clean as possible to avoid situation that for example ProductCard.tsx will have 300 lines of code.

2022-01-12 08:08 UTC, piekczyk commented on components/ProductCard.tsx
> +  floatingLabel,
good catch, I will adjust it

2022-01-12 08:10 UTC, piekczyk commented
> Did you figure out what about this hover effect?

For now I didn't, it's part of another story:
https://app.shortcut.com/oazo-apps/story/3242/animate-asset-icons-on-hover

2022-01-12 09:12 UTC, johnnieskywalker approved these changes

2022-01-12 09:32 UTC, merged