added creating removeTrigger abi and filter
OasisDEX/oasis-borrow pull request #695
Opened 2022-01-11 15:08 UTC by johnnieskywalker

# [Title](https://clubhouseLink)

  
## Changes 👷‍♀️
- Reading RemoveTrigger events from blockchain
- Merging adding trigger and removing trigger into one list
- sorting list by blocknumber 
- determining what to return 
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2022-01-11 15:26 UTC, adamskrodzki requested changes

2022-01-11 15:26 UTC, adamskrodzki commented on features/automation/triggers/AutomationTriggersData.ts
> +    'event TriggerRemoved (index_topic_1 uint256 cdpId, index_topic_2 uint256 triggerId)'
this do not work, should be

'event TriggerRemoved (uint256 cdpId, uint256 triggerId)'

2022-01-11 15:26 UTC, adamskrodzki commented on features/automation/triggers/AutomationTriggersData.ts
>      const record: TriggerRecord = parseEvent(abi, singleEvent)
probably You need to extend TriggerRecord with blockNumber and LogIndex to know the order

2022-01-11 16:11 UTC, johnnieskywalker commented on features/automation/triggers/AutomationTriggersData.ts
>      const record: TriggerRecord = parseEvent(abi, singleEvent)
You think better way is to extend by creating new type that extends this one or just add blockNo and logIndex as it will be used for both AddTrigger and RemoveTrigger events ?

2022-01-11 16:13 UTC, johnnieskywalker commented on features/automation/triggers/AutomationTriggersData.ts
>      const record: TriggerRecord = parseEvent(abi, singleEvent)
Ok got it like this https://github.com/OasisDEX/oasis-borrow/pull/695/files#r782256401

2022-01-12 14:52 UTC, johnnieskywalker commented on features/automation/triggers/AutomationTriggersData.ts
> +  console.log(removedEventsList)
Guess triggerId and blockNumber

2022-01-12 15:46 UTC, johnnieskywalker commented on features/automation/triggers/AutomationTriggersData.ts
> +  console.log(removedEventsList)
I will do it this way but without type RemoveTriggerRecord extending TriggerRecord. I may miss some point but I see no value-added in such type inheritance. Remove triggers are already filtered by vaultId like that 
`  const filterFromTriggerRemoved = contract.filters.TriggerRemoved(vaultId, null)
`
Then I can just take one with highest blockNumber and then from `events` array remove adding triggers with older block number 
![image](https://user-images.githubusercontent.com/6871923/149172334-555ea09e-b02f-45b4-9745-6bfe23e767ee.png)

2022-01-13 10:40 UTC, johnnieskywalker commented on features/automation/triggers/AutomationTriggersData.ts
> +  console.log(removedEventsList)
so in such case event with newest block is on remove list so all trigers shall be removed

![image](https://user-images.githubusercontent.com/6871923/149314979-7eec3ff2-a1c9-4875-ae7e-82d383038ae1.png)

2022-01-13 17:12 UTC, rkrasiuk commented on features/automation/triggers/AutomationTriggersData.ts
> +// TODO - ŁW - Implement tests for this file
remove todo

2022-01-13 17:12 UTC, rkrasiuk commented on features/automation/triggers/AutomationTriggersData.ts
> +  const newestRemoveEvent = removedEventsList[removedEventsList.length - 1]
try avoiding mutating in place
```ts
const newestRemoteEvent = removedEventsList.reduce((latest, event) => latest?.blockNumber > event.blockNumber ? latest : event, null)
```

2022-01-14 09:55 UTC, johnnieskywalker commented on features/automation/triggers/AutomationTriggersData.ts
> +  const newestRemoveEvent = removedEventsList[removedEventsList.length - 1]
Changed to 
```
  const newestRemoveEvent = removedEventsList.reduce((latest, event) => latest?.blockNumber > event.blockNumber ? latest : event)

```
and re-tested

![image](https://user-images.githubusercontent.com/6871923/149496065-20366216-606c-4dfb-9719-cb17a52621a0.png)

2022-01-14 10:18 UTC, adamskrodzki commented on features/automation/triggers/AutomationTriggersData.ts
> +  const newestRemoveEvent = removedEventsList.reduce((latest, event) =>
check before if there are eany events here

2022-01-14 10:20 UTC, adamskrodzki commented on features/automation/triggers/AutomationTriggersData.ts
> +  const newestRemoveEvent = removedEventsList.reduce((latest, event) =>
if no skip addedEventsList filtering

2022-01-14 10:22 UTC, rkrasiuk commented on features/automation/triggers/AutomationTriggersData.ts
> +  removedEventsList.sort((event1, event2) => (event1.blockNumber > event2.blockNumber ? 1 : -1))
the reduce that you implemented according to the comment makes this `.sort` unnecessary

2022-01-17 12:55 UTC, adamskrodzki approved these changes

2022-01-17 12:56 UTC, merged