Asset page
OasisDEX/oasis-borrow pull request #723
Opened 2022-01-19 15:04 UTC by paszkowskiDamian

# [Asset page](https://app.shortcut.com/oazo-apps/story/3231/create-assets-page)

  
## Changes 👷‍♀️
- Assets page created, based on config in `feature/content`
- Landing page pills, TODO
  
## How to test 🧪
- Navigate to `/asset/eth`
- Navigate to `/asset/lp-token`
- Test what happens when user inputs wrong url

see all available options in `content.ts`

## Missing:
- Content for description and links
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2022-01-19 17:25 UTC, sennett requested changes
Why we have two sets of pages and views, one for LP and all the others in [assets.tsx]?  Could the LP tokens be another entry in `ASSETS_PAGES` and then we can avoid this duplication?

From testing, Dai and USDC pages do not contain any product cards on either of their tabs.  Dai only has earn so perhaps we can comment it out for now?

Not sure where USDC is in this mapping of Ilk to product type in the description here: https://app.shortcut.com/oazo-apps/epic/3222/asset-landing-pages-redesign?cf_workflow=500000053&ct_workflow=all

2022-01-19 17:25 UTC, sennett commented on features/homepage/HomepageView.tsx
> +        <Pill label={pill.label} link={pill.link} icon={pill.icon} />
Need a key on Pill here.

2022-01-20 10:36 UTC, piekczyk requested changes

2022-01-20 10:36 UTC, piekczyk commented on content/landing.ts
> +export const PILLS = [
I know thats for landing only but since it's exported it would be good to provide more meaningful name like for example LANDING_PILLS.

2022-01-20 10:36 UTC, piekczyk commented on pages/asset/[asset].tsx
> +AssetPage.layout = AppLayout
You can use ProductPagesLayout here for correct background in the header

2022-01-20 10:36 UTC, piekczyk commented on features/asset/LpTokenView.tsx
> +              productCards={productCardsData
Here you could use uniLpProductCards mapping method from productCards.ts

2022-01-20 10:36 UTC, piekczyk commented on pages/asset/lp-token.tsx
> +AssetPage.layout = AppLayout
You can use ProductPagesLayout here for correct background in the header

2022-01-20 15:46 UTC, piekczyk approved these changes

2022-01-20 16:08 UTC, sennett submitted a review, later dismissed

2022-01-21 09:28 UTC, sennett approved these changes

2022-01-21 11:44 UTC, sennett approved these changes

2022-01-21 11:45 UTC, merged