Institutional Vaults view.
OasisDEX/oasis-borrow pull request #842
Opened 2022-02-21 16:00 UTC by ferni

# [Create left side of manage institutional vault page inside storybook](https://app.shortcut.com/oazo-apps/story/3570/create-left-side-of-manage-institutional-vault-page-inside-storybook)

Plus this story: [Create new form for institutional vaults based on borrow UI](https://app.shortcut.com/oazo-apps/story/3548/create-new-form-for-institutional-vaults-based-on-borrow-ui)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>

- Add ManageInstiVaultContainer.
- Refactor some components of ManageVaultContainer (borrow), so they can be customized a bit, enough to accommodate for institutional vaults.
- Use ManageInstiVaultContainer on GeneralManageVaultView, with mock data.

## How to test 🧪
  <Please explain how to test your changes>

- On GeneralManageVaultView.tsx file: Add your borrow vault id as a BigNumber to INSTI_VAULT_IDS array, then your vault would show up as an institutional vault. Everything should work the same as borrow.
- The normal borrow vaults should still work normally as well (considering it's been refactored).
- See design here: https://www.notion.so/oazo/Institutional-vaults-DSS-charter-0e1ad01cac574f4cbcdbbeec8d18515d

2022-02-28 13:27 UTC, sennett requested changes

2022-02-28 14:00 UTC, ferni commented on helpers/formatters/format.ts
> +
Yeah, I've seen formatPercent used like that a lot, so I've extracted it. And on the vast majority of cases, it was for displaying a ratio. But if you want we could discuss some other name for it.

2022-02-28 14:08 UTC, ferni commented on helpers/formatters/format.ts
> +
Could be formatDecimalAsPercent

2022-03-01 05:43 UTC, ferni commented on helpers/formatters/format.ts
> +
Added test.

2022-03-01 09:06 UTC, sennett approved these changes

2022-03-01 13:04 UTC, merged