saving after liquidation value fix
OasisDEX/oasis-borrow pull request #854
Opened 2022-02-28 13:26 UTC by piekczyk

# [saving after liquidation value fix](https://clubhouseLink)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2022-02-28 15:13 UTC, adamskrodzki approved these changes

2022-02-28 15:16 UTC, adamskrodzki commented on components/vault/detailsCards/VaultDetailsCardMaxTokenOnStopLossTrigger.tsx
> +  const savingCompareToLiquidation = maxToken.minus(ethDuringLiquidation)
something is wrong here, if ethDuringLiquidation is smaller, savings are bigger ?

I guess it should be like:
ethDuringLiquidation,munus(collAvailable.multiplyBy(1-liquidationPenalty))

2022-02-28 15:18 UTC, adamskrodzki requested changes
see comment

2022-03-01 07:01 UTC, piekczyk commented on components/vault/detailsCards/VaultDetailsCardMaxTokenOnStopLossTrigger.tsx
> +  const savingCompareToLiquidation = maxToken.minus(ethDuringLiquidation)
That's correct. Maybe variable names are somehow misleading. I would rather say - if maxToken amount is higher, savings are bigger. I didn't include liquidationPenalty so I will add in in the minute.

2022-03-10 13:37 UTC, adamskrodzki approved these changes

2022-03-10 14:56 UTC, merged