automation UI persistence
OasisDEX/oasis-borrow pull request #861
Opened 2022-03-01 15:43 UTC by adamskrodzki

# [Title](https://clubhouseLink)

<please insert a clubhouse link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...
    
## Definition of done ✔️

- [ ] Acceptance criteria for each issue met
- [ ] Unit tests written where needed and passing
- [ ] End-to-end tests for happy path
- [ ] Documentation updated <When applicable>
- [ ] Project builds without errors
- [ ] Non-functional requirements met
- [ ] Code reviewed and functionality tested by the reviewer (locally, Heroku, etc.)
- [ ] Feature verified and accepted by Product Owner
- [ ] Project deployed to production environment

2022-03-02 07:43 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> +  const isEditing = !lastUIState ? false : startingSlRatio !== lastUIState.selectedSLValue
possibly toCollateral bit should also be here

2022-03-02 08:20 UTC, piekczyk commented on components/dumb/TxStatusSection.tsx
> +        {txStatus && txHash && progressStatuses.includes(txStatus) && (
good catch

2022-03-02 22:04 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> -  type Action =
Extracted to another file

2022-03-02 22:04 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> -  const token = vault.token
moved up

2022-03-02 22:05 UTC, adamskrodzki commented on features/automation/controls/AdjustSlFormControl.tsx
> -  const dispatch = useUIChanges(reducerHandler, initial, uiSubjectName)
not sure why but this hook was causing problems, direct calls to publish work

2022-03-04 09:30 UTC, peculiarity commented on features/automation/common/UITypes/AddFormChange.ts
> +  txDetails?: {
Why not simply call it `tx` and then you will haave:
```
tx: {
  status: TxStatus,
  hash: string,
  const: BigNumber
}
```

2022-03-04 09:31 UTC, peculiarity commented on components/dumb/SliderValuePicker.tsx
> +  const background = props.sliderPercentageFill
No offence but I have no idea what's happening in here.

2022-03-04 09:38 UTC, peculiarity requested changes

2022-03-04 09:38 UTC, peculiarity commented on features/automation/common/UITypes/RemoveFormChange.ts
> +      txDetails: {
Make sure you formated everything

2022-03-04 09:38 UTC, peculiarity commented on features/automation/common/UITypes/RemoveFormChange.ts
> +      txDetails: {
Also again the same comment regarding naming. Also keep it consistent. In the previous definition you named it `txCost` and here it's `totalCost` are these different? Can we have a single `Tx` type somewhere ?

2022-03-04 09:38 UTC, peculiarity commented on features/automation/common/UITypes/RemoveFormChange.ts
> +  txDetails?: {
Again ...

2022-03-04 09:38 UTC, peculiarity commented on features/automation/controls/AdjustSlFormLayout.tsx
> +  txState?: TxStatus
IF it's of type TxStatus why the variable name is called `txState`?

2022-03-04 09:38 UTC, peculiarity commented on features/automation/controls/AdjustSlFormControl.tsx
> +    txState: currentUIState?.txDetails?.txStatus,
if this property name was `txStatus` you would have simply used `...currentUIState?.txDetails`

2022-03-04 09:38 UTC, peculiarity commented on features/automation/controls/CancelSlFormControl.tsx
> +      console.log("New RemoveForm change", value)
Do we want to stick with these console logs for now or should we remove them ?

2022-03-04 09:38 UTC, peculiarity commented on features/automation/controls/CancelSlFormControl.tsx
> +          const gasUsed = successTx ? new BigNumber((transactionState as any).receipt.gasUsed) : zero
Why as `any` ?

2022-03-04 09:38 UTC, peculiarity commented on features/automation/controls/CancelSlFormLayout.tsx
> +            totalCost={new BigNumber(200)}
Hardcoded value ?

2022-03-04 09:49 UTC, peculiarity commented on features/automation/controls/CancelSlFormLayout.tsx
> +          txHash={(props.txState as any)?.txHash}
Isn't `props.txState` of type `TxStatus` ? This is a bug right there. I don't think you will get `txHash` value from there

2022-03-04 20:40 UTC, adamskrodzki commented on components/dumb/SliderValuePicker.tsx
> +  const background = props.sliderPercentageFill
hehe, me either ;)
It's @piekczyk code :D, as far as i can say it is that when you have slider left from dot it is one color and right from it is another.

2022-03-04 20:45 UTC, adamskrodzki commented on features/automation/common/UITypes/AddFormChange.ts
> +  txDetails?: {
it all needs to be nullable since it is not allways available, if it comes to name, It's arguable, it's not full tx payloac just some partial stuff

2022-03-07 07:52 UTC, adamskrodzki commented on features/automation/controls/CancelSlFormControl.tsx
> +          const gasUsed = successTx ? new BigNumber((transactionState as any).receipt.gasUsed) : zero
reciept is not allways available

2022-03-08 14:55 UTC, piekczyk commented on components/AppContext.ts
> +  uiChanges.configureSubject(ADD_FORM_CHANGE, formChangeReducer)
general remark - stuff like this should be used as initial state within rxjs scan operator, for now I think we should encapsulate it within new function which will eventually return already configured uiChanges

2022-03-09 08:17 UTC, adamskrodzki commented on components/AppContext.ts
> +  uiChanges.configureSubject(ADD_FORM_CHANGE, formChangeReducer)
can You provide example?

2022-03-10 12:04 UTC, piekczyk approved these changes

2022-03-10 12:06 UTC, merged