Institutional vault support
OasisDEX/oasis-borrow pull request #931
Opened 2022-04-05 09:54 UTC by sennett

# [Institutional vault support](https://app.shortcut.com/oazo-apps/story/3829/finalizing-institutional-vaults)

Adds provisional support for institutional vaults ("permissioned chartered vaults") on Goerli.  Does not include un-permissioned chartered vaults.

![image](https://user-images.githubusercontent.com/3783198/161725189-6f22f223-865e-4baa-94d6-5f71d25cc1a9.png)

User facing-changes
===

- Chartered "origination" fee, as a percentage of DAI generated.  Pre-existing stability fee still applies.
- Minimum active col. ratio - user cannot take vault debt below this amount.  User can de-risk vault back above this ratio.  Liquidation ratio still applies.
- Fixes a bug where prexisting vault debt was being factored in to dust-limit calcs.

Technical notes
===

Manage-borrow pipeline is reused, with two adapters passed in: one for standard borrow vaults and one for insti vaults.  These provide:

- initial view state
- vault calcs + user messages
- transaction costs

A new`InstiVault` type with corresponding pipe, that is mostly the same as standard vaults, with a a few additional properties.

Min active col ratio in business logic.  This is also used by standard borrow vaults: it is the same as the liquidation ratio in this case.

Testing
===

- Test using CDPID 134 on Goerli.  Wallet details here: https://www.notion.so/oazo/Dev-test-account-2603f91458004c309d31d3dd0af42aae
- The same wallet also has standard borrow CDPs that can be used to test.
- Regression test of open + manage borrow.

Next steps
===

Outside the scope of this PR.

- hydrate term end and fee data
- use goerli addresses from copy-paste goerli.json from https://chainlog.makerdao.com/
- complete INST-WBTC-A ilk - it should work but currently cannot test

Won't do
===

- un-permissioned chartered vaults

2022-04-05 13:18 UTC, piekczyk requested changes

2022-04-05 13:18 UTC, piekczyk commented on features/borrow/manage/pipes/adapters/institutionalBorrowManageAdapter.ts
> +  function check(currentColRatio: BigNumber, newColRatio: BigNumber) {
I guess this method could be moved outside of this block

2022-04-05 13:18 UTC, piekczyk commented on features/borrow/manage/pipes/adapters/institutionalBorrowManageAdapter.ts
> +        ...(viewState.vaultIsCurrentlyUnderMinActiveColRatio
looks a little bit hacky, shouldn't `vaultIsCurrentlyUnderMinActiveColRatio` be already within `viewState.warningMessages` at that point of time?

2022-04-05 13:18 UTC, piekczyk commented on features/borrow/manage/pipes/adapters/institutionalBorrowManageAdapter.ts
> +    const activeCollRatioPriceUSDAfter = collateralPriceAtRatio({
looks like const name could be just `afterActiveCollRatioPriceUSD`

2022-04-05 13:18 UTC, piekczyk commented on features/borrow/manage/pipes/adapters/standardBorrowManageAdapter.ts
> +    const s8 = applyManageVaultCalculations(s7, zero, s7.ilkData.liquidationRatio)
second and third argument could be assigned within this method since you are passing there s7 anyway

2022-04-05 13:18 UTC, piekczyk commented on features/instiVault/manage/containers/ManageInstiVaultDetails.tsx
> +          title={t('manage-insti-vault.card.term-end') + ' (mock values)'}
mock, to not forget

2022-04-05 13:35 UTC, piekczyk commented
![image](https://user-images.githubusercontent.com/39706811/161765695-6f424921-ade1-4db7-9f76-75797194bb1b.png)
`n/a` gas estimation leads to `NaN ETH` transaction fee

2022-04-05 13:55 UTC, sennett commented on blockchain/instiVault.ts
> +    nib$: (args: { ilk: string; usr: string }) => Observable<BigNumber>
Ah yup. Updated.

2022-04-05 13:56 UTC, sennett commented on blockchain/instiVault.ts
> +                  nextFeeChange: '1.4% at $20.4m',
Yes this is expected - we don't know these values yet.  This will happen before launch.

2022-04-05 15:46 UTC, sennett commented on blockchain/vault.maths.ts
> +    : new BigNumber('1e-18')
Moved.

2022-04-05 15:47 UTC, sennett commented on features/borrow/manage/pipes/adapters/institutionalBorrowManageAdapter.ts
> +  function check(currentColRatio: BigNumber, newColRatio: BigNumber) {
Yes moved.

2022-04-05 15:57 UTC, sennett commented on features/borrow/manage/pipes/adapters/standardBorrowManageAdapter.ts
> +    const s8 = applyManageVaultCalculations(s7, zero, s7.ilkData.liquidationRatio)
This is using the same business logic inside `applyManageVaultCalculations` for both borrow-standard and borrow-insti vaults:

- Borrow standard does not have an origination fee, so we pass in zero.
- The collateral ratio at which a standard borrow vault becomes inactive (i.e. the ratio under which the vault cannot have risk further increased) is the the liquidation ratio, so we pass the liquidation ratio for standard borrow vaults.

This way the business logic does not care what type of vault we are operating on, and the abstraction is cleaner, otherwise we have to pass in `isInsti: boolean` and extra nullable values into `applyManageVaultCalculations` on the view state.

2022-04-05 15:59 UTC, sennett commented
> ![image](https://user-images.githubusercontent.com/39706811/161764917-d6d67f9d-4934-442d-8a3a-45d6cf474d0d.png) should after pill be displayed as default?

> ![image](https://user-images.githubusercontent.com/39706811/161765695-6f424921-ade1-4db7-9f76-75797194bb1b.png) `n/a` gas estimation leads to `NaN ETH` transaction fee

Both sorted.

2022-04-08 03:47 UTC, ferni approved these changes
LGTM

2022-04-08 03:47 UTC, ferni commented on features/shared/checkOasisCDPType.ts
> +export function createCheckOasisCDPType$(
So this naming is going on the direction of generalizing the positions to not be only vaults. So "OasisCDP" would be the replacement?

2022-04-08 14:00 UTC, sennett commented on features/shared/checkOasisCDPType.ts
> +export function createCheckOasisCDPType$(
Yeah it's a step in that direction.  Not 100% set on the name but it's better than Vault.  Probably just "Position" is good enough, but it also will depend on what is happening with the other protocols.

2022-04-11 07:25 UTC, sennett commented
Seba approved via Discord.

2022-04-11 07:25 UTC, merged

2022-04-11 07:33 UTC, sennett commented on features/instiVault/manage/containers/ManageInstiVaultContainer.tsx
> +                      />
Oh nice.  I'll change with the next PR.