Owner page vault loading time fix
OasisDEX/oasis-borrow pull request #961
Opened 2022-04-15 11:40 UTC by piekczyk

# [Title](https://shortcutLink)

<please insert a shortcut link above>
  
## Changes 👷‍♀️
  <Please add short list of changes>
- item 1
  
## How to test 🧪
  <Please explain how to test your changes>
- step 1 ...

2022-04-19 10:44 UTC, adamskrodzki requested changes

2022-04-19 10:44 UTC, adamskrodzki commented on features/vaultsOverview/vaultsOverview.ts
> +  ) as unknown) as Observable<VaultWithSLData>
why not just 
` const allVaults = ((automationEnabled ? vaultWithAutomationData$ : vaults$(address)).pipe(
    map((vaults) => vaults.filter((vault) => ( vault.type === 'multiply' || vault.type ==='borrow') )),  ) as unknown) as Observable<VaultWithSLData>
`

2022-04-19 10:44 UTC, adamskrodzki commented on features/vaultsOverview/vaultsOverview.ts
> +  ) as unknown) as Observable<VaultWithSLData>
and then have single vaultsWithFilter$

2022-04-19 10:44 UTC, adamskrodzki commented on features/vaultsOverview/vaultsOverview.ts
> +  const multiplyVaults = ((automationEnabled ? vaultWithAutomationData$ : vaults$(address)).pipe(
is this generic enough to not be changed everytime new kind of trigger is introduced? Why automation data are event relevant here ?

2022-04-20 08:03 UTC, piotrkonowrocki reviewed
How big should be the difference in loading time between your branch and current main? I've tested it locally and sometimes I don't see a change at all, sometimes it can be faster by around 500ms.

But maybe it's because local environment isn't the fastest itself and it needs to be tested on staging?

2022-04-20 10:20 UTC, piekczyk commented on features/vaultsOverview/vaultsOverview.ts
> +  ) as unknown) as Observable<VaultWithSLData>
I guess it was done in that way because later borrow and multiply vaults are mapped as different properties so it's easier to split it on this level. I just extracted it as consts.

`  return combineLatest(
    vaultsWithFilter$(borrowVaults),
    vaultsWithFilter$(multiplyVaults),
    vaultsAddress$.pipe(map(getVaultsSummary)),
    ilksWithFilter$(ilksListWithBalances$),
  ).pipe(
    map(([borrow, multiply, vaultSummary, ilksWithFilters]) => ({
      vaults: {
        borrow,
        multiply,
      },
      vaultSummary,
      ilksWithFilters,
    })),
    distinctUntilChanged(isEqual),
  )`

2022-04-20 10:30 UTC, piekczyk commented on features/vaultsOverview/vaultsOverview.ts
> +  const multiplyVaults = ((automationEnabled ? vaultWithAutomationData$ : vaults$(address)).pipe(
We will need to extend vaultWithAutomationData$ pipe (and rename it for sure) with all extra stuff that we need - currently only stop loss information is needed. It is relevant here because we are showing Stop Loss On labels on the owner page where the borrow / multiple vault lists are. 

![image](https://user-images.githubusercontent.com/39706811/164212036-795fc0e4-d820-456a-8833-663a90e14f4c.png)

2022-04-20 10:43 UTC, piekczyk commented
> How big should be the difference in loading time between your branch and current main? I've tested it locally and sometimes I don't see a change at all, sometimes it can be faster by around 500ms.
> 
> But maybe it's because local environment isn't the fastest itself and it needs to be tested on staging?

Main issue here was that owner page was loaded with empty vault lists and after some time list were loaded. Right now when loading spinner disappears all data should be already there (number of vaults + vault lists). With this fix whole state should be generated all at once instead of providing dummy initial state for lists and then waiting till new block arrives (so in the end it should be faster but it's hard to say how much faster since it depends on blocks).


Issue described above is visible on the screen below
![image](https://user-images.githubusercontent.com/39706811/164212995-3953220f-8bc6-457b-b479-1b2b884d4efc.png)

2022-04-20 11:24 UTC, adamskrodzki approved these changes

2022-04-20 11:53 UTC, piotrkonowrocki approved these changes
Okay, now I see, works as intended 👌

2022-04-20 12:31 UTC, merged